<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 8 Penaksiran Secara Statistika | Statistika Lingkungan Menggunakan R</title>
  <meta name="description" content="Buku yang membahas penerapan R pada komputasi statistik di bidang Teknik Lingkungan">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 8 Penaksiran Secara Statistika | Statistika Lingkungan Menggunakan R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="cover.png" />
  <meta property="og:description" content="Buku yang membahas penerapan R pada komputasi statistik di bidang Teknik Lingkungan" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Penaksiran Secara Statistika | Statistika Lingkungan Menggunakan R" />
  
  <meta name="twitter:description" content="Buku yang membahas penerapan R pada komputasi statistik di bidang Teknik Lingkungan" />
  <meta name="twitter:image" content="cover.png" />

<meta name="author" content="Moh. Rosidi">


<meta name="date" content="2019-04-11">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="Rosidi.png">
  <link rel="shortcut icon" href="Rosidi.png" type="image/x-icon">
<link rel="prev" href="ekplorasi-data-menggunakan-grafik.html">

<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #0000ff; } /* Keyword */
code > span.ch { color: #008080; } /* Char */
code > span.st { color: #008080; } /* String */
code > span.co { color: #008000; } /* Comment */
code > span.ot { color: #ff4000; } /* Other */
code > span.al { color: #ff0000; } /* Alert */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #008000; font-weight: bold; } /* Warning */
code > span.cn { } /* Constant */
code > span.sc { color: #008080; } /* SpecialChar */
code > span.vs { color: #008080; } /* VerbatimString */
code > span.ss { color: #008080; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { } /* Variable */
code > span.cf { color: #0000ff; } /* ControlFlow */
code > span.op { } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #ff4000; } /* Preprocessor */
code > span.do { color: #008000; } /* Documentation */
code > span.an { color: #008000; } /* Annotation */
code > span.cv { color: #008000; } /* CommentVar */
code > span.at { } /* Attribute */
code > span.in { color: #008000; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistika Lingkungan Menggunakan R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Pengantar</a></li>
<li class="part"><span><b>Bahasa Pemrograman R</b></span></li>
<li class="chapter" data-level="1" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html"><i class="fa fa-check"></i><b>1</b> Mengenal Bahasa R</a><ul>
<li class="chapter" data-level="1.1" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#sejarah-r"><i class="fa fa-check"></i><b>1.1</b> Sejarah R</a></li>
<li class="chapter" data-level="1.2" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#fitur-dan-karakteristik-r"><i class="fa fa-check"></i><b>1.2</b> Fitur dan Karakteristik R</a></li>
<li class="chapter" data-level="1.3" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#kelebihan-dan-kekurangan-r"><i class="fa fa-check"></i><b>1.3</b> Kelebihan dan Kekurangan R</a></li>
<li class="chapter" data-level="1.4" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#rstudio"><i class="fa fa-check"></i><b>1.4</b> RStudio</a></li>
<li class="chapter" data-level="1.5" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#menginstall-r-dan-rstudio"><i class="fa fa-check"></i><b>1.5</b> Menginstall R dan RStudio</a></li>
<li class="chapter" data-level="1.6" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#working-directory"><i class="fa fa-check"></i><b>1.6</b> Working Directory</a><ul>
<li class="chapter" data-level="1.6.1" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#mengubah-lokasi-working-directory"><i class="fa fa-check"></i><b>1.6.1</b> Mengubah Lokasi Working Directory</a></li>
<li class="chapter" data-level="1.6.2" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#mengubah-lokasi-working-directory-default"><i class="fa fa-check"></i><b>1.6.2</b> Mengubah Lokasi Working Directory Default</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#fasilitas-help"><i class="fa fa-check"></i><b>1.7</b> Fasilitas Help</a><ul>
<li class="chapter" data-level="1.7.1" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#mencari-help-dari-suatu-perintah-tertentu"><i class="fa fa-check"></i><b>1.7.1</b> Mencari Help dari Suatu Perintah Tertentu</a></li>
<li class="chapter" data-level="1.7.2" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#general-help"><i class="fa fa-check"></i><b>1.7.2</b> General Help</a></li>
<li class="chapter" data-level="1.7.3" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#fasilitas-help-lainnya"><i class="fa fa-check"></i><b>1.7.3</b> Fasilitas Help Lainnya</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#referensi"><i class="fa fa-check"></i><b>1.8</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html"><i class="fa fa-check"></i><b>2</b> Sintaks Bahasa R</a><ul>
<li class="chapter" data-level="2.1" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#operator-aritmatika"><i class="fa fa-check"></i><b>2.1</b> Operator Aritmatika</a></li>
<li class="chapter" data-level="2.2" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#fungsi-aritmetik"><i class="fa fa-check"></i><b>2.2</b> Fungsi Aritmetik</a></li>
<li class="chapter" data-level="2.3" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#operator-relasi"><i class="fa fa-check"></i><b>2.3</b> Operator Relasi</a></li>
<li class="chapter" data-level="2.4" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#operator-logika"><i class="fa fa-check"></i><b>2.4</b> Operator Logika</a></li>
<li class="chapter" data-level="2.5" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#memasukkan-nilai-kedalam-variabel"><i class="fa fa-check"></i><b>2.5</b> Memasukkan Nilai Kedalam Variabel</a></li>
<li class="chapter" data-level="2.6" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#tipe-data"><i class="fa fa-check"></i><b>2.6</b> Tipe Data</a></li>
<li class="chapter" data-level="2.7" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#vektor"><i class="fa fa-check"></i><b>2.7</b> Vektor</a><ul>
<li class="chapter" data-level="2.7.1" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#membuat-vektor"><i class="fa fa-check"></i><b>2.7.1</b> Membuat vektor</a></li>
<li class="chapter" data-level="2.7.2" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#missing-values"><i class="fa fa-check"></i><b>2.7.2</b> Missing Values</a></li>
<li class="chapter" data-level="2.7.3" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#subset-pada-vektor"><i class="fa fa-check"></i><b>2.7.3</b> Subset Pada Vektor</a></li>
<li class="chapter" data-level="2.7.4" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#perhitungan-menggunakan-vektor"><i class="fa fa-check"></i><b>2.7.4</b> Perhitungan Menggunakan Vektor</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#matriks"><i class="fa fa-check"></i><b>2.8</b> Matriks</a><ul>
<li class="chapter" data-level="2.8.1" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#membuat-matriks"><i class="fa fa-check"></i><b>2.8.1</b> Membuat matriks</a></li>
<li class="chapter" data-level="2.8.2" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#subset-pada-matriks"><i class="fa fa-check"></i><b>2.8.2</b> Subset Pada Matriks</a></li>
<li class="chapter" data-level="2.8.3" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#perhitungan-menggunakan-matriks"><i class="fa fa-check"></i><b>2.8.3</b> Perhitungan Menggunakan Matriks</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#faktor"><i class="fa fa-check"></i><b>2.9</b> Faktor</a><ul>
<li class="chapter" data-level="2.9.1" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#membuat-variabel-faktor"><i class="fa fa-check"></i><b>2.9.1</b> Membuat Variabel Faktor</a></li>
<li class="chapter" data-level="2.9.2" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#perhitungan-menggunakan-faktor"><i class="fa fa-check"></i><b>2.9.2</b> Perhitungan Menggunakan Faktor</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#data-frames"><i class="fa fa-check"></i><b>2.10</b> Data Frames</a><ul>
<li class="chapter" data-level="2.10.1" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#membuat-data-frame"><i class="fa fa-check"></i><b>2.10.1</b> Membuat Data Frame</a></li>
<li class="chapter" data-level="2.10.2" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#subset-pada-data-frame"><i class="fa fa-check"></i><b>2.10.2</b> Subset Pada Data Frame</a></li>
<li class="chapter" data-level="2.10.3" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#memperluas-data-frame"><i class="fa fa-check"></i><b>2.10.3</b> Memperluas Data Frame</a></li>
<li class="chapter" data-level="2.10.4" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#perhitungan-pada-data-frame"><i class="fa fa-check"></i><b>2.10.4</b> Perhitungan Pada Data Frame</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#list"><i class="fa fa-check"></i><b>2.11</b> List</a><ul>
<li class="chapter" data-level="2.11.1" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#membuat-list"><i class="fa fa-check"></i><b>2.11.1</b> Membuat List</a></li>
<li class="chapter" data-level="2.11.2" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#subset-list"><i class="fa fa-check"></i><b>2.11.2</b> Subset List</a></li>
<li class="chapter" data-level="2.11.3" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#memperluas-list"><i class="fa fa-check"></i><b>2.11.3</b> Memperluas List</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#loop"><i class="fa fa-check"></i><b>2.12</b> Loop</a><ul>
<li class="chapter" data-level="2.12.1" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#for-loop"><i class="fa fa-check"></i><b>2.12.1</b> For Loop</a></li>
<li class="chapter" data-level="2.12.2" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#while-loop"><i class="fa fa-check"></i><b>2.12.2</b> While Loop</a></li>
<li class="chapter" data-level="2.12.3" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#repeat-loop"><i class="fa fa-check"></i><b>2.12.3</b> Repeat Loop</a></li>
<li class="chapter" data-level="2.12.4" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#break"><i class="fa fa-check"></i><b>2.12.4</b> Break</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#decision-making"><i class="fa fa-check"></i><b>2.13</b> Decision Making</a><ul>
<li class="chapter" data-level="2.13.1" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#if-statement"><i class="fa fa-check"></i><b>2.13.1</b> if statement</a></li>
<li class="chapter" data-level="2.13.2" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#if-else-statement"><i class="fa fa-check"></i><b>2.13.2</b> if else statement</a></li>
<li class="chapter" data-level="2.13.3" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#switch-statement"><i class="fa fa-check"></i><b>2.13.3</b> switch statement</a></li>
</ul></li>
<li class="chapter" data-level="2.14" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#fungsi"><i class="fa fa-check"></i><b>2.14</b> Fungsi</a></li>
<li class="chapter" data-level="2.15" data-path="sintaks-bahasa-r.html"><a href="sintaks-bahasa-r.html#referensi-1"><i class="fa fa-check"></i><b>2.15</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html"><i class="fa fa-check"></i><b>3</b> Manajemen Data R</a><ul>
<li class="chapter" data-level="3.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#import-file"><i class="fa fa-check"></i><b>3.1</b> Import File</a><ul>
<li class="chapter" data-level="3.1.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#import-file-menggunakan-fungsi-bawaan-r"><i class="fa fa-check"></i><b>3.1.1</b> Import File Menggunakan Fungsi Bawaan R</a></li>
<li class="chapter" data-level="3.1.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#membaca-file-csv-dan-txt-menggunakan-library-readr"><i class="fa fa-check"></i><b>3.1.2</b> Membaca File CSV dan TXT Menggunakan Library readr</a></li>
<li class="chapter" data-level="3.1.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#import-file-excel-pada-r"><i class="fa fa-check"></i><b>3.1.3</b> Import File Excel Pada R</a></li>
<li class="chapter" data-level="3.1.4" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#membaca-file-dari-format-aplikasi-statistik"><i class="fa fa-check"></i><b>3.1.4</b> Membaca File Dari Format Aplikasi Statistik</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#eksport-file"><i class="fa fa-check"></i><b>3.2</b> Eksport File</a><ul>
<li class="chapter" data-level="3.2.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#eksport-data-menjadi-format-txt-dan-csv"><i class="fa fa-check"></i><b>3.2.1</b> Eksport Data Menjadi Format TXT dan CSV</a></li>
<li class="chapter" data-level="3.2.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#eksport-data-menjadi-format-excel"><i class="fa fa-check"></i><b>3.2.2</b> Eksport Data Menjadi Format Excel</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#tibble-data-format"><i class="fa fa-check"></i><b>3.3</b> Tibble Data Format</a><ul>
<li class="chapter" data-level="3.3.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#membuat-tibble"><i class="fa fa-check"></i><b>3.3.1</b> Membuat Tibble</a></li>
<li class="chapter" data-level="3.3.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#tibble-vs-data-frame"><i class="fa fa-check"></i><b>3.3.2</b> Tibble vs Data Frame</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#merapikan-data"><i class="fa fa-check"></i><b>3.4</b> Merapikan Data</a><ul>
<li class="chapter" data-level="3.4.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#gather"><i class="fa fa-check"></i><b>3.4.1</b> Gather</a></li>
<li class="chapter" data-level="3.4.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#spread"><i class="fa fa-check"></i><b>3.4.2</b> Spread</a></li>
<li class="chapter" data-level="3.4.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#separate"><i class="fa fa-check"></i><b>3.4.3</b> Separate</a></li>
<li class="chapter" data-level="3.4.4" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#unite"><i class="fa fa-check"></i><b>3.4.4</b> Unite</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#transformasi-data"><i class="fa fa-check"></i><b>3.5</b> Transformasi Data</a><ul>
<li class="chapter" data-level="3.5.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#paket-dplyr"><i class="fa fa-check"></i><b>3.5.1</b> Paket dplyr</a></li>
<li class="chapter" data-level="3.5.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#filter"><i class="fa fa-check"></i><b>3.5.2</b> filter()</a></li>
<li class="chapter" data-level="3.5.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#arrange"><i class="fa fa-check"></i><b>3.5.3</b> arrange()</a></li>
<li class="chapter" data-level="3.5.4" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#select"><i class="fa fa-check"></i><b>3.5.4</b> select()</a></li>
<li class="chapter" data-level="3.5.5" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#mutate"><i class="fa fa-check"></i><b>3.5.5</b> mutate()</a></li>
<li class="chapter" data-level="3.5.6" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#summarize-dan-group_by"><i class="fa fa-check"></i><b>3.5.6</b> summarize() dan group_by()</a></li>
<li class="chapter" data-level="3.5.7" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#mengkombinasikan-beberapa-operasi-menggunakan-operator-pipe"><i class="fa fa-check"></i><b>3.5.7</b> Mengkombinasikan Beberapa Operasi Menggunakan Operator Pipe (%&gt;%)</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#referensi-2"><i class="fa fa-check"></i><b>3.6</b> Referensi</a></li>
</ul></li>
<li class="part"><span><b>Visualisasi Data - R</b></span></li>
<li class="chapter" data-level="4" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html"><i class="fa fa-check"></i><b>4</b> Visualisasi Data Menggunakan Fungsi Dasar R</a><ul>
<li class="chapter" data-level="4.1" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#visualisasi-data-menggunakan-fungsi-plot"><i class="fa fa-check"></i><b>4.1</b> Visualisasi Data Menggunakan Fungsi plot()</a></li>
<li class="chapter" data-level="4.2" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#matriks-scatterplot"><i class="fa fa-check"></i><b>4.2</b> Matriks Scatterplot</a></li>
<li class="chapter" data-level="4.3" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#box-plot"><i class="fa fa-check"></i><b>4.3</b> Box plot</a></li>
<li class="chapter" data-level="4.4" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#bar-plot"><i class="fa fa-check"></i><b>4.4</b> Bar Plot</a></li>
<li class="chapter" data-level="4.5" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#line-plot"><i class="fa fa-check"></i><b>4.5</b> Line Plot</a></li>
<li class="chapter" data-level="4.6" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#pie-chart"><i class="fa fa-check"></i><b>4.6</b> Pie Chart</a></li>
<li class="chapter" data-level="4.7" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#histogram-dan-density-plot"><i class="fa fa-check"></i><b>4.7</b> Histogram dan Density Plot</a></li>
<li class="chapter" data-level="4.8" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#qq-plot"><i class="fa fa-check"></i><b>4.8</b> QQ Plot</a></li>
<li class="chapter" data-level="4.9" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#dot-chart"><i class="fa fa-check"></i><b>4.9</b> Dot Chart</a></li>
<li class="chapter" data-level="4.10" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#kustomisasi-parameter-grafik"><i class="fa fa-check"></i><b>4.10</b> Kustomisasi Parameter Grafik</a><ul>
<li class="chapter" data-level="4.10.1" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#menambahkan-judul"><i class="fa fa-check"></i><b>4.10.1</b> Menambahkan Judul</a></li>
<li class="chapter" data-level="4.10.2" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#menambahkan-legend"><i class="fa fa-check"></i><b>4.10.2</b> Menambahkan Legend</a></li>
<li class="chapter" data-level="4.10.3" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#menambahkan-teks-pada-grafik"><i class="fa fa-check"></i><b>4.10.3</b> Menambahkan Teks Pada Grafik</a></li>
<li class="chapter" data-level="4.10.4" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#menambahkan-garis-pada-plot"><i class="fa fa-check"></i><b>4.10.4</b> Menambahkan Garis Pada Plot</a></li>
<li class="chapter" data-level="4.10.5" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#merubah-simbol-plot-dan-jenis-garis"><i class="fa fa-check"></i><b>4.10.5</b> Merubah Simbol plot dan Jenis Garis</a></li>
<li class="chapter" data-level="4.10.6" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#mengatur-axis-plot"><i class="fa fa-check"></i><b>4.10.6</b> Mengatur Axis Plot</a></li>
<li class="chapter" data-level="4.10.7" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#mengatur-warna"><i class="fa fa-check"></i><b>4.10.7</b> Mengatur Warna</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#alternatif-library-dasar-lain"><i class="fa fa-check"></i><b>4.11</b> Alternatif Library Dasar Lain</a><ul>
<li class="chapter" data-level="4.11.1" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#scatterplot-menggunakan-library-car"><i class="fa fa-check"></i><b>4.11.1</b> Scatterplot Menggunakan Library car</a></li>
<li class="chapter" data-level="4.11.2" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#matriks-scatterplot-menggunakan-library-psych"><i class="fa fa-check"></i><b>4.11.2</b> Matriks Scatterplot Menggunakan Library psych</a></li>
<li class="chapter" data-level="4.11.3" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#box-plot-menggunakan-library-gplots"><i class="fa fa-check"></i><b>4.11.3</b> Box Plot Menggunakan Library gplots</a></li>
<li class="chapter" data-level="4.11.4" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#qq-plot-menggunakan-library-car"><i class="fa fa-check"></i><b>4.11.4</b> QQ Plot Menggunakan Library car</a></li>
<li class="chapter" data-level="4.11.5" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#plot-group-means-menggunakan-library-gplots"><i class="fa fa-check"></i><b>4.11.5</b> Plot Group Means Menggunakan Library gplots</a></li>
</ul></li>
<li class="chapter" data-level="4.12" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#referensi-3"><i class="fa fa-check"></i><b>4.12</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html"><i class="fa fa-check"></i><b>5</b> Visualisasi Data Menggunakan GGPLOT</a><ul>
<li class="chapter" data-level="5.1" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#scatterplot"><i class="fa fa-check"></i><b>5.1</b> Scatterplot</a></li>
<li class="chapter" data-level="5.2" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#box-plot-dan-violin-plot"><i class="fa fa-check"></i><b>5.2</b> Box Plot dan Violin Plot</a></li>
<li class="chapter" data-level="5.3" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#bar-plot-1"><i class="fa fa-check"></i><b>5.3</b> Bar Plot</a></li>
<li class="chapter" data-level="5.4" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#line-plot-1"><i class="fa fa-check"></i><b>5.4</b> Line Plot</a></li>
<li class="chapter" data-level="5.5" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#pie-chart-1"><i class="fa fa-check"></i><b>5.5</b> Pie Chart</a></li>
<li class="chapter" data-level="5.6" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#histogram-dan-desity-plot"><i class="fa fa-check"></i><b>5.6</b> Histogram dan Desity Plot</a></li>
<li class="chapter" data-level="5.7" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#qq-plot-1"><i class="fa fa-check"></i><b>5.7</b> QQ Plot</a></li>
<li class="chapter" data-level="5.8" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#dot-plot"><i class="fa fa-check"></i><b>5.8</b> Dot Plot</a></li>
<li class="chapter" data-level="5.9" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#ecdf-plot"><i class="fa fa-check"></i><b>5.9</b> ECDF Plot</a></li>
<li class="chapter" data-level="5.10" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#parameter-grafik"><i class="fa fa-check"></i><b>5.10</b> Parameter Grafik</a><ul>
<li class="chapter" data-level="5.10.1" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#merubah-judul-grafik-keterangan-axis-dan-legend"><i class="fa fa-check"></i><b>5.10.1</b> Merubah Judul Grafik, Keterangan Axis dan Legend</a></li>
<li class="chapter" data-level="5.10.2" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#merubah-tampilan-dan-posisi-legend"><i class="fa fa-check"></i><b>5.10.2</b> Merubah Tampilan dan Posisi Legend</a></li>
<li class="chapter" data-level="5.10.3" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#merubah-warana-pada-grafik-secara-otomatis-dan-manual"><i class="fa fa-check"></i><b>5.10.3</b> Merubah Warana Pada Grafik Secara Otomatis dan Manual</a></li>
<li class="chapter" data-level="5.10.4" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#kustomisasi-titik"><i class="fa fa-check"></i><b>5.10.4</b> Kustomisasi Titik</a></li>
<li class="chapter" data-level="5.10.5" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#kustomisasi-jenis-garis"><i class="fa fa-check"></i><b>5.10.5</b> Kustomisasi Jenis Garis</a></li>
<li class="chapter" data-level="5.10.6" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#menambahkan-label-pada-titik-observasi-dan-bidang-plot"><i class="fa fa-check"></i><b>5.10.6</b> Menambahkan Label Pada Titik Observasi dan Bidang Plot</a></li>
<li class="chapter" data-level="5.10.7" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#kustomisasi-tema-pada-plot"><i class="fa fa-check"></i><b>5.10.7</b> Kustomisasi Tema Pada Plot</a></li>
<li class="chapter" data-level="5.10.8" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#penskalaan-dan-transformasi-axis"><i class="fa fa-check"></i><b>5.10.8</b> Penskalaan dan Transformasi Axis</a></li>
<li class="chapter" data-level="5.10.9" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#kustomisasi-tick-mark-axis"><i class="fa fa-check"></i><b>5.10.9</b> Kustomisasi Tick Mark Axis</a></li>
<li class="chapter" data-level="5.10.10" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#menambahkan-garis-lurus-pada-plot"><i class="fa fa-check"></i><b>5.10.10</b> Menambahkan Garis Lurus Pada Plot</a></li>
<li class="chapter" data-level="5.10.11" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#melakukan-rotasi-pada-grafik"><i class="fa fa-check"></i><b>5.10.11</b> Melakukan Rotasi Pada Grafik</a></li>
<li class="chapter" data-level="5.10.12" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#facet"><i class="fa fa-check"></i><b>5.10.12</b> Facet</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#referensi-4"><i class="fa fa-check"></i><b>5.11</b> Referensi</a></li>
</ul></li>
<li class="part"><span><b>Statistika Deskriptif - R</b></span></li>
<li class="chapter" data-level="6" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html"><i class="fa fa-check"></i><b>6</b> Ringkasan Numerik</a><ul>
<li class="chapter" data-level="6.1" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-pemusatan-data"><i class="fa fa-check"></i><b>6.1</b> Ukuran Pemusatan Data</a><ul>
<li class="chapter" data-level="6.1.1" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#pengukuran-klasik-mean"><i class="fa fa-check"></i><b>6.1.1</b> Pengukuran Klasik-Mean</a></li>
<li class="chapter" data-level="6.1.2" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#median-sebagai-ukuran-pemusatan-data-yang-resistan"><i class="fa fa-check"></i><b>6.1.2</b> Median Sebagai Ukuran Pemusatan Data yang Resistan</a></li>
<li class="chapter" data-level="6.1.3" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-pemusatan-data-lainnya"><i class="fa fa-check"></i><b>6.1.3</b> Ukuran Pemusatan Data Lainnya</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-sebaran-data"><i class="fa fa-check"></i><b>6.2</b> Ukuran Sebaran Data</a><ul>
<li class="chapter" data-level="6.2.1" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#pengukuran-klasik-varian-dan-simpangan-baku"><i class="fa fa-check"></i><b>6.2.1</b> Pengukuran Klasik (Varian dan Simpangan Baku)</a></li>
<li class="chapter" data-level="6.2.2" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-sebaran-data-yang-resisten-terhadap-outlier"><i class="fa fa-check"></i><b>6.2.2</b> Ukuran Sebaran Data yang Resisten Terhadap Outlier</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ringkasan-data-menggunakan-fungsi-summary-dan-stat.desc"><i class="fa fa-check"></i><b>6.3</b> Ringkasan Data Menggunakan Fungsi summary() dan stat.desc()</a></li>
<li class="chapter" data-level="6.4" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-kemencengan-data"><i class="fa fa-check"></i><b>6.4</b> Ukuran Kemencengan Data</a><ul>
<li class="chapter" data-level="6.4.1" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-kemencengan-klasik"><i class="fa fa-check"></i><b>6.4.1</b> Ukuran Kemencengan Klasik</a></li>
<li class="chapter" data-level="6.4.2" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-kemencengan-yang-resisten"><i class="fa fa-check"></i><b>6.4.2</b> Ukuran Kemencengan yang Resisten</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#outlier"><i class="fa fa-check"></i><b>6.5</b> Outlier</a></li>
<li class="chapter" data-level="6.6" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#transformasi-data-1"><i class="fa fa-check"></i><b>6.6</b> Transformasi Data</a></li>
<li class="chapter" data-level="6.7" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#referensi-5"><i class="fa fa-check"></i><b>6.7</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html"><i class="fa fa-check"></i><b>7</b> Ekplorasi Data Menggunakan Grafik</a><ul>
<li class="chapter" data-level="7.1" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-untuk-melihat-ditribusi-data"><i class="fa fa-check"></i><b>7.1</b> Grafik Untuk Melihat Ditribusi Data</a><ul>
<li class="chapter" data-level="7.1.1" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#histogram"><i class="fa fa-check"></i><b>7.1.1</b> Histogram</a></li>
<li class="chapter" data-level="7.1.2" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#density-plot"><i class="fa fa-check"></i><b>7.1.2</b> Density Plot</a></li>
<li class="chapter" data-level="7.1.3" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#qq-plot-2"><i class="fa fa-check"></i><b>7.1.3</b> QQ-plot</a></li>
<li class="chapter" data-level="7.1.4" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#box-plot-dan-violin-plot-1"><i class="fa fa-check"></i><b>7.1.4</b> Box Plot dan Violin Plot</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-untuk-melihat-beda-distribusi-data-antar-grup"><i class="fa fa-check"></i><b>7.2</b> Grafik Untuk Melihat Beda Distribusi Data Antar Grup</a></li>
<li class="chapter" data-level="7.3" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-untuk-memvisualisasikan-korelasi-antar-variabel"><i class="fa fa-check"></i><b>7.3</b> Grafik Untuk Memvisualisasikan Korelasi Antar Variabel</a></li>
<li class="chapter" data-level="7.4" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-yang-digunakan-untuk-memvisualisasikan-asosiasi-antar-variabel"><i class="fa fa-check"></i><b>7.4</b> Grafik Yang Digunakan Untuk Memvisualisasikan Asosiasi Antar Variabel</a></li>
<li class="chapter" data-level="7.5" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-yang-digunakan-untuk-memisualisasikan-ukuran-sampel-dan-perubahan-sepanjang-waktu"><i class="fa fa-check"></i><b>7.5</b> Grafik Yang Digunakan Untuk Memisualisasikan Ukuran Sampel dan Perubahan Sepanjang Waktu</a></li>
<li class="chapter" data-level="7.6" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#referensi-6"><i class="fa fa-check"></i><b>7.6</b> Referensi</a></li>
</ul></li>
<li class="part"><span><b>Statistika Inferensi - R</b></span></li>
<li class="chapter" data-level="8" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html"><i class="fa fa-check"></i><b>8</b> Penaksiran Secara Statistika</a><ul>
<li class="chapter" data-level="8.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#definisi-interval-estimasi"><i class="fa fa-check"></i><b>8.1</b> Definisi Interval Estimasi</a></li>
<li class="chapter" data-level="8.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interpretasi-interval-estimasi"><i class="fa fa-check"></i><b>8.2</b> Interpretasi Interval Estimasi</a></li>
<li class="chapter" data-level="8.3" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-median"><i class="fa fa-check"></i><b>8.3</b> Interval Kepercayaan Median</a><ul>
<li class="chapter" data-level="8.3.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-estimasi-median-metode-nonparametrik"><i class="fa fa-check"></i><b>8.3.1</b> Interval Estimasi Median Metode Nonparametrik</a></li>
<li class="chapter" data-level="8.3.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#metode-parametrik-interval-estimasi-median"><i class="fa fa-check"></i><b>8.3.2</b> Metode Parametrik Interval Estimasi Median</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-mean"><i class="fa fa-check"></i><b>8.4</b> Interval Kepercayaan Mean</a><ul>
<li class="chapter" data-level="8.4.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-mean-untuk-distribusi-yang-simetris"><i class="fa fa-check"></i><b>8.4.1</b> Interval Kepercayaan Mean Untuk Distribusi Yang Simetris</a></li>
<li class="chapter" data-level="8.4.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-mean-untuk-distribusi-yang-asimetris"><i class="fa fa-check"></i><b>8.4.2</b> Interval Kepercayaan Mean Untuk Distribusi Yang Asimetris</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-nonparametrik"><i class="fa fa-check"></i><b>8.5</b> Interval Prediksi Nonparametrik</a><ul>
<li class="chapter" data-level="8.5.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-nonparametrik-dua-sisi"><i class="fa fa-check"></i><b>8.5.1</b> Interval Prediksi Nonparametrik Dua Sisi</a></li>
<li class="chapter" data-level="8.5.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-nonparametrik-satu-sisi"><i class="fa fa-check"></i><b>8.5.2</b> Interval Prediksi Nonparametrik Satu Sisi</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-parametrik"><i class="fa fa-check"></i><b>8.6</b> Interval Prediksi Parametrik</a><ul>
<li class="chapter" data-level="8.6.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-distribusi-simetris"><i class="fa fa-check"></i><b>8.6.1</b> Interval Prediksi Distribusi Simetris</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://environmental-data-modeling.netlify.com/" target="blank">Author's Website</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistika Lingkungan Menggunakan R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="penaksiran-secara-statistika" class="section level1">
<h1><span class="header-section-number">Chapter 8</span> Penaksiran Secara Statistika</h1>
<p>Pada Chapter 6-Ringkasan Numerik kita telah belajar beberapa atribut kunci dari data seperti <span class="math inline">\(\overline{X}\)</span> dan <span class="math inline">\(s\)</span>. Kedua nilai tersebut disebut sebagai nilai estimasi sampel dari populasi (untuk mean <span class="math inline">\(\mu\)</span> dan simpangan baku <span class="math inline">\(\sigma\)</span>). Pada Chapter ini kita akan melakukan eksplorasi lebih jauh lagi mengenai interval estimasi (<em>interval estimate</em>) yang akan menyinggung kedua nilai tersebut lebih jauh.</p>
<div id="definisi-interval-estimasi" class="section level2">
<h2><span class="header-section-number">8.1</span> Definisi Interval Estimasi</h2>
<p>Median sampel dan mean sampel menyatakan titik pemusatan data. Estimasi menggunakan kedua nilai tersebut disebut sebagai estimasi titik (<em>point estimation</em>). Estimasi titik sendiri tidak menggambarkan reliabilitas atau kurangnya reliabilitas (variabilitas) dari estimasi ini. Sebagai contoh, anggaplah terdapat dua data X dan Y dengan mean 5 dengan jumlah observasi yang sama. Data Y memiliki nilai mean 5 dengan sangat sedikit variasi didalamnya, sedangkan data X jauh lebih bervariasi. Perkiraan titik 5 untuk X jauh lebih tidak dapat diandalkan dibandingkan dengan untuk Y karena variabilitas yang lebih besar dalam data X. Dengan kata lain, lebih banyak kehati-hatian diperlukan ketika menyatakan bahwa 5 memperkirakan mean populasi sebenarnya X daripada ketika menyatakan ini untuk Y. Melaporkan hanya perkiraan mean sampel (poin) 5 gagal memberikan petunjuk tentang perbedaan ini.</p>
<p>Sebagai alternatif untuk estimasi titik, estimasi interval adalah interval yang memiliki probabilitas yang dinyatakan mengandung nilai populasi sebenarnya. interval lebih lebar untuk set data yang memiliki variabilitas lebih besar. Jadi dalam contoh di atas, interval antara 4,7 dan 5,3 mungkin memiliki kemungkinan 95% untuk mengandung mean populasi Y yang sebenarnya (tidak diketahui). Butuh interval yang jauh lebih luas, katakanlah antara 2,0 dan 8,0, untuk memiliki probabilitas yang sama untuk mengandung rerata sebenarnya dari X. Karena itu, perbedaan keandalan dari dua estimasi dengan jelas dinyatakan menggunakan estimasi interval. Estimasi interval dapat memberikan dua informasi yang estimasi poin tidak dapat berikan, antara lain:</p>
<ol style="list-style-type: decimal">
<li>Pernyataan probabilitas atau kemungkinan bahwa interval berisi nilai populasi sebenarnya (keandalannya).</li>
<li>Pernyataan kemungkinan bahwa satu titik data dengan besaran tertentu berasal dari populasi yang diteliti.</li>
</ol>
<p>Estimasi interval untuk poin pertama disebut sebagai interval kepercayaan (<em>confidence interval</em>), sedangkan yang kedua disebut sebagai interval prediksi (<em>prediction interal</em>). Meskipun salin terkait, pembaca perlu berhati-hati sebab kedua definisi tersebut sering kali tertukar satu sama lain.</p>
</div>
<div id="interpretasi-interval-estimasi" class="section level2">
<h2><span class="header-section-number">8.2</span> Interpretasi Interval Estimasi</h2>
<p>Untuk lebih memahami mengenai definisi interval estimasi pada sub-chapter ini akan diberikan contoh yang diambil dari buku <strong>statistical Methods in Water Resources</strong> karya Helsel dan Hirsch (2012). Misalkan mean populasi sebenarnya <span class="math inline">\(\mu\)</span> konsentrasi dalam akuifer adalah 10. Sleain itu, anggaplah bahwa varians populasi sebenarnya <span class="math inline">\(\sigma^2\)</span> sama dengan 1. Karena nilai-nilai ini dalam praktiknya tidak pernah diketahui, sampel diambil untuk memperkirakannya dengan mean sampel <span class="math inline">\(x\)</span> dan sampel varianss <span class="math inline">\(s^2\)</span> . Dana yang cukup tersedia untuk mengambil 12 sampel air (kira-kira satu per bulan) selama satu tahun, dan hari-hari di mana pengambilan sampel terjadi dipilih secara acak. Dari 12 sampel ini <span class="math inline">\(x\)</span>x dan <span class="math inline">\(s^2\)</span> dihitung. Meskipun pada kenyataannya hanya satu set 12 sampel akan diambil setiap tahun, menggunakan komputer 12 hari dapat dipilih beberapa kali untuk menggambarkan konsep perkiraan interval. Untuk masing-masing dari 10 set independen dari 12 sampel, interval kepercayaan pada mean dihitung dengan menggunakan persamaan yang diberikan pada Tabel <a href="penaksiran-secara-statistika.html#tab:iie">8.1</a> dan Gambar <a href="penaksiran-secara-statistika.html#fig:iievis">8.1</a>.</p>
<table>
<caption><span id="tab:iie">Tabel 8.1: </span> Sepuluh interval kepercayaan 90% sekitar nilai mean sebenarnya sebesar 10 (Data berdistribusi normal dan Tanda plus menyatakan data tidak disertakan dalam nilai mean sebenarnya)</caption>
<thead>
<tr class="header">
<th><strong>No.</strong></th>
<th><strong>N</strong></th>
<th><strong>Mean</strong></th>
<th><strong>St.Dev</strong></th>
<th><strong>90% Interval kepercayaan</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>12</td>
<td>10,06</td>
<td>1,11</td>
<td>9,46 sampai 10,64</td>
</tr>
<tr class="even">
<td>2</td>
<td>12</td>
<td>10,60</td>
<td>0,81</td>
<td><span class="math inline">\(^+\)</span> 10,18 sampai 11,02</td>
</tr>
<tr class="odd">
<td>3</td>
<td>12</td>
<td>9,95</td>
<td>1,26</td>
<td>9,29 sampai 10,60</td>
</tr>
<tr class="even">
<td>4</td>
<td>12</td>
<td>10,18</td>
<td>1,26</td>
<td>9,52 sampai 10,83</td>
</tr>
<tr class="odd">
<td>5</td>
<td>12</td>
<td>10,17</td>
<td>1,33</td>
<td>9,48 sampai 10,85</td>
</tr>
<tr class="even">
<td>6</td>
<td>12</td>
<td>10,22</td>
<td>1,19</td>
<td>9,60 sampai 10,84</td>
</tr>
<tr class="odd">
<td>7</td>
<td>12</td>
<td>9,71</td>
<td>1,51</td>
<td>8,92 sampai 10,49</td>
</tr>
<tr class="even">
<td>8</td>
<td>12</td>
<td>9,90</td>
<td>1,01</td>
<td>9,38 sampai 10,43</td>
</tr>
<tr class="odd">
<td>9</td>
<td>12</td>
<td>9,95</td>
<td>0.10</td>
<td>9,43 sampai 10,46</td>
</tr>
<tr class="even">
<td>10</td>
<td>12</td>
<td>9,88</td>
<td>1,37</td>
<td>9,17 sampai 10,59</td>
</tr>
</tbody>
</table>
<p>Kesepuluh interval pada contoh di atas disebut dengan dengan <strong>interval kepercayaan 90%</strong> dari nilai mean sesungguhnya. Nilai mean sebenarnya akan terdapat pada interval tersebut dengan probabilitas 90%. Sehingga berdasarkan Tabel <a href="penaksiran-secara-statistika.html#tab:iie">8.1</a> terdapat 9 interval yang memiliki nilai mean sesungguhnya didalamnya (probabilitas 90%). Jika kita sekali lagi melakukan sampling dengan jumlah sampling yang sama pada interval nilai baru yang dihasilkan akan mengandung nilai mean sesungguhnya dan dapat juga tidak. Probabilitas interval tersebut mengandung nilai mean sesungguhnya disebut sebagai <strong>tingkat kepercayaan</strong> (<em>confidence level</em>). Probabilitas nilai interval tidak mengandung mean sesungguhnya disebut sebagai <strong>alpha level</strong> (<span class="math inline">\(\alpha\)</span>) yang ditulis berdasarkan Persamaan <a href="penaksiran-secara-statistika.html#eq:alpha">(8.1)</a>.</p>
<span class="math display" id="eq:alpha">\[\begin{equation}
  \alpha=1-confidence\ level\ 
  \tag{8.1}
\end{equation}\]</span>
<p>Lebar interval kepercayaan adalah fungsi dari bentuk distribusi data (variabilitas dan kemencengannya), ukuran sampel, dan tingkat kepercayaan yang diinginkan. Ketika tingkat kepercayaan meningkat, lebar interval juga meningkat, karena interval yang lebih besar lebih mungkin mengandung nilai sebenarnya daripada interval yang lebih pendek. Dengan demikian interval kepercayaan 95% akan lebih luas daripada interval 90% untuk data yang sama.</p>
<div class="figure" style="text-align: center"><span id="fig:iievis"></span>
<img src="iievis.PNG" alt="Sepuluh interval kepercayaan 90 persen data dengan nilai mean sebenarnya 10" width="65%" />
<p class="caption">
Gambar 8.1: Sepuluh interval kepercayaan 90 persen data dengan nilai mean sebenarnya 10
</p>
</div>
<p>Interval kepercayaan simetris pada rata-rata biasanya dihitung dengan asumsi data mengikuti distribusi normal. Jika tidak, distribusi rerata itu sendiri akan mendekati normal sepanjang ukuran sampel besar (katakanlah 50 pengamatan atau lebih besar). Interval kepercayaan dengan asumsi normalitas kemudian akan memasukkan mean sebenarnya (<span class="math inline">\(1-\alpha\)</span>)% dari waktu. Dalam contoh di atas, data dihasilkan dari distribusi normal, sehingga ukuran sampel kecil 12 tidak menjadi masalah. Namun ketika data memiliki kemencengan dan ukuran sampel di bawah 50 atau lebih, interval kepercayaan simetris tidak akan mengandung rata-rata (<span class="math inline">\(1-\alpha\)</span>)% sepanjang waktu. Dalam contoh di bawah ini, interval kepercayaan simetris secara salah dihitung untuk data yang miring (Gambar <a href="penaksiran-secara-statistika.html#fig:iiedata">8.2</a>). Hasil (Gambar <a href="penaksiran-secara-statistika.html#fig:iievis2">8.3</a> dan Tabel <a href="penaksiran-secara-statistika.html#tab:iie2">8.2</a>) menunjukkan bahwa interval kepercayaan kehilangan nilai sebenarnya dari 1 lebih sering daripada yang seharusnya. Semakin besar skewness, semakin besar ukuran sampel harus sebelum interval kepercayaan simetris dapat diandalkan. Sebagai alternatif, interval kepercayaan asimetris dapat dihitung untuk situasi umum data yang memiliki kemencengan.</p>
<table>
<caption><span id="tab:iie2">Tabel 8.2: </span> Sepuluh interval kepercayaan 90% sekitar nilai mean sebenarnya sebesar 1 (Data tidak berdistribusi normal dan Tanda plus menyatakan data tidak disertakan dalam nilai mean sebenarnya)</caption>
<thead>
<tr class="header">
<th><strong>No.</strong></th>
<th><strong>N</strong></th>
<th><strong>Mean</strong></th>
<th><strong>St.Dev</strong></th>
<th><strong>90% Interval kepercayaan</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>12</td>
<td>0,784</td>
<td>0,320</td>
<td><span class="math inline">\(^+\)</span> 0,618 sampai 0,950</td>
</tr>
<tr class="even">
<td>2</td>
<td>12</td>
<td>0,811</td>
<td>0,299</td>
<td><span class="math inline">\(^+\)</span> 0,656 sampai 0,966</td>
</tr>
<tr class="odd">
<td>3</td>
<td>12</td>
<td>1,178</td>
<td>0,700</td>
<td>0,815 sampai 1,541</td>
</tr>
<tr class="even">
<td>4</td>
<td>12</td>
<td>1,030</td>
<td>0,459</td>
<td>0,792 sampai 1,267</td>
</tr>
<tr class="odd">
<td>5</td>
<td>12</td>
<td>1,079</td>
<td>0,573</td>
<td>0,782 sampai 1,376</td>
</tr>
<tr class="even">
<td>6</td>
<td>12</td>
<td>0,833</td>
<td>0,363</td>
<td>0,644 sampai 1,021</td>
</tr>
<tr class="odd">
<td>7</td>
<td>12</td>
<td>0,789</td>
<td>0,240</td>
<td><span class="math inline">\(^+\)</span> 0,644 sampai 0,913</td>
</tr>
<tr class="even">
<td>8</td>
<td>12</td>
<td>1,159</td>
<td>0,815</td>
<td>0,736 sampai 1,581</td>
</tr>
<tr class="odd">
<td>9</td>
<td>12</td>
<td>0,822</td>
<td>0,365</td>
<td><span class="math inline">\(^+\)</span> 0,633 sampai 0,992</td>
</tr>
<tr class="even">
<td>10</td>
<td>12</td>
<td>0,837</td>
<td>0,478</td>
<td>0,589 sampai 1,085</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:iiedata"></span>
<img src="iiedata.PNG" alt="Histogram data dengan nilai mean populasi 1 dan simpangan baku populasi 0.75" width="70%" />
<p class="caption">
Gambar 8.2: Histogram data dengan nilai mean populasi 1 dan simpangan baku populasi 0.75
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:iievis2"></span>
<img src="iievis2.PNG" alt="Sepuluh interval kepercayaan 90 persen data dengan nilai mean sebenarnya 1" width="65%" />
<p class="caption">
Gambar 8.3: Sepuluh interval kepercayaan 90 persen data dengan nilai mean sebenarnya 1
</p>
</div>
</div>
<div id="interval-kepercayaan-median" class="section level2">
<h2><span class="header-section-number">8.3</span> Interval Kepercayaan Median</h2>
<p>Interval kepercayaan median populasi dapat dihitung tanpa perlu mengikuti asumsi distribusi tertentu. Sehingga nilai median dapat digunakan untuk memperkirakan nilai pusat data untuk distribusi data yang tidak berdistribusi normal.</p>
<div id="interval-estimasi-median-metode-nonparametrik" class="section level3">
<h3><span class="header-section-number">8.3.1</span> Interval Estimasi Median Metode Nonparametrik</h3>
<p>Interval estimasi nonparametrik untuk median populasi sebenarnya dihitung menggunakan distribusi binomial. Pertama, tingkat signifikansi yang diinginkan <span class="math inline">\(\alpha\)</span> dinyatakan, error yang dapat diterima tidak termasuk median yang sebenarnya. Satu-setengah (<span class="math inline">\(\alpha/2\)</span>) dari error ini digunakan untuk setiap akhir interval (Gambar <a href="penaksiran-secara-statistika.html#fig:iemednp">8.4</a>). Tabel distribusi binomial memberikan nilai kritis bawah dan atas <span class="math inline">\(x&#39;\)</span> dan <span class="math inline">\(x\)</span> pada setengah tingkat alfa yang diinginkan (<span class="math inline">\(\alpha/2\)</span>). Nilai-nilai kritis ini ditransformasikan ke dalam rangking <span class="math inline">\(R_l\)</span> dan <span class="math inline">\(R_u\)</span> yang sesuai dengan titik data <span class="math inline">\(C_l\)</span> dan <span class="math inline">\(C_u\)</span> di ujung interval kepercayaan.</p>
<div class="figure" style="text-align: center"><span id="fig:iemednp"></span>
<img src="iemednp.PNG" alt="Probabilitas median populasi P50 pada dua sisi interval estimasi." width="65%" />
<p class="caption">
Gambar 8.4: Probabilitas median populasi P50 pada dua sisi interval estimasi.
</p>
</div>
<p>Untuk ukuran sampel kecil, tabel binomial dimasukkan pada kolom p = 0,5 (median) untuk menghitung interval kepercayaan pada median. Nilai kritis <span class="math inline">\(x&#39;\)</span> diperoleh dari tabel distribusi binomial yang sesuai dengan <span class="math inline">\(\alpha/2\)</span>, atau sedekat mungkin dengan <span class="math inline">\(\alpha/2\)</span>. Nilai kritis ini kemudian digunakan untuk menghitung peringkat <span class="math inline">\(R_u\)</span> dan <span class="math inline">\(R_l\)</span> yang sesuai dengan nilai data pada batas kepercayaan atas dan bawah untuk median. Batas-batas ini adalah titik data peringkat <span class="math inline">\(R_l\)</span>th yang masuk dari setiap ujung daftar n observasi. Interval kepercayaan yang dihasilkan akan mencerminkan bentuk (menceng atau simetris) dari data asli.</p>
<span class="math display" id="eq:rl">\[\begin{equation}
  R_l=x&#39;+1 
  \tag{8.2}
\end{equation}\]</span>
<span class="math display" id="eq:ru">\[\begin{equation}
  R_u=n-x&#39;=x\ untuk\ x&#39;\ dan\ x\ dari\ tabel\ dist.\ binomial 
  \tag{8.3}
\end{equation}\]</span>
<p>Interval nonparametrik tidak selalu dapat secara tepat menghasilkan tingkat kepercayaan yang diinginkan ketika ukuran sampel kecil. Ini karena mereka terpisah, melompat dari satu nilai data ke yang berikutnya di ujung interval. Namun, tingkat kepercayaan yang dekat dengan yang diinginkan tersedia untuk semua kecuali ukuran sampel terkecil.</p>
<p>Untuk lebih memahaminya diberikan data 25 pengukuran konsentrasi arsenin di air tanah dalam ppb yang disajikan pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a>.</p>
<table>
<caption><span id="tab:gwardat">Tabel 8.3: </span>Konsentrasi Arsenik dalam air tanah (ppb)</caption>
<thead>
<tr class="header">
<th align="right">observasi</th>
<th align="right">konsentrasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1.3</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">1.5</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">1.8</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">2.6</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">2.8</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">3.5</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">4.0</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">4.8</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">8.0</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">9.5</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">12.0</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="right">14.0</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="right">19.0</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="right">23.0</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="right">41.0</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="right">80.0</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="right">100.0</td>
</tr>
<tr class="even">
<td align="right">18</td>
<td align="right">110.0</td>
</tr>
<tr class="odd">
<td align="right">19</td>
<td align="right">120.0</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="right">190.0</td>
</tr>
<tr class="odd">
<td align="right">21</td>
<td align="right">240.0</td>
</tr>
<tr class="even">
<td align="right">22</td>
<td align="right">250.0</td>
</tr>
<tr class="odd">
<td align="right">23</td>
<td align="right">300.0</td>
</tr>
<tr class="even">
<td align="right">24</td>
<td align="right">340.0</td>
</tr>
<tr class="odd">
<td align="right">25</td>
<td align="right">580.0</td>
</tr>
</tbody>
</table>
<p>Visualisasi Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a> ditunjukkan pada Gambar <a href="penaksiran-secara-statistika.html#fig:gwardatvis">8.5</a>. Berdasarkan gambar tersebut terlihat bahwa data memiliki kemencengan yang positif sehingga penaksiran rata-rata populasi menggunakan nilai mean tidak dapat dilakukan.</p>
<div class="figure" style="text-align: center"><span id="fig:gwardatvis"></span>
<img src="EnvStat_files/figure-html/gwardatvis-1.png" alt="Distribusi konsentrasi arsenik dalam air tanah" width="70%" />
<p class="caption">
Gambar 8.5: Distribusi konsentrasi arsenik dalam air tanah
</p>
</div>
<p>Berdasarkan data pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a>, median konsentrasi arsenik <span class="math inline">\(\hat{C}_{0.5}\)</span>=19 yang berada pada urutan data ke-13 dari data yang telah diurutkan dari yang terkecil ke yang terbesar. Untuk menentukan interval kepercayaan 95% median kosentrasi arsenik <span class="math inline">\(C_{0.5}\)</span>, nilai kritis berdasarkan nilai error mendekati <span class="math inline">\(\alpha/2\)</span>=0,025 adalah <span class="math inline">\(x&#39;\)</span>=7. Untuk lebih memahaminya pembaca dapat mengunduh tabel distribusi binomial pada laman <a href="https://onlinepubs.trb.org/onlinepubs/nchrp/cd-22/manual/v2appendixc.pdf">berikut</a>. Nilai <span class="math inline">\(x&#39;\)</span>=7 diperoleh menggunakan Tabel distribusi binomial dengan <span class="math inline">\(n\)</span>=25 dan <span class="math inline">\(p\)</span>=0,5 yang ditampilkan pada Gambar <a href="penaksiran-secara-statistika.html#fig:tabbinom">8.6</a> dengan nilai probabilitas sebesar 0,022 (mendekati 0,025) yang setara dengan area yang diarsir pada Gambar <a href="penaksiran-secara-statistika.html#fig:iemednp">8.4</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:tabbinom"></span>
<img src="tabbinom.PNG" alt="Lokasi probabilitas x berdasarkan tabel distribusi binomial" width="65%" />
<p class="caption">
Gambar 8.6: Lokasi probabilitas x berdasarkan tabel distribusi binomial
</p>
</div>
<p>Berdasarkan Persamaan <a href="penaksiran-secara-statistika.html#eq:rl">(8.2)</a> dan Persamaan <a href="penaksiran-secara-statistika.html#eq:ru">(8.3)</a>, rangking <span class="math inline">\(R_l\)</span> pada observasi yang menyatakan batas kepercayaan bawah (<em>lower confidence limit</em>) adalah 8 (<span class="math inline">\(R_i\)</span>=7+1) dan <span class="math inline">\(R_u\)</span> yang menyatakan batas kepercayaan atas (<em>upper confidence level</em>) adalah 25-7=18. Berdasarkan nilai probabilitas <span class="math inline">\(x&#39;\)</span>=0,022, maka nilai alpha yang sesunggunya sebesar <span class="math inline">\(\alpha=2*0,022=0,044\)</span>. Nilai tersebut setara dengan tingkat kepercayaan <span class="math inline">\(1-0,044\)</span> atau 95,6%. Nilai interval kepercayaan median antara observasi ke-8 dan 18 adalah <span class="math inline">\(C_l=4,8\le C_{0.5}\le110=C_u\ \ pada\ \alpha=0,044\)</span>. Nilai asimetrik disekitar <span class="math inline">\(\hat{C}_{0.5}\)</span>=19 mencerminkan kemencengan pada data.</p>
<p>Jika pembaca ingin melakukan perhitungan pada <code>R</code>, pembaca harus membuat fungsi sebagai berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">med_npCI &lt;-<span class="st"> </span><span class="cf">function</span>(x,alpha){
  <span class="co"># mengurutkan data</span>
  x_sort=<span class="kw">sort</span>(x)
  <span class="co"># menghitung jumlah observasi</span>
  n=<span class="kw">length</span>(x)
  <span class="co"># menghitung median data</span>
  med =<span class="st"> </span><span class="kw">median</span>(x)
  <span class="co"># loop untuk mencari nilai probabilitas terdekat</span>
  <span class="co"># dengan alpha</span>
  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>n){
    b =<span class="st"> </span><span class="kw">pbinom</span>(i,n,<span class="fl">0.5</span>)
    <span class="cf">if</span>(b<span class="op">&gt;</span>alpha<span class="op">/</span><span class="dv">2</span>){
      <span class="cf">break</span>
    }
  }
  <span class="co"># mengambil x&#39;</span>
  x_i=i<span class="op">-</span><span class="dv">1</span>
  <span class="co"># menghitung Rl dan Ru</span>
  rl=x_i<span class="op">+</span><span class="dv">1</span>
  ru=n<span class="op">-</span>x_i
  <span class="co"># menghitung true confidence level</span>
  CL=<span class="dv">1</span><span class="op">-</span><span class="dv">2</span><span class="op">*</span>(<span class="kw">pbinom</span>(x_i,n,<span class="fl">0.5</span>))
  <span class="co"># menghitung Lower dan Upper CL</span>
  LCL=x_sort[rl]
  UCL=x_sort[ru]
  <span class="co"># menggabungkannya dalam satu data</span>
  data=<span class="kw">data.frame</span>(<span class="st">&quot;median&quot;</span>=med,
                  <span class="st">&quot;True CL %&quot;</span>=CL<span class="op">*</span><span class="dv">100</span>,
                  <span class="st">&quot;Lower CL&quot;</span>=LCL,
                  <span class="st">&quot;Upper CL&quot;</span>=UCL)
  <span class="kw">return</span>(data)
}</code></pre></div>
<p>Fungsi yang telah dibuat tersebut selanjutnya dapat pembaca gunakan saat akan menghitung interval kepercayaan median populasi menggunakan metode Nonparametrik. Berikut penerapannya menggunakan data pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a> yang telah disimpan kedalam objek <code>gwardat</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">med_npCI</span>(<span class="dt">x=</span>gwardat<span class="op">$</span>konsentrasi, <span class="dt">alpha=</span><span class="fl">0.05</span>)</code></pre></div>
<pre><code>##   median True.CL.. Lower.CL Upper.CL
## 1     19     95.67      4.8      110</code></pre>
<p>Alternatif lain yang dapat digunakan untuk menghitung interval kepercayaan jika sampel cukup besar n&gt;20 menggunakan metode Nonparametrik adalah dengan menggunakan pendekatan tabel distribusi normal untuk memperkirakan distribusi binomial. Dengan menggunakan pendekatan ini, hanya sebagian kecil tabel distribusi binomial (n=20) yang diperlukan untuk melakukannya. Nilai kritis <span class="math inline">\(z_{\alpha/2}\)</span> dari tabel distribusi normal menentukan rangking atas dan bawah observasi yang menyatakan awal dan akhir nilai interval kepercayaan yang dinyatakan pada Persamaan <a href="penaksiran-secara-statistika.html#eq:rlz">(8.4)</a> dan Persamaan <a href="penaksiran-secara-statistika.html#eq:ruz">(8.5)</a>. Pembulatan diperlukan dalam proses ini sebab nilai ranking harus berupa integer.</p>
<span class="math display" id="eq:rlz">\[\begin{equation}
  R_l=\frac{n-z_{\frac{\alpha}{2}}\cdot\sqrt{n}}{2} 
  \tag{8.4}
\end{equation}\]</span>
<span class="math display" id="eq:ruz">\[\begin{equation}
   R_l=\frac{n-z_{\frac{\alpha}{2}}\cdot\sqrt{n}}{2}+1
  \tag{8.5}
\end{equation}\]</span>
<p>Menggunakan contoh data pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a>, dengan 95% interval kepercayaan (<span class="math inline">\(z_{\alpha/2}\)</span>=1,96) median dapat dihitung seperti berikut:</p>
<p><span class="math display">\[
  R_l=\frac{25-1,96\cdot\sqrt{25}}{2}=7,6 
\]</span></p>
<p><span class="math display">\[
  R_l=\frac{25+1,96\cdot\sqrt{25}}{2}+1=18,4 
\]</span></p>
<p>Berdasarkan hasil perhitungan diperoleh rangking bawah adalah data ke-8 dan rangking atas adalah 18. Kedua data dibulatkan berdasarkan integer terdekat. Nilai interval kepercayaan median yang diperoleh sama dengan metode sebelumnya sebab rangking batas bawah dan atasnya yang seragam.</p>
<p>Jika pembaca ingin menggunakan <code>R</code>, maka fungsi yang sebelumya telah kita buat dapat dimodifikasi seperti berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">med_norCI &lt;-<span class="st"> </span><span class="cf">function</span>(x, alpha){
  <span class="co"># mengurutkan data dari yang terkecil</span>
  x_sort=<span class="kw">sort</span>(x)
  <span class="co"># menghitung jumlah observasi</span>
  n =<span class="st"> </span><span class="kw">length</span>(x)
  <span class="co"># menghitung median data</span>
  med =<span class="st"> </span><span class="kw">median</span>(x)
  <span class="co"># menghitung Rl dan Ru</span>
  rl=<span class="kw">round</span>((n<span class="op">-</span><span class="kw">abs</span>(<span class="kw">qnorm</span>(alpha<span class="op">/</span><span class="dv">2</span>))<span class="op">*</span><span class="kw">sqrt</span>(n))<span class="op">/</span><span class="dv">2</span>,<span class="dv">0</span>)
  ru=<span class="kw">round</span>(((n<span class="op">+</span><span class="kw">abs</span>(<span class="kw">qnorm</span>(alpha<span class="op">/</span><span class="dv">2</span>))<span class="op">*</span><span class="kw">sqrt</span>(n))<span class="op">/</span><span class="dv">2</span>)<span class="op">+</span><span class="dv">1</span>,<span class="dv">0</span>)
  <span class="co"># menghitung Lower dan Upper CL</span>
  LCL=x_sort[rl]
  UCL=x_sort[ru]
  <span class="co"># menggabungkannya dalam satu data</span>
  data=<span class="kw">data.frame</span>(<span class="st">&quot;median&quot;</span>=med,
                  <span class="st">&quot;Lower CL&quot;</span>=LCL,
                  <span class="st">&quot;Upper CL&quot;</span>=UCL)
  <span class="kw">return</span>(data)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">med_norCI</span>(<span class="dt">x=</span>gwardat<span class="op">$</span>konsentrasi, <span class="dt">alpha=</span><span class="fl">0.05</span>)</code></pre></div>
<pre><code>##   median Lower.CL Upper.CL
## 1     19      4.8      110</code></pre>
</div>
<div id="metode-parametrik-interval-estimasi-median" class="section level3">
<h3><span class="header-section-number">8.3.2</span> Metode Parametrik Interval Estimasi Median</h3>
<p>Telah dijelaskan pada chapter 6 bahwa rata-rata geometrik merupakan merupakan nilai rata-rata yang digunakan untuk mengestimasi median sampel untuk data yang memiliki kemencengan dengan transformasi yang digunakan agar data simetris adalah transformasi logaritmik <span class="math inline">\(y=\ln(x)\)</span>. Pada metode ini data diasumsikan memiliki distribusi lognormal (kemencengan positif). Rerata dan interval geometris akan lebih efisien (interval lebih pendek) dari median dan interval kepercayaannya ketika data benar-benar lognormal. Median sampel dan intervalnya lebih tepat dan lebih efisien jika logaritma data masih menunjukkan kemencengan dan/atau <em>outlier</em>. Estimasi media menggunakan metode parametrik dituliskan kedalam Persamaan <a href="penaksiran-secara-statistika.html#eq:gmci">(8.6)</a> dan Persamaan <a href="penaksiran-secara-statistika.html#eq:gmci2">(8.7)</a>.</p>
<span class="math display" id="eq:gmci">\[\begin{equation}
  GM_x=\exp\left(\overline{y}\right) 
  \tag{8.6}
\end{equation}\]</span>
<p>dimana <span class="math inline">\(y=\ln(x)\)</span> dan <span class="math inline">\(\overline{y}\)</span>=mean sampel <span class="math inline">\(y\)</span>.</p>
<span class="math display" id="eq:gmci2">\[\begin{equation}
  \exp\left(\overline{y}-t_{\left(\frac{\alpha}{2},n-1\right)}\sqrt{\frac{s_y^2}{n}}\right)\le GM_x\le\exp\left(\overline{y}+t_{\left(\frac{\alpha}{2},n-1\right)}\sqrt{\frac{s_y^2}{n}}\right) 
  \tag{8.7}
\end{equation}\]</span>
<p>dimana <span class="math inline">\(s_{y}^2\)</span>= varians sampel y pada unit log natural.</p>
<p>Pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a>, untuk menghitung interval keyakinan median menggunakan pendekatan mean geometrik <span class="math inline">\(GM_x\)</span> kita perlu mentransformasi datanya terlebih dahulu sehingga menjadi bentuk natural log. hasil transformasi disajikan pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat2">8.4</a>.</p>
<table>
<caption><span id="tab:gwardat2">Tabel 8.4: </span>Tranformasi logaritmik konsentrasi Arsenik dalam air tanah (ppb)</caption>
<thead>
<tr class="header">
<th align="right">observasi</th>
<th align="right">konsentrasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">0.2624</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">0.4055</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">0.5878</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">0.9555</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">1.0296</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">1.2528</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">1.3863</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">1.5686</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">2.0794</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">2.2513</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">2.4849</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="right">2.6391</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="right">2.9444</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="right">3.1355</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="right">3.7136</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="right">4.3820</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="right">4.6052</td>
</tr>
<tr class="even">
<td align="right">18</td>
<td align="right">4.7005</td>
</tr>
<tr class="odd">
<td align="right">19</td>
<td align="right">4.7875</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="right">5.2470</td>
</tr>
<tr class="odd">
<td align="right">21</td>
<td align="right">5.4806</td>
</tr>
<tr class="even">
<td align="right">22</td>
<td align="right">5.5215</td>
</tr>
<tr class="odd">
<td align="right">23</td>
<td align="right">5.7038</td>
</tr>
<tr class="even">
<td align="right">24</td>
<td align="right">5.8289</td>
</tr>
<tr class="odd">
<td align="right">25</td>
<td align="right">6.3630</td>
</tr>
</tbody>
</table>
<p>visualisasi distribusi yang baru disajikan pada Gambar <a href="penaksiran-secara-statistika.html#fig:gwardatvis2">8.7</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:gwardatvis2"></span>
<img src="EnvStat_files/figure-html/gwardatvis2-1.png" alt="Distribusi logaritmik konsentrasi arsenik dalam air tanah" width="70%" />
<p class="caption">
Gambar 8.7: Distribusi logaritmik konsentrasi arsenik dalam air tanah
</p>
</div>
<p>Nilai mean dari data tersebut adalah 3,17 dengan simpangan baku sebesar 1,96. Berdasarkan Gambar <a href="penaksiran-secara-statistika.html#fig:gwardatvis2">8.7</a>, kita telah memperoleh distribusi yang simetris.</p>
<p>Dengan menggunakan Persamaan <a href="penaksiran-secara-statistika.html#eq:gmci">(8.6)</a> dan Persamaan <a href="penaksiran-secara-statistika.html#eq:gmci2">(8.7)</a> selanjutnya dapat dihitung interval kepercayaannya dengan derajat kepercayaan 95%.</p>
<p><span class="math display">\[
  GM_x=\exp\left(3,17\right)=23,8
\]</span></p>
<p><span class="math display">\[
  \exp\left(3.17-2,064\cdot\sqrt{\frac{1.96^2}{25}}\right)\le GM_x\le\exp\left(3.17-2,064\cdot\sqrt{\frac{1.96^2}{25}}\right)
\]</span></p>
<p><span class="math display">\[
  \exp\left(2,36\right)\le GM_x\le\exp\left(3,98\right)
\]</span></p>
<p><span class="math display">\[
  10,6\le GM_x\le53,5
\]</span></p>
<p>Dengan menggunakan <code>R</code> dapat dikerjakan menggunakan fungsi sebagai berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># persamaan hanya dapat digunakan untuk data yang telah ditransformasi lognormal</span>

med_gm &lt;-<span class="st"> </span><span class="cf">function</span>(x, alpha){
  <span class="co"># rata-rata geometrik</span>
  gm =<span class="st"> </span><span class="kw">exp</span>(<span class="kw">mean</span>(x))
  <span class="co"># menghitung derajat kebebasan</span>
  df =<span class="st"> </span><span class="kw">length</span>(x)<span class="op">-</span><span class="dv">1</span>
  <span class="co"># menghitung batas bawah dan atas</span>
  LCL =<span class="st"> </span><span class="kw">exp</span>(<span class="kw">mean</span>(x)<span class="op">-</span><span class="kw">qt</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>,df)<span class="op">*</span><span class="kw">sqrt</span>(<span class="kw">var</span>(x)<span class="op">/</span><span class="kw">length</span>(x)))
  UCL =<span class="st"> </span><span class="kw">exp</span>(<span class="kw">mean</span>(x)<span class="op">+</span><span class="kw">qt</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>,df)<span class="op">*</span><span class="kw">sqrt</span>(<span class="kw">var</span>(x)<span class="op">/</span><span class="kw">length</span>(x)))
  <span class="co"># menggabungkan hasil</span>
  data=<span class="kw">data.frame</span>(<span class="st">&quot;GM&quot;</span>=gm,
                  <span class="st">&quot;Lower CL&quot;</span>=LCL,
                  <span class="st">&quot;Upper CL&quot;</span>=UCL)
  <span class="kw">return</span>(data)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">med_gm</span>(<span class="dt">x=</span>gwardat2<span class="op">$</span>konsentrasi, <span class="dt">alpha=</span><span class="fl">0.05</span>)</code></pre></div>
<pre><code>##      GM Lower.CL Upper.CL
## 1 23.87    10.63     53.6</code></pre>
<p>Pembaca perlu berhati-hati dalam menentukan apakah akan menggunakan metode Nonparametrik atau parametrik. Jika data berditribusi lognormal kita dapat menggunakan metode parametrik.</p>
</div>
</div>
<div id="interval-kepercayaan-mean" class="section level2">
<h2><span class="header-section-number">8.4</span> Interval Kepercayaan Mean</h2>
<p>Estimasi interval juga dapat dihitung untuk mean populasi sebenarnya <span class="math inline">\(\mu\)</span>. Hal ini sangat sesuai jika pusat data menjadi fokus dalam analisa statistik. Interval simetris di sekitar sampel rata-rata X paling sering dihitung. Untuk ukuran sampel besar, interval simetris secara memadai menggambarkan variasi rata-rata, terlepas dari bentuk distribusi data. Ini karena distribusi rata-rata sampel akan mendekati dengan distribusi normal ketika ukuran sampel semakin besar, meskipun data mungkin tidak terdistribusi secara normal. Untuk ukuran sampel yang lebih kecil, rata-rata tidak akan didistribusikan secara normal kecuali jika data itu sendiri terdistribusi secara normal. Ketika data meningkat kemencengannya, lebih banyak data diperlukan sebelum distribusi rata-rata dapat didekati secara memadai oleh distribusi normal. Untuk distribusi yang sangat miring atau data yang mengandung <em>outlier</em>, mungkin diperlukan lebih dari 100 pengamatan sebelum nilai rata-rata tidak akan terpengaruh oleh nilai terbesar untuk mengasumsikan bahwa distribusinya akan simetris.</p>
<div id="interval-kepercayaan-mean-untuk-distribusi-yang-simetris" class="section level3">
<h3><span class="header-section-number">8.4.1</span> Interval Kepercayaan Mean Untuk Distribusi Yang Simetris</h3>
<p>Interval kepercayaan mean untuk distribusi simetris dihitung menggunakan tabel distribusi <em>student’s t</em> yang tersedia dalam buku teks statistik dan perangkat lunak. Tabel ini dimasukkan untuk menemukan nilai kritis untuk t pada setengah tingkat alfa yang diinginkan. Pada buku lain sering dijelaskan bahwa distribusi t hanya digunakan untuk sampel kecil (beberapa menyebutkan n&lt;30), sedangkan untuk distribusi besar digunakan distribusi normal. Penggunaan distribusi normal jarang digunakan dalam prakiraan. Hal ini disebabkan karena pada proses perhitungan diperlukan nilai simpangan baku <span class="math inline">\(\sigma\)</span>. Pada kenyataannya pada pengukuran dilapangan kita sering sekalin melakukan estimasi terhadap simpangan baku melalui sampel <span class="math inline">\(s\)</span> karena kita tidak mengetahui nilai simpangan baku populasinya sehingga pada buku ini akan digali lebih jauh metode estimasi interval menggunakan persamaan distribusi t.</p>
<p>Lebar interval kepercayaan adalah fungsi dari nilai-nilai kritis dari tabel distribusi t, standar deviasi data, dan ukuran sampel. Ketika data memiliki kemecengan atau mengandung <em>outlier</em>, asumsi di balik interval t dan distribusi normal tidak berlaku. Interval simetris yang dihasilkan akan sangat luas sehingga sebagian besar pengamatan akan dimasukkan di dalamnya. Ini juga dapat mencapai di bawah nol di ujung bawah. Titik akhir negatif dari interval kepercayaan untuk data yang tidak dapat menjadi negatif adalah sinyal yang jelas bahwa asumsi interval kepercayaan simetris tidak diperlukan. Untuk data tersebut, dengan asumsi distribusi lognormal seperti yang dijelaskan dalam sub chapter sebelumnya (interval kepercayaan median) akan lebih tepat. Interval kepercayaan dihitung menggunakan Persamaan <a href="penaksiran-secara-statistika.html#eq:pmeancisim">(8.8)</a>.</p>
<span class="math display" id="eq:pmeancisim">\[\begin{equation}
  \overline{x}-t_{\left(\frac{\alpha}{2},n-1\right)}\cdot\sqrt{\frac{s^2}{n}}\le\mu\le\overline{x}+t_{\left(\frac{\alpha}{2},n-1\right)}\cdot\sqrt{\frac{s^2}{n}}
  \tag{8.8}
\end{equation}\]</span>
<p>Untuk lebih memahami cara penerapannya, kita akan menggunakan kembali data pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat2">8.4</a>. Langkah pertama yang perlu dilakukan adalah menghitung mean sampel <span class="math inline">\(\overline{x}\)</span> dan simpangan baku sampel <span class="math inline">\(s\)</span>. Berdasarkan hasil perhitungan diperoleh nilai <span class="math inline">\(\overline{x}\)</span> =98.352 dan <span class="math inline">\(s\)</span> = 144.685. Dengan meggunakan Persamaan <a href="penaksiran-secara-statistika.html#eq:pmeancisim">(8.8)</a>, interval estimasi mean dengan tingkat kepercayaan 95% dapat dihitung sebagai berikut:</p>
<p><span class="math display">\[
  3,17\ -\ t_{\left(0.25,24\right)}\cdot\sqrt{\frac{1,96^2}{25}}\le\mu\le3,17\ -\ t_{\left(0.25,24\right)}\cdot\sqrt{\frac{1,96^2}{25}}
\]</span></p>
<p><span class="math display">\[
  2,36\le\mu\le3,98
\]</span></p>
<p>Berdasarkan hasil yang diperoleh terdapat 95% peluang nilai mean populasi <span class="math inline">\(\mu\)</span> terletak pada interval 2,36 sampai 3,98. Perlu diingat bahwa metode parametrik sangat sensitif dengan adanya <em>outlier</em> sehingga jika pembaca ingin menggunakannya pastikan terlebih dahulu tidak ada <em>outlier</em> pada data dengan cara melakukan visualisasi data.</p>
<p>Pada <code>R</code> kita dapat menggunakan fungsi <code>stat.desc()</code> untuk menhitung statistika deskriptif serta interval kepercayaan mean-nya. Berikut adalah sintaks yang digunakan:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># memuat paket</span>
<span class="kw">library</span>(pastecs)

<span class="co"># ringkasan data</span>
r=<span class="kw">stat.desc</span>(gwardat2<span class="op">$</span>konsentrasi)
r</code></pre></div>
<pre><code>##      nbr.val     nbr.null       nbr.na          min 
##      25.0000       0.0000       0.0000       0.2624 
##          max        range          sum       median 
##       6.3630       6.1007      79.3167       2.9444 
##         mean      SE.mean CI.mean.0.95          var 
##       3.1727       0.3919       0.8089       3.8400 
##      std.dev     coef.var 
##       1.9596       0.6176</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># batas bawah (LCL)</span>
<span class="kw">mean</span>(gwardat2<span class="op">$</span>konsentrasi)<span class="op">-</span>r[[<span class="dv">11</span>]]</code></pre></div>
<pre><code>## [1] 2.364</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># batas atas (UCL)</span>
<span class="kw">mean</span>(gwardat2<span class="op">$</span>konsentrasi)<span class="op">+</span>r[[<span class="dv">11</span>]]</code></pre></div>
<pre><code>## [1] 3.982</code></pre>
</div>
<div id="interval-kepercayaan-mean-untuk-distribusi-yang-asimetris" class="section level3">
<h3><span class="header-section-number">8.4.2</span> Interval Kepercayaan Mean Untuk Distribusi Yang Asimetris</h3>
<p>Mean dan interval kepercayaan dapat dihitung dengan mengasumsikan distribusi data mengikuti distribusi logaritmik <span class="math inline">\(y=\ln{(x)}\)</span>. Metode ini berguna untuk jenis data yang memiliki bentuk distribusi data yang memiliki kemencengan positif (perlu transformasi logaritmik agar simetris).Metode ini memberikan perkiraan rata-rata yang lebih dapat diandalkan (varians lebih rendah) daripada perhitungan rata-rata sampel biasa tanpa transformasi log.</p>
<p>Untuk memperkirakan rata-rata populasi <span class="math inline">\(\mu_x\)</span> dalam unit aslinya, anggap datanya berdistribusi normal. Satu-setengah varians logaritma ditambahkan ke <span class="math inline">\(\overline{y}\)</span> (rata-rata log) sebelum eksponensial. Karena varianss sampel <span class="math inline">\(s^2_y\)</span> hanya perkiraan varianss sebenarnya dari logaritma, estimasi sampel rata-rata akan menjadi bias. Namun, untuk sampel dengan <span class="math inline">\(s^2_y\)</span> kecil dan ukuran sampel besar bias dapat diabaikan. Interval kepercayaan dapat dituliskan berdasarkan Persamaan <a href="penaksiran-secara-statistika.html#eq:pmeanciasim">(8.9)</a>.</p>
<span class="math display" id="eq:pmeanciasim">\[\begin{equation}
  \mu_x=\exp\left(\overline{y}+0,5\cdot s_y^2\right)
  \tag{8.9}
\end{equation}\]</span>
<p>dimana <span class="math inline">\(y=\ln{(x)}\)</span>, <span class="math inline">\(\overline{y}\)</span>= mean sampel dan <span class="math inline">\(s^2_y\)</span>= varians sampel y dalam unit log natural.</p>
<p>Interval kepercayaan sekitar <span class="math inline">\(\mu_x\)</span> bukan estimasi interval yang dihitung untuk rata-rata geometri dalam Persamaan <a href="penaksiran-secara-statistika.html#eq:gmci2">(8.7)</a>. Interval kepercayaan tidak dapat dihitung hanya dengan mengekspansi interval sekitar <span class="math inline">\(\overline{y}\)</span>. Interval kepercayaan yang tepat dalam satuan asli untuk rata-rata data lognormal dapat dihitung. Untuk lebih jelasnya pembaca dapat melihatnya pada situs <a href="http://jse.amstat.org/v13n1/olsson.html" class="uri">http://jse.amstat.org/v13n1/olsson.html</a>.</p>
<p>Metode Cox dapat digunakan untuk menghitung interval keyakinan dengan nilai estimasi rata-rata menggunakan Persamaan <a href="penaksiran-secara-statistika.html#eq:pmeanciasim">(8.9)</a>. Persamaan yang digunakan dapat dituliskan sebagai berikut (Persamaan <a href="penaksiran-secara-statistika.html#eq:pmeanciasimci">(8.10)</a>).</p>
<span class="math display" id="eq:pmeanciasimci">\[\begin{equation}
  \ln\left(\mu_x\right)=\overline{Y}+\frac{s_y^2}{2}\pm z_{\left(\frac{\alpha}{2}\right)}\sqrt{\frac{s_y^2}{n}+\frac{s_y^4}{2\left(n-1\right)}}
  \tag{8.10}
\end{equation}\]</span>
<p>Persamaan <a href="penaksiran-secara-statistika.html#eq:pmeanciasimci">(8.10)</a> dapat dimodifikasi dengan menggunakan distribusi t dibanding menggunakan distribusi normal. Penggunaan distribusi t akan memperbaiki kelemahan penggunaan distribusi normal pada sampel yang berukuran kecil.</p>
<p>Data Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a> dapat kita gunakan untuk menghitung rata-rata menggunakan Persamaan <a href="penaksiran-secara-statistika.html#eq:pmeanciasimci">(8.10)</a>. Hal ini disebabkan karena data yang ada memiliki kemencengan positif sehingga dapat dianggap bahwa transformasi logaritmik dapat membentuk distribusi ini menjadi lebih simetris.</p>
<p>Berdasarkan hasil perhitungan diperoleh nilai <span class="math inline">\(\overline{Y}\)</span> =3.173 dan <span class="math inline">\(s^2_y\)</span> = 1.96. Sehingga nilai interval selanjutnya dapat dihitung menggunakan Persamaan <a href="penaksiran-secara-statistika.html#eq:pmeanciasimci">(8.10)</a> dengan interval keyakinan 95%.</p>
<p><span class="math display">\[
  \ln\left(\mu_x\right)=3,17+\frac{1,96^2}{2}\pm1,96\sqrt{\frac{1,96^2}{25}+\frac{1,96^4}{2\left(25-1\right)}}
\]</span></p>
<p><span class="math display">\[
  \ln\left(\mu_x\right)=5,10\pm1,33
\]</span></p>
<p>Sehingga</p>
<p><span class="math display">\[
  \exp\left(5,10-1,33\right)\le\mu_x\le\exp\left(5,10+1,33\right)
\]</span></p>
<p><span class="math display">\[
  43,38\le\mu_x\le620,17
\]</span></p>
<p>Nilai interval yang dihasilkan sangat panjang sehingga nilai rata-rata yang dihasilkan tidak dapat diandalkan untuk memperkirankan lokasi nilai mean populasi.</p>
<p>Pada contoh berikut akan disajikan sintaks untuk menghitung interval kepercayaan mean data pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a> berdasarkan Persamaan <a href="penaksiran-secara-statistika.html#eq:pmeanciasimci">(8.10)</a> dan sitribusi yang digunakan adalah distribusi t. Pembaca dapat memodifikasi sintaks berikut jika ingin menggunakan distribusi normal.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mean_asci&lt;-<span class="cf">function</span>(x,alpha){
  m=<span class="kw">mean</span>(x)
  <span class="co"># mean data hasil transformasi logaritmik</span>
  ave =<span class="st"> </span><span class="kw">mean</span>(<span class="kw">log</span>(x))
  <span class="co"># simpangan baku data hasil transformasi</span>
  sd =<span class="st"> </span><span class="kw">sd</span>(<span class="kw">log</span>(x))
  <span class="co"># jumlah observasi</span>
  n =<span class="st"> </span><span class="kw">length</span>(x)
  <span class="co"># derajat kebebasa</span>
  df =<span class="st"> </span>n<span class="op">-</span><span class="dv">1</span>
  <span class="co"># interval keyakinan satu sisi</span>
  re =<span class="st"> </span><span class="dv">1</span><span class="op">-</span>(alpha<span class="op">/</span><span class="dv">2</span>)
  <span class="co"># CI menggunakan distribusi t</span>
  LCL =<span class="st"> </span><span class="kw">exp</span>(ave<span class="op">+</span>(<span class="fl">0.5</span><span class="op">*</span>sd<span class="op">^</span><span class="dv">2</span>)<span class="op">-</span><span class="kw">qt</span>(re,df)<span class="op">*</span><span class="kw">sqrt</span>(((sd<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span>n)<span class="op">+</span>((sd<span class="op">^</span><span class="dv">4</span>)<span class="op">/</span>(<span class="dv">2</span><span class="op">*</span>df))))
  UCL =<span class="st"> </span><span class="kw">exp</span>(ave<span class="op">+</span>(<span class="fl">0.5</span><span class="op">*</span>sd<span class="op">^</span><span class="dv">2</span>)<span class="op">+</span><span class="kw">qt</span>(re,df)<span class="op">*</span><span class="kw">sqrt</span>(((sd<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span>n)<span class="op">+</span>((sd<span class="op">^</span><span class="dv">4</span>)<span class="op">/</span>(<span class="dv">2</span><span class="op">*</span>df))))
  <span class="co"># menggabungkan hasil</span>
  data =<span class="st"> </span><span class="kw">data.frame</span>(<span class="st">&quot;Mean&quot;</span>=m,
                  <span class="st">&quot;Lower CL&quot;</span>=LCL,
                  <span class="st">&quot;Upper CL&quot;</span>=UCL)
  <span class="kw">return</span>(data)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean_asci</span>(<span class="dt">x=</span>gwardat<span class="op">$</span>konsentrasi, <span class="dt">alpha=</span><span class="fl">0.05</span>)</code></pre></div>
<pre><code>##    Mean Lower.CL Upper.CL
## 1 98.35    40.11    660.9</code></pre>
</div>
</div>
<div id="interval-prediksi-nonparametrik" class="section level2">
<h2><span class="header-section-number">8.5</span> Interval Prediksi Nonparametrik</h2>
<p>Pertanyaan yang sering diajukan adalah apakah satu pengamatan baru kemungkinan berasal dari distribusi yang sama dengan data yang dikumpulkan sebelumnya, atau sebagai alternatif dari distribusi yang berbeda. Pertanyaan dapat dievaluasi dengan menentukan apakah pengamatan baru di luar interval prediksi yang dihitung dari data yang ada. Interval prediksi mengandung <span class="math inline">\(100\cdot\left(1-\alpha\right)\)</span> persen dari distribusi data, sementara <span class="math inline">\(100\cdot\alpha\)</span> persen berada di luar interval. Jika pengamatan baru datang dari distribusi yang sama dengan data yang diukur sebelumnya, ada kemungkinan <span class="math inline">\(100\cdot\alpha\)</span> persen bahwa pengamatan baru tersebut akan berada di luar interval prediksi. Karena pengamatan baru tersebut berada di luar interval tidak “membuktikan” pengamatan baru itu berbeda, hanya saja sepertinya begitu. Seberapa besar kemungkinan ini tergantung pada pilihan <span class="math inline">\(\alpha\)</span> yang ditentukan oleh peneliti.</p>
<p>Interval prediksi dihitung dengan tujuan yang berbeda dari interval kepercayaan. Interval prediksi terkait dengan nilai data individu yang berlawanan dengan ringkasan statistik seperti nilai mean. Interval prediksi lebih luas daripada interval kepercayaan, karena pengamatan individu lebih bervariasi daripada ringkasan statistik yang dihitung dari beberapa pengamatan. Tidak seperti interval kepercayaan, interval prediksi memperhitungkan variabilitas titik data tunggal di sekitar median atau rata-rata, di samping kesalahan dalam memperkirakan pusat distribusi. Ketika mean <span class="math inline">\(\pm\)</span> 2 standar deviasi secara keliru digunakan untuk memperkirakan lebar interval prediksi, data baru dinyatakan berasal dari populasi yang berbeda lebih sering daripada yang seharusnya.</p>
<div id="interval-prediksi-nonparametrik-dua-sisi" class="section level3">
<h3><span class="header-section-number">8.5.1</span> Interval Prediksi Nonparametrik Dua Sisi</h3>
<p>Interval prediksi tingkat kepercayaan nonparametrik <span class="math inline">\(\alpha\)</span> secara sederhana dinyatakan sebagai interval antara persentil distribusi <span class="math inline">\(\alpha/2\)</span> dan <span class="math inline">\(1-\left(\frac{\alpha}{2}\right)\)</span> (Gambar <a href="penaksiran-secara-statistika.html#fig:ipnds">8.8</a>). Interval ini mengandung <span class="math inline">\(100\cdot\left(1-\alpha\right)\)</span> data, sedangkan <span class="math inline">\(100\cdot\alpha\)</span> persen berada di luar interval. Oleh karena itu jika titik data tambahan baru berasal dari distribusi yang sama dengan data yang diukur sebelumnya, ada kemungkinan <span class="math inline">\(100\cdot\alpha\)</span> persen bahwa itu akan berada di luar interval prediksi. Interval akan mencerminkan bentuk data yang dikembangkannya, dan tidak ada asumsi tentang bentuk bentuk yang perlu dibuat. Interval prediksi nonparametrik dua sisi dinyatakan berdasarkan Persamaan <a href="penaksiran-secara-statistika.html#eq:eqipnds">(8.11)</a>.</p>
<span class="math display" id="eq:eqipnds">\[\begin{equation}
  PI_{np}=X_{\frac{\alpha}{2}\cdot\left(n+1\right)}\ sampai\ dengan\ X_{\left[1-\left(\frac{\alpha}{2}\right)\right]\cdot\left(n+1\right)}
  \tag{8.11}
\end{equation}\]</span>
<div class="figure" style="text-align: center"><span id="fig:ipnds"></span>
<img src="ipnds.PNG" alt="Prediksi interval dua sisi" width="65%" />
<p class="caption">
Gambar 8.8: Prediksi interval dua sisi
</p>
</div>
<p>Kita akan kembali menggunakan data pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a>. Dengan menggunakan tingkat kepercayaan 90% kita diminta untuk menentukan interval prediksi dari konsentrasi arsenik pada data tersebut tanpa mengasumsikan distribusi dari data.</p>
<p>Untuk melakukannya kita perlu menentukan observasi ke-2,5 dan 97,5 (berdasarkan nilai <span class="math inline">\(\alpha/2\)</span>) dengan rangking observasi berdasarkan Persamaan <a href="penaksiran-secara-statistika.html#eq:eqipnds">(8.11)</a> adalah <span class="math inline">\((0,05*26)\)</span> atau rangking observasi antara observasi 1 (<span class="math inline">\(R_1\)</span>) dan 2 (<span class="math inline">\(R_2\)</span>) dan <span class="math inline">\((0,95*26)\)</span> rangking observasi antara observasi 24 (<span class="math inline">\(R_{24}\)</span>) dan 25 (<span class="math inline">\(R_{25}\)</span>). Dengan menggunakan interpolasi linier pada observasi ke-1, 2 , 24 dan 25, interval prediksi yang diperoleh adalah sebagai berikut:</p>
<p><span class="math display">\[
  X_1+\left(\frac{R_{\left(0.05\cdot26\right)}-R_1}{R_2-R_1}\right)\cdot\left(X_2-X_1\right)\ sampai\ dengan\ X_{24}+\left(\frac{R_{\left(0.95\cdot26\right)}-R_{24}}{R_{25}-R_{24}}\right)\cdot\left(X_{25}-X_4\right)
\]</span></p>
<p><span class="math display">\[
  1,3+\left(\frac{1,3-1}{2-1}\right)\cdot\left(1,5-1,3\right)\ sampai\ dengan\ 340+\left(\frac{24,5-24}{25-24}\right)\cdot\left(580-340\right)
\]</span></p>
<p><span class="math display">\[
  1,4\ sampai\ dengan\ 508\ ppb
\]</span></p>
<p>Observasi baru diluar rentang tersebut akan dianggap berasal dari distribusi yang berbeda dengan tingkat error sebesar 10% (<span class="math inline">\(\alpha\)</span>=10%).</p>
<p>Dengan menggunakan <code>R</code> pembaca depat menghitung interval prediksi menggunakan fungsi berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">PInp &lt;-<span class="st"> </span><span class="cf">function</span>(x, alpha){
  <span class="co"># mengurutkan data</span>
  x_sort =<span class="st"> </span><span class="kw">sort</span>(x)
  <span class="co"># jumlah observasi</span>
  n =<span class="st"> </span><span class="kw">length</span>(x)
  <span class="co"># menghitung alpha masing-masing sisi</span>
  err &lt;-<span class="st"> </span>alpha<span class="op">/</span><span class="dv">2</span>
  <span class="co"># menentukan rangkin observasi sesuai alpha</span>
  rl =<span class="st"> </span>err<span class="op">*</span>(n<span class="op">+</span><span class="dv">1</span>)
  ru =<span class="st"> </span>(<span class="dv">1</span><span class="op">-</span>err)<span class="op">*</span>(n<span class="op">+</span><span class="dv">1</span>)
  <span class="co"># menentukan observasi untuk interpolasi linier</span>
  rl_<span class="dv">1</span>=<span class="st"> </span><span class="kw">ceiling</span>(rl) <span class="co"># bulatkan ke bawah</span>
  rl_<span class="dv">2</span>=<span class="st"> </span><span class="kw">floor</span>(rl) <span class="co"># bulatkan ke atas</span>
  ru_<span class="dv">1</span>=<span class="st"> </span><span class="kw">ceiling</span>(ru) 
  ru_<span class="dv">2</span>=<span class="st"> </span><span class="kw">floor</span>(ru)
  <span class="co"># menentukan interval prediksi</span>
  LPI =<span class="st"> </span><span class="kw">round</span>(x_sort[rl_<span class="dv">1</span>]<span class="op">+</span>((rl<span class="op">-</span>rl_<span class="dv">1</span>)<span class="op">/</span>(rl_<span class="dv">2</span><span class="op">-</span>rl_<span class="dv">1</span>))<span class="op">*</span>(x_sort[rl_<span class="dv">2</span>]<span class="op">-</span>x_sort[rl_<span class="dv">1</span>]),<span class="dv">1</span>)
  UPI =<span class="st"> </span><span class="kw">round</span>(x_sort[ru_<span class="dv">1</span>]<span class="op">+</span>((ru<span class="op">-</span>ru_<span class="dv">1</span>)<span class="op">/</span>(ru_<span class="dv">2</span><span class="op">-</span>ru_<span class="dv">1</span>))<span class="op">*</span>(x_sort[ru_<span class="dv">2</span>]<span class="op">-</span>x[ru_<span class="dv">1</span>]),<span class="dv">1</span>)
  <span class="co"># menggabungkan hasil</span>
  data =<span class="st"> </span><span class="kw">data.frame</span>(<span class="st">&quot;Lower PI&quot;</span>=LPI,
                    <span class="st">&quot;Upper PI&quot;</span>=UPI)
  <span class="kw">return</span>(data)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">PInp</span>(<span class="dt">x=</span>gwardat<span class="op">$</span>konsentrasi, <span class="dt">alpha=</span><span class="fl">0.1</span>)</code></pre></div>
<pre><code>##   Lower.PI Upper.PI
## 1      1.4      508</code></pre>
</div>
<div id="interval-prediksi-nonparametrik-satu-sisi" class="section level3">
<h3><span class="header-section-number">8.5.2</span> Interval Prediksi Nonparametrik Satu Sisi</h3>
<p>Interval prediksi satu sisi digunakan jika kita ingin mengecek apakah pengamatan baru lebih besar dari data yang ada, atau lebih kecil dari data yang ada, tetapi tidak keduanya. Keputusan untuk menggunakan interval satu sisi harus didasarkan sepenuhnya pada pertanyaan yang menarik. Seharusnya tidak ditentukan setelah melihat data dan memutuskan bahwa pengamatan baru cenderung hanya lebih besar, atau hanya lebih kecil, daripada informasi yang ada. Interval satu sisi menggunakan <span class="math inline">\(\alpha\)</span> dibanding <span class="math inline">\(\alpha/2\)</span> sebagai nilai error, menempatkan semua error di satu sisi interval (Gambar <a href="penaksiran-secara-statistika.html#fig:ipss">8.9</a>). Interval prediksi dituliskan berdasarkan Persamaan <a href="penaksiran-secara-statistika.html#eq:eqipss">(8.12)</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:ipss"></span>
<img src="ipss.PNG" alt="Prediksi interval satu sisi" width="65%" />
<p class="caption">
Gambar 8.9: Prediksi interval satu sisi
</p>
</div>
<span class="math display" id="eq:eqipss">\[\begin{equation}
  PI_{np}:\ x_{baru}&lt;X_{\alpha\cdot\left(n+1\right)}\ atau\ x_{baru}&gt;X_{\left[1-\alpha\right]\cdot\left(n+1\right)}
  \tag{8.12}
\end{equation}\]</span>
<p>Untuk memahami penerapannya, misalkan kita memiliki nilai arsenik baru dengan konsentrasi 355 ppb. Kita perlu menentukan apakah nilai tersebut lebih besar dari sebagian besar data yang ada.</p>
<p>Dengan menggunakan Persamaan <a href="penaksiran-secara-statistika.html#eq:eqipss">(8.12)</a> dan <span class="math inline">\(\alpha\)</span>=0,1 atau tingkat kepercayaan 90%, interval prediksi satu sisi atau data teratas dari persentil ke-90 dari data yang ada adalah <span class="math inline">\(X_{0,9}*26=X_{23,4}\)</span>. Dengan menggunakan interpolasi linier pada observasi data dengan rangking ke-23 (<span class="math inline">\(R_{23}\)</span>) dan 24 (<span class="math inline">\(R_{23}\)</span>) diperoleh:</p>
<p><span class="math display">\[
  X_{23}+0,4\cdot\left(X_{24}-X_{23}\right)=300+0,4\cdot40=316\ ppb
\]</span></p>
<p>Berdasarkan data yang diperoleh diketahui bahwa batas atas dari interval prediksi adalah 316&lt;355 pbb, sehingga disimpulkan bahwa konsentrasi 355 pbb lebih besar dari sebagian besar data yang ada.</p>
<p>Dengan menggunakan <code>R</code> interval prediksi menggunakan satu sisi dapat dihitung menggunakan fungsi berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">PInp_os &lt;-<span class="st"> </span><span class="cf">function</span>(x, obs, alpha, side){
  <span class="co"># mengurutkan data dari yang terkecil</span>
  x_sort =<span class="st"> </span><span class="kw">sort</span>(x)
  <span class="co"># jumlah observasi</span>
  n =<span class="st"> </span><span class="kw">length</span>(x)
  <span class="co"># rangking observasi</span>
  ru =<span class="st"> </span>(<span class="dv">1</span><span class="op">-</span>alpha)<span class="op">*</span>(n<span class="op">+</span><span class="dv">1</span>)
  ru_<span class="dv">1</span> =<span class="st"> </span><span class="kw">ceiling</span>(ru)
  ru_<span class="dv">2</span> =<span class="st"> </span><span class="kw">floor</span>(ru)
  rl =<span class="st"> </span>alpha<span class="op">*</span>(n<span class="op">+</span><span class="dv">1</span>)
  rl_<span class="dv">1</span> =<span class="st"> </span><span class="kw">ceiling</span>(rl)
  rl_<span class="dv">2</span> =<span class="st"> </span><span class="kw">floor</span>(rl)
  <span class="co"># perhitungan interval atas dan bawah</span>
  PIup =<span class="st"> </span>x_sort[ru_<span class="dv">1</span>]<span class="op">+</span>((ru<span class="op">-</span>ru_<span class="dv">1</span>)<span class="op">/</span>(ru_<span class="dv">2</span><span class="op">-</span>ru_<span class="dv">1</span>))<span class="op">*</span>(x_sort[ru_<span class="dv">2</span>]<span class="op">-</span>x_sort[ru_<span class="dv">1</span>])
  PIdown =<span class="st"> </span>x_sort[rl_<span class="dv">1</span>]<span class="op">+</span>((rl<span class="op">-</span>rl_<span class="dv">1</span>)<span class="op">/</span>(rl_<span class="dv">2</span><span class="op">-</span>rl_<span class="dv">1</span>))<span class="op">*</span>(x_sort[rl_<span class="dv">2</span>]<span class="op">-</span>x_sort[rl_<span class="dv">1</span>])
  <span class="co"># decision making</span>
  <span class="cf">if</span>((side<span class="op">==</span><span class="st">&quot;upper&quot;</span>) <span class="op">&amp;</span><span class="st"> </span>(PIup<span class="op">&lt;</span>obs)){
    <span class="kw">cat</span>(<span class="st">&quot;PI =&quot;</span>,PIup,<span class="st">&quot;,observasi baru=&quot;</span>,obs)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">----------------------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi lebih besar dibandingkan sebagian besar nilai yang ada&quot;</span>)
  } <span class="cf">else</span> <span class="cf">if</span>((side<span class="op">==</span><span class="st">&quot;lower&quot;</span>) <span class="op">&amp;</span><span class="st"> </span>(PIdown<span class="op">&gt;</span>obs)){
    <span class="kw">cat</span>(<span class="st">&quot;PI =&quot;</span>,PIdown, <span class="st">&quot;,observasi baru=&quot;</span>,obs)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">----------------------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi lebih kecil dibandingkan sebagian besar nilai yang ada&quot;</span>)
  } <span class="cf">else</span> <span class="cf">if</span>(side<span class="op">==</span><span class="st">&quot;&quot;</span>){
    <span class="kw">print</span>(<span class="st">&quot;side belum ditentukan tentukan apakah lower atau upper&quot;</span>)
  } <span class="cf">else</span>{
    <span class="kw">cat</span>(<span class="st">&quot;batas bawah =&quot;</span>,PIdown,<span class="st">&quot;, batas atas =&quot;</span>,PIup)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">---------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi sama dengan sebagian besar nilai yang ada&quot;</span>)
  }
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">PInp_os</span>(<span class="dt">x=</span>gwardat<span class="op">$</span>konsentrasi, <span class="dt">obs=</span><span class="dv">355</span>, <span class="dt">alpha=</span><span class="fl">0.1</span>, <span class="dt">side=</span><span class="st">&quot;upper&quot;</span>)</code></pre></div>
<pre><code>## PI = 316 ,observasi baru= 355
## ----------------------------------------------------------------------
## Kesimpulan:
## nilai observasi lebih besar dibandingkan sebagian besar nilai yang ada</code></pre>
</div>
</div>
<div id="interval-prediksi-parametrik" class="section level2">
<h2><span class="header-section-number">8.6</span> Interval Prediksi Parametrik</h2>
<p>Interval prediksi parametrik juga digunakan untuk menentukan apakah pengamatan baru kemungkinan berasal dari distribusi yang berbeda dari data yang dikumpulkan sebelumnya. Namun, pada metode parametrik asumsi bentuk dari distribusi data akan diperhitungkan. Asumsi ini memberikan lebih banyak informasi untuk membangun interval, asalkan asumsi tersebut valid. Jika data tidak mengikuti distribusi yang diasumsikan, interval prediksi mungkin tidak akurat.</p>
<div id="interval-prediksi-distribusi-simetris" class="section level3">
<h3><span class="header-section-number">8.6.1</span> Interval Prediksi Distribusi Simetris</h3>
<p>Asumsi yang digunakan untuk melakukan perhitungan interval prediksi untuk distribusi data yang simetris adalah data haruslah berdistribusi normal. Interval prediksi selanjutnya dibentuk secara simetris pada kedua sisi nilai mean. Interval ini lebih lebar rentangnya dibandingkan dengan interval kepercayaan nilai mean. Persamaan matematis yang digunakan untuk menghitungnya dituliskan pada Persamaan <a href="penaksiran-secara-statistika.html#eq:ipds">(8.13)</a>.</p>
<span class="math display" id="eq:ipds">\[\begin{equation}
  PI=\overline{X}-t_{\left(\frac{\alpha}{2},n-1\right)}\cdot\sqrt{s^2+\left(\frac{s^2}{n}\right)}sampai\ \overline{X}+t_{\left(\frac{\alpha}{2},n-1\right)}\cdot\sqrt{s^2+\left(\frac{s^2}{n}\right)}
  \tag{8.13}
\end{equation}\]</span>
<p>Untuk interval satu sisi Persamaan <a href="penaksiran-secara-statistika.html#eq:ipds">(8.13)</a>, menjadi Persamaan <a href="penaksiran-secara-statistika.html#eq:ipds2">(8.14)</a>.</p>
<span class="math display" id="eq:ipds2">\[\begin{equation}
  PI=\overline{X}-t_{\left(\alpha,n-1\right)}\cdot\sqrt{s^2+\left(\frac{s^2}{n}\right)}sampai\ \overline{X}+t_{\left(\alpha,n-1\right)}\cdot\sqrt{s^2+\left(\frac{s^2}{n}\right)}
  \tag{8.14}
\end{equation}\]</span>
<p>Untuk lebih memahaminya misalkan terdapat hasil pengukuran baru konsentrasi arsenik sebesar 350 ppb dengan menggunakan data pada Tabel <a href="penaksiran-secara-statistika.html#tab:gwardat">8.3</a> sebagai pembanding. Buktikan bahwa observasi baru tersebut berasal dari distrubusi yang sama dengan <span class="math inline">\(\alpha\)</span>=5%.</p>
<p>Dengan menggunakan Persamaan <a href="penaksiran-secara-statistika.html#eq:ipds">(8.13)</a>, interval prediksi dapat dihitung sebagai berikut:</p>
<p><span class="math display">\[
PI\ =\ 98,4-t_{\left(0.025,24\right)}\cdot\sqrt{144,7^2+\frac{144,7^2}{25}\ }sampai\ \ 98,4+t_{\left(0.025,24\right)}\cdot\sqrt{144,7^2+\frac{144,7^2}{25}}
\]</span></p>
<p><span class="math display">\[
PI\ =\ 98,4-2,064\cdot147,6\ \ sampai\ \ 98,4+2,064\cdot147,6
\]</span></p>
<p><span class="math display">\[
PI\ =\ -206,25\ \ sampai\ \ 403,05
\]</span></p>
<p>Berdasarkan hasil perhitungan yang dilakukan terlihat bahwa limit interval prediksi yang dihasilkanterdapat nilai negatif. Kosentrasi negatif mengindikasikan bahwa data yang digunakan tidaklah simetris sehingga penggunaan interval prediksi untuk data yang simetris tidak dapat digunakan pada data tersebut. Metode perhitungan interval prediksi untuk data asimetris lebih cocok untuk digunakan.</p>
<p>Pada <code>R</code> interval prediksi disekitar nilai mean dapat dihitung menggunakan fungsi berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">PI_sim &lt;-<span class="st"> </span><span class="cf">function</span>(x, obs, alpha, side){
  <span class="co"># menghitung nilai mean</span>
  ave =<span class="st"> </span><span class="kw">mean</span>(x)
  <span class="co"># menghitung nilai varians dara</span>
  var =<span class="st"> </span><span class="kw">var</span>(x)
  <span class="co"># menghitung df</span>
  n =<span class="st"> </span><span class="kw">length</span>(x)
  df =<span class="st"> </span>n<span class="op">-</span><span class="dv">1</span>
  <span class="co"># perhitungan rentang satu sisi</span>
  pi_l1 =<span class="st"> </span>ave<span class="op">-</span><span class="kw">qt</span>((<span class="dv">1</span><span class="op">-</span>alpha), df)<span class="op">*</span><span class="kw">sqrt</span>(var<span class="op">+</span>(var<span class="op">/</span>n))
  pi_u1 =<span class="st"> </span>ave<span class="op">+</span><span class="kw">qt</span>((<span class="dv">1</span><span class="op">-</span>alpha), df)<span class="op">*</span><span class="kw">sqrt</span>(var<span class="op">+</span>(var<span class="op">/</span>n))
  <span class="co"># perhitungan rentang dua sisi</span>
  pi_l2 =<span class="st"> </span>ave<span class="op">-</span><span class="kw">qt</span>((<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>), df)<span class="op">*</span><span class="kw">sqrt</span>(var<span class="op">+</span>(var<span class="op">/</span>n))
  pi_u2 =<span class="st"> </span>ave<span class="op">+</span><span class="kw">qt</span>((<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>), df)<span class="op">*</span><span class="kw">sqrt</span>(var<span class="op">+</span>(var<span class="op">/</span>n))
  <span class="co"># decision making</span>
  <span class="cf">if</span>(side<span class="op">==</span><span class="st">&quot;Upper&quot;</span> <span class="op">&amp;</span><span class="st"> </span>obs<span class="op">&gt;</span>pi_u1){
    <span class="kw">cat</span>(<span class="st">&quot;PI Atas =&quot;</span>,pi_u1,<span class="st">&quot;,observasi baru=&quot;</span>,obs)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">----------------------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi lebih besar dibandingkan sebagian besar nilai yang ada&quot;</span>)
  }<span class="cf">else</span> <span class="cf">if</span>(side<span class="op">==</span><span class="st">&quot;Lower&quot;</span> <span class="op">&amp;</span><span class="st"> </span>obs<span class="op">&lt;</span>pi_l1){
    <span class="kw">cat</span>(<span class="st">&quot;PI Bawah =&quot;</span>,pi_l1,<span class="st">&quot;,observasi baru=&quot;</span>,obs)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">----------------------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi lebih kecil dibandingkan sebagian besar nilai yang ada&quot;</span>)
  }<span class="cf">else</span> <span class="cf">if</span>(side<span class="op">==</span><span class="dv">2</span> <span class="op">&amp;</span><span class="st"> </span>obs<span class="op">&gt;</span>pi_u2){
    <span class="kw">cat</span>(<span class="st">&quot;PI Bawah =&quot;</span>,pi_l2,<span class="st">&quot;,observasi baru=&quot;</span>,obs, <span class="st">&quot;,PI Atas =&quot;</span>,pi_u2)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">----------------------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi lebih besar dibandingkan sebagian besar nilai yang ada&quot;</span>)
  }<span class="cf">else</span> <span class="cf">if</span>(side<span class="op">==</span><span class="dv">2</span> <span class="op">&amp;</span><span class="st"> </span>obs<span class="op">&lt;</span>pi_l2){
    <span class="kw">cat</span>(<span class="st">&quot;PI Bawah =&quot;</span>,pi_l2,<span class="st">&quot;,observasi baru=&quot;</span>,obs, <span class="st">&quot;,PI Atas =&quot;</span>,pi_u2)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">----------------------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi lebih kecil dibandingkan sebagian besar nilai yang ada&quot;</span>)
  }<span class="cf">else</span> <span class="cf">if</span>(side<span class="op">==</span><span class="st">&quot;Upper&quot;</span> <span class="op">&amp;</span><span class="st"> </span>obs<span class="op">&lt;</span>pi_u1){
    <span class="kw">cat</span>(<span class="st">&quot;PI Atas =&quot;</span>,pi_u1,<span class="st">&quot;,observasi baru=&quot;</span>,obs)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">----------------------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi sama dengan sebagian besar nilai yang ada&quot;</span>)
  }<span class="cf">else</span> <span class="cf">if</span>(side<span class="op">==</span><span class="st">&quot;Lower&quot;</span> <span class="op">&amp;</span><span class="st"> </span>obs<span class="op">&gt;</span>pi_l1){
    <span class="kw">cat</span>(<span class="st">&quot;PI Bawah =&quot;</span>,pi_l1,<span class="st">&quot;,observasi baru=&quot;</span>,obs)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">----------------------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi sama dengan sebagian besar nilai yang ada&quot;</span>)
  }<span class="cf">else</span>{
    <span class="kw">cat</span>(<span class="st">&quot;PI Bawah =&quot;</span>,pi_l2, <span class="st">&quot;,observasi baru=&quot;</span>,obs,<span class="st">&quot;,PI Atas =&quot;</span>,pi_u2)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">---------------------------------------------------------&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Kesimpulan:&quot;</span>)
    <span class="kw">cat</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">nilai observasi sama dengan sebagian besar nilai yang ada&quot;</span>)
  }
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># interval prediksi satu sisi</span>
<span class="kw">PI_sim</span>(<span class="dt">x =</span> gwardat<span class="op">$</span>konsentrasi, <span class="dt">obs =</span> <span class="dv">350</span>, <span class="dt">alpha=</span><span class="fl">0.05</span>, <span class="dt">side=</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## PI Bawah = -206.2 ,observasi baru= 350 ,PI Atas = 402.9
## ---------------------------------------------------------
## Kesimpulan:
## nilai observasi sama dengan sebagian besar nilai yang ada</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ekplorasi-data-menggunakan-grafik.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["EnvStat.pdf", "EnvStat.epub"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
