<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Ringkasan Numerik | Statistika Lingkungan Menggunakan R</title>
  <meta name="description" content="Buku yang membahas penerapan R pada komputasi statistik di bidang Teknik Lingkungan" />
  <meta name="generator" content="bookdown 0.10 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Ringkasan Numerik | Statistika Lingkungan Menggunakan R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="cover.png" />
  <meta property="og:description" content="Buku yang membahas penerapan R pada komputasi statistik di bidang Teknik Lingkungan" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Ringkasan Numerik | Statistika Lingkungan Menggunakan R" />
  
  <meta name="twitter:description" content="Buku yang membahas penerapan R pada komputasi statistik di bidang Teknik Lingkungan" />
  <meta name="twitter:image" content="cover.png" />

<meta name="author" content="Moh. Rosidi" />


<meta name="date" content="2019-06-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="Rosidi.png" />
  <link rel="shortcut icon" href="Rosidi.png" type="image/x-icon" />
<link rel="prev" href="visualisasi-data-menggunakan-ggplot.html">
<link rel="next" href="ekplorasi-data-menggunakan-grafik.html">
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #0000ff; } /* Keyword */
code > span.ch { color: #008080; } /* Char */
code > span.st { color: #008080; } /* String */
code > span.co { color: #008000; } /* Comment */
code > span.ot { color: #ff4000; } /* Other */
code > span.al { color: #ff0000; } /* Alert */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #008000; font-weight: bold; } /* Warning */
code > span.cn { } /* Constant */
code > span.sc { color: #008080; } /* SpecialChar */
code > span.vs { color: #008080; } /* VerbatimString */
code > span.ss { color: #008080; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { } /* Variable */
code > span.cf { color: #0000ff; } /* ControlFlow */
code > span.op { } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #ff4000; } /* Preprocessor */
code > span.do { color: #008000; } /* Documentation */
code > span.an { color: #008000; } /* Annotation */
code > span.cv { color: #008000; } /* CommentVar */
code > span.at { } /* Attribute */
code > span.in { color: #008000; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistika Lingkungan Menggunakan R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Pengantar</a></li>
<li class="part"><span><b>Bahasa Pemrograman R</b></span></li>
<li class="chapter" data-level="1" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html"><i class="fa fa-check"></i><b>1</b> Mengenal Bahasa R</a><ul>
<li class="chapter" data-level="1.1" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#sejarah-r"><i class="fa fa-check"></i><b>1.1</b> Sejarah R</a></li>
<li class="chapter" data-level="1.2" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#fitur-dan-karakteristik-r"><i class="fa fa-check"></i><b>1.2</b> Fitur dan Karakteristik R</a></li>
<li class="chapter" data-level="1.3" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#kelebihan-dan-kekurangan-r"><i class="fa fa-check"></i><b>1.3</b> Kelebihan dan Kekurangan R</a></li>
<li class="chapter" data-level="1.4" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#rstudio"><i class="fa fa-check"></i><b>1.4</b> RStudio</a></li>
<li class="chapter" data-level="1.5" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#menginstall-r-dan-rstudio"><i class="fa fa-check"></i><b>1.5</b> Menginstall R dan RStudio</a></li>
<li class="chapter" data-level="1.6" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#working-directory"><i class="fa fa-check"></i><b>1.6</b> Working Directory</a><ul>
<li class="chapter" data-level="1.6.1" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#mengubah-lokasi-working-directory"><i class="fa fa-check"></i><b>1.6.1</b> Mengubah Lokasi Working Directory</a></li>
<li class="chapter" data-level="1.6.2" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#mengubah-lokasi-working-directory-default"><i class="fa fa-check"></i><b>1.6.2</b> Mengubah Lokasi Working Directory Default</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#fasilitas-help"><i class="fa fa-check"></i><b>1.7</b> Fasilitas Help</a><ul>
<li class="chapter" data-level="1.7.1" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#mencari-help-dari-suatu-perintah-tertentu"><i class="fa fa-check"></i><b>1.7.1</b> Mencari Help dari Suatu Perintah Tertentu</a></li>
<li class="chapter" data-level="1.7.2" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#general-help"><i class="fa fa-check"></i><b>1.7.2</b> General Help</a></li>
<li class="chapter" data-level="1.7.3" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#fasilitas-help-lainnya"><i class="fa fa-check"></i><b>1.7.3</b> Fasilitas Help Lainnya</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="mengenal-bahasa-r.html"><a href="mengenal-bahasa-r.html#referensi"><i class="fa fa-check"></i><b>1.8</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html"><i class="fa fa-check"></i><b>2</b> Dasar Pemrograman Menggunakan R</a><ul>
<li class="chapter" data-level="2.1" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#operator-aritmatika"><i class="fa fa-check"></i><b>2.1</b> Operator Aritmatika</a></li>
<li class="chapter" data-level="2.2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#fungsi-aritmetik"><i class="fa fa-check"></i><b>2.2</b> Fungsi Aritmetik</a></li>
<li class="chapter" data-level="2.3" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#operator-relasi"><i class="fa fa-check"></i><b>2.3</b> Operator Relasi</a></li>
<li class="chapter" data-level="2.4" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#operator-logika"><i class="fa fa-check"></i><b>2.4</b> Operator Logika</a></li>
<li class="chapter" data-level="2.5" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#memasukkan-nilai-kedalam-variabel"><i class="fa fa-check"></i><b>2.5</b> Memasukkan Nilai Kedalam Variabel</a></li>
<li class="chapter" data-level="2.6" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#tipe-dan-struktur-data"><i class="fa fa-check"></i><b>2.6</b> Tipe dan Struktur Data</a></li>
<li class="chapter" data-level="2.7" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#vektor"><i class="fa fa-check"></i><b>2.7</b> Vektor</a><ul>
<li class="chapter" data-level="2.7.1" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#membuat-vektor"><i class="fa fa-check"></i><b>2.7.1</b> Membuat vektor</a></li>
<li class="chapter" data-level="2.7.2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#missing-values"><i class="fa fa-check"></i><b>2.7.2</b> Missing Values</a></li>
<li class="chapter" data-level="2.7.3" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#subset-pada-vektor"><i class="fa fa-check"></i><b>2.7.3</b> Subset Pada Vektor</a></li>
<li class="chapter" data-level="2.7.4" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#operasi-matematis-menggunakan-vektor"><i class="fa fa-check"></i><b>2.7.4</b> Operasi Matematis Menggunakan Vektor</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#matriks"><i class="fa fa-check"></i><b>2.8</b> Matriks</a><ul>
<li class="chapter" data-level="2.8.1" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#membuat-matriks"><i class="fa fa-check"></i><b>2.8.1</b> Membuat matriks</a></li>
<li class="chapter" data-level="2.8.2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#subset-pada-matriks"><i class="fa fa-check"></i><b>2.8.2</b> Subset Pada Matriks</a></li>
<li class="chapter" data-level="2.8.3" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#perhitungan-menggunakan-matriks"><i class="fa fa-check"></i><b>2.8.3</b> Perhitungan Menggunakan Matriks</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#faktor"><i class="fa fa-check"></i><b>2.9</b> Faktor</a><ul>
<li class="chapter" data-level="2.9.1" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#membuat-variabel-faktor"><i class="fa fa-check"></i><b>2.9.1</b> Membuat Variabel Faktor</a></li>
<li class="chapter" data-level="2.9.2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#perhitungan-menggunakan-faktor"><i class="fa fa-check"></i><b>2.9.2</b> Perhitungan Menggunakan Faktor</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#data-frames"><i class="fa fa-check"></i><b>2.10</b> Data Frames</a><ul>
<li class="chapter" data-level="2.10.1" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#membuat-data-frame"><i class="fa fa-check"></i><b>2.10.1</b> Membuat Data Frame</a></li>
<li class="chapter" data-level="2.10.2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#subset-pada-data-frame"><i class="fa fa-check"></i><b>2.10.2</b> Subset Pada Data Frame</a></li>
<li class="chapter" data-level="2.10.3" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#memperluas-data-frame"><i class="fa fa-check"></i><b>2.10.3</b> Memperluas Data Frame</a></li>
<li class="chapter" data-level="2.10.4" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#perhitungan-pada-data-frame"><i class="fa fa-check"></i><b>2.10.4</b> Perhitungan Pada Data Frame</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#list"><i class="fa fa-check"></i><b>2.11</b> List</a><ul>
<li class="chapter" data-level="2.11.1" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#membuat-list"><i class="fa fa-check"></i><b>2.11.1</b> Membuat List</a></li>
<li class="chapter" data-level="2.11.2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#subset-list"><i class="fa fa-check"></i><b>2.11.2</b> Subset List</a></li>
<li class="chapter" data-level="2.11.3" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#memperluas-list"><i class="fa fa-check"></i><b>2.11.3</b> Memperluas List</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#loop"><i class="fa fa-check"></i><b>2.12</b> Loop</a><ul>
<li class="chapter" data-level="2.12.1" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#for-loop"><i class="fa fa-check"></i><b>2.12.1</b> For Loop</a></li>
<li class="chapter" data-level="2.12.2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#while-loop"><i class="fa fa-check"></i><b>2.12.2</b> While Loop</a></li>
<li class="chapter" data-level="2.12.3" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#repeat-loop"><i class="fa fa-check"></i><b>2.12.3</b> Repeat Loop</a></li>
<li class="chapter" data-level="2.12.4" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#break"><i class="fa fa-check"></i><b>2.12.4</b> Break</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#loop-menggunakan-apply-family-function"><i class="fa fa-check"></i><b>2.13</b> Loop Menggunakan Apply Family Function</a><ul>
<li class="chapter" data-level="2.13.1" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#apply"><i class="fa fa-check"></i><b>2.13.1</b> Apply</a></li>
<li class="chapter" data-level="2.13.2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#lapply"><i class="fa fa-check"></i><b>2.13.2</b> lapply</a></li>
<li class="chapter" data-level="2.13.3" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#sapply"><i class="fa fa-check"></i><b>2.13.3</b> sapply</a></li>
<li class="chapter" data-level="2.13.4" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#vapply"><i class="fa fa-check"></i><b>2.13.4</b> vapply</a></li>
<li class="chapter" data-level="2.13.5" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#tapply"><i class="fa fa-check"></i><b>2.13.5</b> tapply</a></li>
</ul></li>
<li class="chapter" data-level="2.14" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#loop-menggunakan-map-function-pada-library-purrr"><i class="fa fa-check"></i><b>2.14</b> Loop Menggunakan map function pada Library <code>purrr</code></a></li>
<li class="chapter" data-level="2.15" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#decision-making"><i class="fa fa-check"></i><b>2.15</b> Decision Making</a><ul>
<li class="chapter" data-level="2.15.1" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#if-statement"><i class="fa fa-check"></i><b>2.15.1</b> if statement</a></li>
<li class="chapter" data-level="2.15.2" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#if-else-statement"><i class="fa fa-check"></i><b>2.15.2</b> if else statement</a></li>
<li class="chapter" data-level="2.15.3" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#switch-statement"><i class="fa fa-check"></i><b>2.15.3</b> switch statement</a></li>
</ul></li>
<li class="chapter" data-level="2.16" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#fungsi"><i class="fa fa-check"></i><b>2.16</b> Fungsi</a></li>
<li class="chapter" data-level="2.17" data-path="dasar-pemrograman-menggunakan-r.html"><a href="dasar-pemrograman-menggunakan-r.html#referensi-1"><i class="fa fa-check"></i><b>2.17</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html"><i class="fa fa-check"></i><b>3</b> Manajemen Data R</a><ul>
<li class="chapter" data-level="3.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#tidyverse"><i class="fa fa-check"></i><b>3.1</b> Tidyverse</a></li>
<li class="chapter" data-level="3.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#import-file"><i class="fa fa-check"></i><b>3.2</b> Import File</a><ul>
<li class="chapter" data-level="3.2.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#import-file-menggunakan-fungsi-bawaan-r"><i class="fa fa-check"></i><b>3.2.1</b> Import File Menggunakan Fungsi Bawaan R</a></li>
<li class="chapter" data-level="3.2.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#membaca-file-csv-dan-txt-menggunakan-library-readr"><i class="fa fa-check"></i><b>3.2.2</b> Membaca File CSV dan TXT Menggunakan Library readr</a></li>
<li class="chapter" data-level="3.2.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#import-file-excel-pada-r"><i class="fa fa-check"></i><b>3.2.3</b> Import File Excel Pada R</a></li>
<li class="chapter" data-level="3.2.4" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#membaca-file-dari-format-aplikasi-statistik"><i class="fa fa-check"></i><b>3.2.4</b> Membaca File Dari Format Aplikasi Statistik</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#import-beberapa-file-dalam-beberapa-baris-kode"><i class="fa fa-check"></i><b>3.3</b> Import Beberapa File Dalam Beberapa Baris Kode</a><ul>
<li class="chapter" data-level="3.3.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#for-loop-1"><i class="fa fa-check"></i><b>3.3.1</b> for loop</a></li>
<li class="chapter" data-level="3.3.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#apply-family-function"><i class="fa fa-check"></i><b>3.3.2</b> Apply Family Function</a></li>
<li class="chapter" data-level="3.3.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#map-family-function"><i class="fa fa-check"></i><b>3.3.3</b> Map Family Function</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#eksport-file"><i class="fa fa-check"></i><b>3.4</b> Eksport File</a><ul>
<li class="chapter" data-level="3.4.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#eksport-data-menjadi-format-txt-dan-csv"><i class="fa fa-check"></i><b>3.4.1</b> Eksport Data Menjadi Format TXT dan CSV</a></li>
<li class="chapter" data-level="3.4.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#eksport-data-menjadi-format-excel"><i class="fa fa-check"></i><b>3.4.2</b> Eksport Data Menjadi Format Excel</a></li>
<li class="chapter" data-level="3.4.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#eksport-file-dalam-format-sas-spss-dan-stata"><i class="fa fa-check"></i><b>3.4.3</b> Eksport File Dalam Format SAS, SPSS, dan STATA</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#tibble-data-format"><i class="fa fa-check"></i><b>3.5</b> Tibble Data Format</a><ul>
<li class="chapter" data-level="3.5.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#membuat-tibble"><i class="fa fa-check"></i><b>3.5.1</b> Membuat Tibble</a></li>
<li class="chapter" data-level="3.5.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#tibble-vs-data-frame"><i class="fa fa-check"></i><b>3.5.2</b> Tibble vs Data Frame</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#merapikan-data"><i class="fa fa-check"></i><b>3.6</b> Merapikan Data</a><ul>
<li class="chapter" data-level="3.6.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#gather"><i class="fa fa-check"></i><b>3.6.1</b> Gather</a></li>
<li class="chapter" data-level="3.6.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#spread"><i class="fa fa-check"></i><b>3.6.2</b> Spread</a></li>
<li class="chapter" data-level="3.6.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#separate"><i class="fa fa-check"></i><b>3.6.3</b> Separate</a></li>
<li class="chapter" data-level="3.6.4" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#unite"><i class="fa fa-check"></i><b>3.6.4</b> Unite</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#transformasi-data"><i class="fa fa-check"></i><b>3.7</b> Transformasi Data</a><ul>
<li class="chapter" data-level="3.7.1" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#paket-dplyr"><i class="fa fa-check"></i><b>3.7.1</b> Paket dplyr</a></li>
<li class="chapter" data-level="3.7.2" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#filter"><i class="fa fa-check"></i><b>3.7.2</b> filter()</a></li>
<li class="chapter" data-level="3.7.3" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#arrange"><i class="fa fa-check"></i><b>3.7.3</b> arrange()</a></li>
<li class="chapter" data-level="3.7.4" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#select"><i class="fa fa-check"></i><b>3.7.4</b> select()</a></li>
<li class="chapter" data-level="3.7.5" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#mutate"><i class="fa fa-check"></i><b>3.7.5</b> mutate()</a></li>
<li class="chapter" data-level="3.7.6" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#summarize-dan-group_by"><i class="fa fa-check"></i><b>3.7.6</b> summarize() dan group_by()</a></li>
<li class="chapter" data-level="3.7.7" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#mengkombinasikan-beberapa-operasi-menggunakan-operator-pipe"><i class="fa fa-check"></i><b>3.7.7</b> Mengkombinasikan Beberapa Operasi Menggunakan Operator Pipe (%&gt;%)</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="manajemen-data-r.html"><a href="manajemen-data-r.html#referensi-2"><i class="fa fa-check"></i><b>3.8</b> Referensi</a></li>
</ul></li>
<li class="part"><span><b>Visualisasi Data - R</b></span></li>
<li class="chapter" data-level="4" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html"><i class="fa fa-check"></i><b>4</b> Visualisasi Data Menggunakan Fungsi Dasar R</a><ul>
<li class="chapter" data-level="4.1" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#visualisasi-data-menggunakan-fungsi-plot"><i class="fa fa-check"></i><b>4.1</b> Visualisasi Data Menggunakan Fungsi plot()</a></li>
<li class="chapter" data-level="4.2" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#matriks-scatterplot"><i class="fa fa-check"></i><b>4.2</b> Matriks Scatterplot</a></li>
<li class="chapter" data-level="4.3" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#box-plot"><i class="fa fa-check"></i><b>4.3</b> Box plot</a></li>
<li class="chapter" data-level="4.4" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#bar-plot"><i class="fa fa-check"></i><b>4.4</b> Bar Plot</a></li>
<li class="chapter" data-level="4.5" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#line-plot"><i class="fa fa-check"></i><b>4.5</b> Line Plot</a></li>
<li class="chapter" data-level="4.6" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#pie-chart"><i class="fa fa-check"></i><b>4.6</b> Pie Chart</a></li>
<li class="chapter" data-level="4.7" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#histogram-dan-density-plot"><i class="fa fa-check"></i><b>4.7</b> Histogram dan Density Plot</a></li>
<li class="chapter" data-level="4.8" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#qq-plot"><i class="fa fa-check"></i><b>4.8</b> QQ Plot</a></li>
<li class="chapter" data-level="4.9" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#dot-chart"><i class="fa fa-check"></i><b>4.9</b> Dot Chart</a></li>
<li class="chapter" data-level="4.10" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#kustomisasi-parameter-grafik"><i class="fa fa-check"></i><b>4.10</b> Kustomisasi Parameter Grafik</a><ul>
<li class="chapter" data-level="4.10.1" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#menambahkan-judul"><i class="fa fa-check"></i><b>4.10.1</b> Menambahkan Judul</a></li>
<li class="chapter" data-level="4.10.2" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#menambahkan-legend"><i class="fa fa-check"></i><b>4.10.2</b> Menambahkan Legend</a></li>
<li class="chapter" data-level="4.10.3" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#menambahkan-teks-pada-grafik"><i class="fa fa-check"></i><b>4.10.3</b> Menambahkan Teks Pada Grafik</a></li>
<li class="chapter" data-level="4.10.4" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#menambahkan-garis-pada-plot"><i class="fa fa-check"></i><b>4.10.4</b> Menambahkan Garis Pada Plot</a></li>
<li class="chapter" data-level="4.10.5" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#merubah-simbol-plot-dan-jenis-garis"><i class="fa fa-check"></i><b>4.10.5</b> Merubah Simbol plot dan Jenis Garis</a></li>
<li class="chapter" data-level="4.10.6" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#mengatur-axis-plot"><i class="fa fa-check"></i><b>4.10.6</b> Mengatur Axis Plot</a></li>
<li class="chapter" data-level="4.10.7" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#mengatur-warna"><i class="fa fa-check"></i><b>4.10.7</b> Mengatur Warna</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#alternatif-library-dasar-lain"><i class="fa fa-check"></i><b>4.11</b> Alternatif Library Dasar Lain</a><ul>
<li class="chapter" data-level="4.11.1" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#scatterplot-menggunakan-library-car"><i class="fa fa-check"></i><b>4.11.1</b> Scatterplot Menggunakan Library car</a></li>
<li class="chapter" data-level="4.11.2" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#matriks-scatterplot-menggunakan-library-psych"><i class="fa fa-check"></i><b>4.11.2</b> Matriks Scatterplot Menggunakan Library psych</a></li>
<li class="chapter" data-level="4.11.3" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#box-plot-menggunakan-library-gplots"><i class="fa fa-check"></i><b>4.11.3</b> Box Plot Menggunakan Library gplots</a></li>
<li class="chapter" data-level="4.11.4" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#qq-plot-menggunakan-library-car"><i class="fa fa-check"></i><b>4.11.4</b> QQ Plot Menggunakan Library car</a></li>
<li class="chapter" data-level="4.11.5" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#plot-group-means-menggunakan-library-gplots"><i class="fa fa-check"></i><b>4.11.5</b> Plot Group Means Menggunakan Library gplots</a></li>
</ul></li>
<li class="chapter" data-level="4.12" data-path="visualisasi-data-menggunakan-fungsi-dasar-r.html"><a href="visualisasi-data-menggunakan-fungsi-dasar-r.html#referensi-3"><i class="fa fa-check"></i><b>4.12</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html"><i class="fa fa-check"></i><b>5</b> Visualisasi Data Menggunakan GGPLOT</a><ul>
<li class="chapter" data-level="5.1" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#scatterplot"><i class="fa fa-check"></i><b>5.1</b> Scatterplot</a></li>
<li class="chapter" data-level="5.2" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#box-plot-dan-violin-plot"><i class="fa fa-check"></i><b>5.2</b> Box Plot dan Violin Plot</a></li>
<li class="chapter" data-level="5.3" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#bar-plot-1"><i class="fa fa-check"></i><b>5.3</b> Bar Plot</a></li>
<li class="chapter" data-level="5.4" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#line-plot-1"><i class="fa fa-check"></i><b>5.4</b> Line Plot</a></li>
<li class="chapter" data-level="5.5" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#pie-chart-1"><i class="fa fa-check"></i><b>5.5</b> Pie Chart</a></li>
<li class="chapter" data-level="5.6" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#histogram-dan-desity-plot"><i class="fa fa-check"></i><b>5.6</b> Histogram dan Desity Plot</a></li>
<li class="chapter" data-level="5.7" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#qq-plot-1"><i class="fa fa-check"></i><b>5.7</b> QQ Plot</a></li>
<li class="chapter" data-level="5.8" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#dot-plot"><i class="fa fa-check"></i><b>5.8</b> Dot Plot</a></li>
<li class="chapter" data-level="5.9" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#ecdf-plot"><i class="fa fa-check"></i><b>5.9</b> ECDF Plot</a></li>
<li class="chapter" data-level="5.10" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#parameter-grafik"><i class="fa fa-check"></i><b>5.10</b> Parameter Grafik</a><ul>
<li class="chapter" data-level="5.10.1" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#merubah-judul-grafik-keterangan-axis-dan-legend"><i class="fa fa-check"></i><b>5.10.1</b> Merubah Judul Grafik, Keterangan Axis dan Legend</a></li>
<li class="chapter" data-level="5.10.2" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#merubah-tampilan-dan-posisi-legend"><i class="fa fa-check"></i><b>5.10.2</b> Merubah Tampilan dan Posisi Legend</a></li>
<li class="chapter" data-level="5.10.3" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#merubah-warana-pada-grafik-secara-otomatis-dan-manual"><i class="fa fa-check"></i><b>5.10.3</b> Merubah Warana Pada Grafik Secara Otomatis dan Manual</a></li>
<li class="chapter" data-level="5.10.4" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#kustomisasi-titik"><i class="fa fa-check"></i><b>5.10.4</b> Kustomisasi Titik</a></li>
<li class="chapter" data-level="5.10.5" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#kustomisasi-jenis-garis"><i class="fa fa-check"></i><b>5.10.5</b> Kustomisasi Jenis Garis</a></li>
<li class="chapter" data-level="5.10.6" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#menambahkan-label-pada-titik-observasi-dan-bidang-plot"><i class="fa fa-check"></i><b>5.10.6</b> Menambahkan Label Pada Titik Observasi dan Bidang Plot</a></li>
<li class="chapter" data-level="5.10.7" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#kustomisasi-tema-pada-plot"><i class="fa fa-check"></i><b>5.10.7</b> Kustomisasi Tema Pada Plot</a></li>
<li class="chapter" data-level="5.10.8" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#penskalaan-dan-transformasi-axis"><i class="fa fa-check"></i><b>5.10.8</b> Penskalaan dan Transformasi Axis</a></li>
<li class="chapter" data-level="5.10.9" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#kustomisasi-tick-mark-axis"><i class="fa fa-check"></i><b>5.10.9</b> Kustomisasi Tick Mark Axis</a></li>
<li class="chapter" data-level="5.10.10" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#menambahkan-garis-lurus-pada-plot"><i class="fa fa-check"></i><b>5.10.10</b> Menambahkan Garis Lurus Pada Plot</a></li>
<li class="chapter" data-level="5.10.11" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#melakukan-rotasi-pada-grafik"><i class="fa fa-check"></i><b>5.10.11</b> Melakukan Rotasi Pada Grafik</a></li>
<li class="chapter" data-level="5.10.12" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#facet"><i class="fa fa-check"></i><b>5.10.12</b> Facet</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="visualisasi-data-menggunakan-ggplot.html"><a href="visualisasi-data-menggunakan-ggplot.html#referensi-4"><i class="fa fa-check"></i><b>5.11</b> Referensi</a></li>
</ul></li>
<li class="part"><span><b>Statistika Deskriptif - R</b></span></li>
<li class="chapter" data-level="6" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html"><i class="fa fa-check"></i><b>6</b> Ringkasan Numerik</a><ul>
<li class="chapter" data-level="6.1" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-pemusatan-data"><i class="fa fa-check"></i><b>6.1</b> Ukuran Pemusatan Data</a><ul>
<li class="chapter" data-level="6.1.1" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#pengukuran-klasik-mean"><i class="fa fa-check"></i><b>6.1.1</b> Pengukuran Klasik-Mean</a></li>
<li class="chapter" data-level="6.1.2" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#median-sebagai-ukuran-pemusatan-data-yang-resistan"><i class="fa fa-check"></i><b>6.1.2</b> Median Sebagai Ukuran Pemusatan Data yang Resistan</a></li>
<li class="chapter" data-level="6.1.3" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-pemusatan-data-lainnya"><i class="fa fa-check"></i><b>6.1.3</b> Ukuran Pemusatan Data Lainnya</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-sebaran-data"><i class="fa fa-check"></i><b>6.2</b> Ukuran Sebaran Data</a><ul>
<li class="chapter" data-level="6.2.1" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#pengukuran-klasik-varian-dan-simpangan-baku"><i class="fa fa-check"></i><b>6.2.1</b> Pengukuran Klasik (Varian dan Simpangan Baku)</a></li>
<li class="chapter" data-level="6.2.2" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-sebaran-data-yang-resisten-terhadap-outlier"><i class="fa fa-check"></i><b>6.2.2</b> Ukuran Sebaran Data yang Resisten Terhadap Outlier</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ringkasan-data-menggunakan-fungsi-summary-dan-stat.desc"><i class="fa fa-check"></i><b>6.3</b> Ringkasan Data Menggunakan Fungsi summary() dan stat.desc()</a></li>
<li class="chapter" data-level="6.4" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-kemencengan-data"><i class="fa fa-check"></i><b>6.4</b> Ukuran Kemencengan Data</a><ul>
<li class="chapter" data-level="6.4.1" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-kemencengan-klasik"><i class="fa fa-check"></i><b>6.4.1</b> Ukuran Kemencengan Klasik</a></li>
<li class="chapter" data-level="6.4.2" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#ukuran-kemencengan-yang-resisten"><i class="fa fa-check"></i><b>6.4.2</b> Ukuran Kemencengan yang Resisten</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#outlier"><i class="fa fa-check"></i><b>6.5</b> Outlier</a></li>
<li class="chapter" data-level="6.6" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#transformasi-data-1"><i class="fa fa-check"></i><b>6.6</b> Transformasi Data</a></li>
<li class="chapter" data-level="6.7" data-path="ringkasan-numerik.html"><a href="ringkasan-numerik.html#referensi-5"><i class="fa fa-check"></i><b>6.7</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html"><i class="fa fa-check"></i><b>7</b> Ekplorasi Data Menggunakan Grafik</a><ul>
<li class="chapter" data-level="7.1" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-untuk-melihat-ditribusi-data"><i class="fa fa-check"></i><b>7.1</b> Grafik Untuk Melihat Ditribusi Data</a><ul>
<li class="chapter" data-level="7.1.1" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#histogram"><i class="fa fa-check"></i><b>7.1.1</b> Histogram</a></li>
<li class="chapter" data-level="7.1.2" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#density-plot"><i class="fa fa-check"></i><b>7.1.2</b> Density Plot</a></li>
<li class="chapter" data-level="7.1.3" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#qq-plot-2"><i class="fa fa-check"></i><b>7.1.3</b> QQ-plot</a></li>
<li class="chapter" data-level="7.1.4" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#box-plot-dan-violin-plot-1"><i class="fa fa-check"></i><b>7.1.4</b> Box Plot dan Violin Plot</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-untuk-melihat-beda-distribusi-data-antar-grup"><i class="fa fa-check"></i><b>7.2</b> Grafik Untuk Melihat Beda Distribusi Data Antar Grup</a></li>
<li class="chapter" data-level="7.3" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-untuk-memvisualisasikan-korelasi-antar-variabel"><i class="fa fa-check"></i><b>7.3</b> Grafik Untuk Memvisualisasikan Korelasi Antar Variabel</a></li>
<li class="chapter" data-level="7.4" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-yang-digunakan-untuk-memvisualisasikan-asosiasi-antar-variabel"><i class="fa fa-check"></i><b>7.4</b> Grafik Yang Digunakan Untuk Memvisualisasikan Asosiasi Antar Variabel</a></li>
<li class="chapter" data-level="7.5" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#grafik-yang-digunakan-untuk-memisualisasikan-ukuran-sampel-dan-perubahan-sepanjang-waktu"><i class="fa fa-check"></i><b>7.5</b> Grafik Yang Digunakan Untuk Memisualisasikan Ukuran Sampel dan Perubahan Sepanjang Waktu</a></li>
<li class="chapter" data-level="7.6" data-path="ekplorasi-data-menggunakan-grafik.html"><a href="ekplorasi-data-menggunakan-grafik.html#referensi-6"><i class="fa fa-check"></i><b>7.6</b> Referensi</a></li>
</ul></li>
<li class="part"><span><b>Probabilitas dan Distribusi Probabilitas</b></span></li>
<li class="chapter" data-level="8" data-path="probabilitas.html"><a href="probabilitas.html"><i class="fa fa-check"></i><b>8</b> Probabilitas</a><ul>
<li class="chapter" data-level="8.1" data-path="probabilitas.html"><a href="probabilitas.html#aturan-dasar-probabilitas"><i class="fa fa-check"></i><b>8.1</b> Aturan Dasar Probabilitas</a><ul>
<li class="chapter" data-level="8.1.1" data-path="probabilitas.html"><a href="probabilitas.html#peristiwa-mutually-exclusive"><i class="fa fa-check"></i><b>8.1.1</b> Peristiwa <em>Mutually Exclusive</em></a></li>
<li class="chapter" data-level="8.1.2" data-path="probabilitas.html"><a href="probabilitas.html#peristiwa-not-mutually-exclusive"><i class="fa fa-check"></i><b>8.1.2</b> Peristiwa <em>Not Mutually Exclusive</em></a></li>
<li class="chapter" data-level="8.1.3" data-path="probabilitas.html"><a href="probabilitas.html#peristiwa-dependent"><i class="fa fa-check"></i><b>8.1.3</b> Peristiwa <em>Dependent</em></a></li>
<li class="chapter" data-level="8.1.4" data-path="probabilitas.html"><a href="probabilitas.html#peristiwa-independent"><i class="fa fa-check"></i><b>8.1.4</b> Peristiwa <em>Independent</em></a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="probabilitas.html"><a href="probabilitas.html#teori-bayes"><i class="fa fa-check"></i><b>8.2</b> Teori Bayes</a></li>
<li class="chapter" data-level="8.3" data-path="probabilitas.html"><a href="probabilitas.html#ekspektasi-matematis"><i class="fa fa-check"></i><b>8.3</b> Ekspektasi Matematis</a></li>
<li class="chapter" data-level="8.4" data-path="probabilitas.html"><a href="probabilitas.html#referensi-7"><i class="fa fa-check"></i><b>8.4</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html"><i class="fa fa-check"></i><b>9</b> Distribusi Probabilitas</a><ul>
<li class="chapter" data-level="9.1" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#properti-umum-dari-distribusi-probabilitas"><i class="fa fa-check"></i><b>9.1</b> Properti Umum dari Distribusi Probabilitas</a></li>
<li class="chapter" data-level="9.2" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-binomial-dan-multinomial"><i class="fa fa-check"></i><b>9.2</b> Distribusi Binomial dan Multinomial</a><ul>
<li class="chapter" data-level="9.2.1" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-binomial"><i class="fa fa-check"></i><b>9.2.1</b> Distribusi Binomial</a></li>
<li class="chapter" data-level="9.2.2" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#multinomial-eksperimen-dan-distribusi-multinomial"><i class="fa fa-check"></i><b>9.2.2</b> Multinomial Eksperimen dan Distribusi Multinomial</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-hipergeometris"><i class="fa fa-check"></i><b>9.3</b> Distribusi Hipergeometris</a></li>
<li class="chapter" data-level="9.4" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-binomial-negatif-dan-distribusi-geometris"><i class="fa fa-check"></i><b>9.4</b> Distribusi Binomial Negatif dan Distribusi Geometris</a><ul>
<li class="chapter" data-level="9.4.1" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-binomial-negatif"><i class="fa fa-check"></i><b>9.4.1</b> Distribusi Binomial Negatif</a></li>
<li class="chapter" data-level="9.4.2" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-geometris"><i class="fa fa-check"></i><b>9.4.2</b> Distribusi Geometris</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-poisson"><i class="fa fa-check"></i><b>9.5</b> Distribusi Poisson</a></li>
<li class="chapter" data-level="9.6" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-uniform"><i class="fa fa-check"></i><b>9.6</b> Distribusi Uniform</a></li>
<li class="chapter" data-level="9.7" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-normal"><i class="fa fa-check"></i><b>9.7</b> Distribusi Normal</a><ul>
<li class="chapter" data-level="9.7.1" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#luas-area-di-bawah-kurva-normal"><i class="fa fa-check"></i><b>9.7.1</b> Luas Area Di Bawah Kurva Normal</a></li>
<li class="chapter" data-level="9.7.2" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#uji-kecocokan-distribusi-normal"><i class="fa fa-check"></i><b>9.7.2</b> Uji Kecocokan Distribusi Normal</a></li>
<li class="chapter" data-level="9.7.3" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#pendekatan-distribusi-binomial-menggunakan-distribusi-normal"><i class="fa fa-check"></i><b>9.7.3</b> Pendekatan Distribusi Binomial Menggunakan Distribusi Normal</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-gamma-dan-eksponensial"><i class="fa fa-check"></i><b>9.8</b> Distribusi Gamma dan Eksponensial</a></li>
<li class="chapter" data-level="9.9" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-chi-square-students-t-dan-snedecors-f."><i class="fa fa-check"></i><b>9.9</b> Distribusi Chi-Square, Student’s t, dan Snedecor’s F.</a><ul>
<li class="chapter" data-level="9.9.1" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-chi-square"><i class="fa fa-check"></i><b>9.9.1</b> Distribusi Chi-Square</a></li>
<li class="chapter" data-level="9.9.2" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-students-t"><i class="fa fa-check"></i><b>9.9.2</b> Distribusi Student’s t</a></li>
<li class="chapter" data-level="9.9.3" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-snedecors-f"><i class="fa fa-check"></i><b>9.9.3</b> Distribusi Snedecor’s F</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-kontinu-lainnya"><i class="fa fa-check"></i><b>9.10</b> Distribusi Kontinu Lainnya</a><ul>
<li class="chapter" data-level="9.10.1" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-beta"><i class="fa fa-check"></i><b>9.10.1</b> Distribusi Beta</a></li>
<li class="chapter" data-level="9.10.2" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-lognormal"><i class="fa fa-check"></i><b>9.10.2</b> Distribusi Lognormal</a></li>
<li class="chapter" data-level="9.10.3" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-cauchy"><i class="fa fa-check"></i><b>9.10.3</b> Distribusi Cauchy</a></li>
<li class="chapter" data-level="9.10.4" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-logistik"><i class="fa fa-check"></i><b>9.10.4</b> Distribusi Logistik</a></li>
<li class="chapter" data-level="9.10.5" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#distribusi-weibull"><i class="fa fa-check"></i><b>9.10.5</b> Distribusi Weibull</a></li>
</ul></li>
<li class="chapter" data-level="9.11" data-path="distribusi-probabilitas.html"><a href="distribusi-probabilitas.html#referensi-8"><i class="fa fa-check"></i><b>9.11</b> Referensi</a></li>
</ul></li>
<li class="part"><span><b>Statistika Inferensial - R</b></span></li>
<li class="chapter" data-level="10" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html"><i class="fa fa-check"></i><b>10</b> Penaksiran Secara Statistika</a><ul>
<li class="chapter" data-level="10.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#definisi-interval-estimasi"><i class="fa fa-check"></i><b>10.1</b> Definisi Interval Estimasi</a></li>
<li class="chapter" data-level="10.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interpretasi-interval-estimasi"><i class="fa fa-check"></i><b>10.2</b> Interpretasi Interval Estimasi</a></li>
<li class="chapter" data-level="10.3" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-median"><i class="fa fa-check"></i><b>10.3</b> Interval Kepercayaan Median</a><ul>
<li class="chapter" data-level="10.3.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-estimasi-median-metode-nonparametrik"><i class="fa fa-check"></i><b>10.3.1</b> Interval Estimasi Median Metode Nonparametrik</a></li>
<li class="chapter" data-level="10.3.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#metode-parametrik-interval-estimasi-median"><i class="fa fa-check"></i><b>10.3.2</b> Metode Parametrik Interval Estimasi Median</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-mean"><i class="fa fa-check"></i><b>10.4</b> Interval Kepercayaan Mean</a><ul>
<li class="chapter" data-level="10.4.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-mean-untuk-distribusi-yang-simetris"><i class="fa fa-check"></i><b>10.4.1</b> Interval Kepercayaan Mean Untuk Distribusi Yang Simetris</a></li>
<li class="chapter" data-level="10.4.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-mean-untuk-distribusi-yang-asimetris"><i class="fa fa-check"></i><b>10.4.2</b> Interval Kepercayaan Mean Untuk Distribusi Yang Asimetris</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-nonparametrik"><i class="fa fa-check"></i><b>10.5</b> Interval Prediksi Nonparametrik</a><ul>
<li class="chapter" data-level="10.5.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-nonparametrik-dua-sisi"><i class="fa fa-check"></i><b>10.5.1</b> Interval Prediksi Nonparametrik Dua Sisi</a></li>
<li class="chapter" data-level="10.5.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-nonparametrik-satu-sisi"><i class="fa fa-check"></i><b>10.5.2</b> Interval Prediksi Nonparametrik Satu Sisi</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-parametrik"><i class="fa fa-check"></i><b>10.6</b> Interval Prediksi Parametrik</a><ul>
<li class="chapter" data-level="10.6.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-distribusi-simetris"><i class="fa fa-check"></i><b>10.6.1</b> Interval Prediksi Distribusi Simetris</a></li>
<li class="chapter" data-level="10.6.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-prediksi-untuk-distribusi-data-yang-tidak-simetris"><i class="fa fa-check"></i><b>10.6.2</b> Interval Prediksi Untuk Distribusi Data Yang Tidak Simetris</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-persentil-interval-toleransi"><i class="fa fa-check"></i><b>10.7</b> Interval Kepercayaan Persentil (Interval Toleransi)</a><ul>
<li class="chapter" data-level="10.7.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-nonparametrik-persentil"><i class="fa fa-check"></i><b>10.7.1</b> Interval Kepercayaan Nonparametrik Persentil</a></li>
<li class="chapter" data-level="10.7.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#uji-nonparametrik-untuk-persentil"><i class="fa fa-check"></i><b>10.7.2</b> Uji Nonparametrik Untuk Persentil</a></li>
<li class="chapter" data-level="10.7.3" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-parametrik-untuk-persentil"><i class="fa fa-check"></i><b>10.7.3</b> Interval Kepercayaan Parametrik Untuk Persentil</a></li>
<li class="chapter" data-level="10.7.4" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#uji-parametrik-untuk-persentil"><i class="fa fa-check"></i><b>10.7.4</b> Uji Parametrik Untuk Persentil</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#interval-kepercayaan-menggunakan-metode-bootstrap"><i class="fa fa-check"></i><b>10.8</b> Interval Kepercayaan Menggunakan Metode Bootstrap</a></li>
<li class="chapter" data-level="10.9" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#kegunaan-lain-dari-interval-kepercayaan"><i class="fa fa-check"></i><b>10.9</b> Kegunaan Lain Dari Interval Kepercayaan</a><ul>
<li class="chapter" data-level="10.9.1" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#implikasi-non-normalitas-pada-pendeteksian-outlier"><i class="fa fa-check"></i><b>10.9.1</b> Implikasi Non-Normalitas Pada Pendeteksian <em>Outlier</em></a></li>
<li class="chapter" data-level="10.9.2" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#implikasi-non-normalitas-pada-kontrol-kualitas"><i class="fa fa-check"></i><b>10.9.2</b> Implikasi Non-Normalitas Pada Kontrol Kualitas</a></li>
<li class="chapter" data-level="10.9.3" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#implikasi-non-normalitas-terhadap-desain-sampling"><i class="fa fa-check"></i><b>10.9.3</b> Implikasi Non-Normalitas Terhadap Desain Sampling</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="penaksiran-secara-statistika.html"><a href="penaksiran-secara-statistika.html#referensi-9"><i class="fa fa-check"></i><b>10.10</b> Referensi</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html"><i class="fa fa-check"></i><b>11</b> Uji Hipotesis</a><ul>
<li class="chapter" data-level="11.1" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#klasifikasi-uji-hipotesis"><i class="fa fa-check"></i><b>11.1</b> Klasifikasi Uji Hipotesis</a><ul>
<li class="chapter" data-level="11.1.1" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#klasifikasi-berdasarkan-skala-pengukuran"><i class="fa fa-check"></i><b>11.1.1</b> Klasifikasi Berdasarkan Skala Pengukuran</a></li>
<li class="chapter" data-level="11.1.2" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#klasifikasi-berdasarkan-distribusi-data"><i class="fa fa-check"></i><b>11.1.2</b> Klasifikasi Berdasarkan Distribusi Data</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#menyiapkan-prosedur-uji-hipotesis"><i class="fa fa-check"></i><b>11.2</b> Menyiapkan Prosedur UJi Hipotesis</a><ul>
<li class="chapter" data-level="11.2.1" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#memilih-uji-yang-sesuai"><i class="fa fa-check"></i><b>11.2.1</b> Memilih Uji yang Sesuai</a></li>
<li class="chapter" data-level="11.2.2" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#hipotesis-nol-dan-alternatif"><i class="fa fa-check"></i><b>11.2.2</b> Hipotesis Nol dan Alternatif</a></li>
<li class="chapter" data-level="11.2.3" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#statistik-uji-dan-aturan-penolakan"><i class="fa fa-check"></i><b>11.2.3</b> Statistik Uji dan Aturan Penolakan</a></li>
<li class="chapter" data-level="11.2.4" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#p-value"><i class="fa fa-check"></i><b>11.2.4</b> P-Value</a></li>
<li class="chapter" data-level="11.2.5" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#membuat-keputusan-untuk-menolak-hipotesis-nol-atau-tidak"><i class="fa fa-check"></i><b>11.2.5</b> Membuat Keputusan Untuk Menolak Hipotesis Nol atau Tidak</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#uji-nilai-rata-rata-sampel-tunggal"><i class="fa fa-check"></i><b>11.3</b> Uji Nilai Rata-Rata Sampel Tunggal</a><ul>
<li class="chapter" data-level="11.3.1" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#uji-parametrik"><i class="fa fa-check"></i><b>11.3.1</b> Uji Parametrik</a></li>
<li class="chapter" data-level="11.3.2" data-path="uji-hipotesis.html"><a href="uji-hipotesis.html#uji-nonparametrik"><i class="fa fa-check"></i><b>11.3.2</b> Uji Nonparametrik</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://environmental-data-modeling.netlify.com/" target="blank">Author's Website</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistika Lingkungan Menggunakan R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ringkasan-numerik" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Ringkasan Numerik</h1>
<p>Pada bidang lingkungan kita sering kali menemui sebuah pernyataan “konsentrasi rata-rata TSS pada sungai tersebut adalah 30 mg/l” atau “kedalaman penampang saluran tersebut berkisar antara 1 sampai 2 meter”. Kedua pernyataan tersebut merupakan sebuah penyapaian informasi terkait karakteristik data yang ada. Pernyataan yang pertama menyatakan karakteristik nilai pemusatan data, sedangkan yang kedua menyatakan karakteristik sebaran suatu data.</p>
<p>Karakteristik lain yang sering digunakan untuk menjelaskan suatu data adalah bentuk distibusi suatu data dan estimasi nilai ekstrim seperti nilai masimum dan minimum suatu data. Seluruh karakteristik data tersebut perlu dihitung untuk memperoleh informasi numerik pada data.</p>
<p>Pada chapter ini kita akan membahas terkait metode untuk membuat ringkasan dan deksripsi data. Pembahasan akan terdiri dari ukuran nilai pemusatan data, ukuran sebaran atau variabilitas data dan bentuk distribusi data. Selain itu kita akan membahas nilai ekstrim yang ada pada sebuah data dan transformasi data.</p>
<div id="ukuran-pemusatan-data" class="section level2">
<h2><span class="header-section-number">6.1</span> Ukuran Pemusatan Data</h2>
<p>Nilai rata-rata (mean) dan nilai tengah (median) merupakan dua nilai yang paling umum digunakan untuk menyatakan lokasi pemusatan data meskipun kedua nilai bukanlah satu atau dua ukuran yang tersedia. Apa sajakah properti dari kedua ukuran tersebut dan kapan salah satu atau keduanya dapat digunakan bersamaan?.</p>
<div id="pengukuran-klasik-mean" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Pengukuran Klasik-Mean</h3>
<p>Nilai mean (<span class="math inline">\(\overline{X}\)</span>) diperoleh dengan menjumlahkan seluruh data dan membaginya dengan jumlah observasinya yang dapat dituliskan seperti Persamaan <a href="ringkasan-numerik.html#eq:mean">(6.1)</a>:</p>
<span class="math display" id="eq:mean">\[\begin{equation}
  \overline{X}=\text{}\sum_{_{i=1}}^n\frac{X_i}{n}
  \tag{6.1}
\end{equation}\]</span>
<p>Nilai mean yang disimbolkan dengan “X bar” merupakan nilai mean untuk sampel. Nilai mean untuk populasi disimbolkan oleh huruf Yunani “mu atau <span class="math inline">\(\mu\)</span>”.</p>
<p>Pada Persamaan <a href="ringkasan-numerik.html#eq:mean">(6.1)</a>, jika data terdiri dari banyak grup maka nilai rata-rata dihitung berdasarkan jumlah nilai observasi dikali dengan bobotnya. Nilai mean tersebut disebut sebagai <em>weighted mean</em> yang dapat ditulis berdasarkan Persamaan Persamaan <a href="ringkasan-numerik.html#eq:weightedmean">(6.2)</a>.</p>
<span class="math display" id="eq:weightedmean">\[\begin{equation}
  \overline{X}\ =\text{}\sum_{_{i=1}}^n\overline{X_i}\cdot\frac{n_i}{n}
  \tag{6.2}
\end{equation}\]</span>
<p>dimana <span class="math inline">\(\overline{X_i}\)</span> merupakan nilai rata-rata grup ke-i dan <span class="math inline">\(\frac{n_i}{n}\)</span> merupakan bobot pengali yang berupa rasio antara observasi grup ke-i dengan keseluruhan observasi.</p>
<p>Kita biasanya akan berhadapan dengan nilai observasi yang baru sehingga nilai mean yang telah ada akan ikut berubah. Perubahan nilai mean tersebut disebabkan karena setiap observasi yang disertakan dalam perhitungan mean memiliki pengaruhnya masing-masing. Jika observasi tersebut cenderung ekstrim besar maka nilai mean akan bergeser menuju kearahnya begitu juga sebaliknya.</p>
<p>Pengaruh dari sebuah nilai observasi ke-j atau <span class="math inline">\(X_j\)</span> dapat dilihat dengan menghitung seluruh observasi secara bersamaan kecuali observasi ke-j pada sebuah grup. Dapat dituliskan pada Persamaan <a href="ringkasan-numerik.html#eq:influencemean2">(6.4)</a></p>
<span class="math display" id="eq:influencemean1">\[\begin{equation}
  \overline{X} =\text{}\overline{X_{\left(j\right)}}\ \cdot\frac{\left(n-1\right)}{n}+X_j\cdot\frac{1}{n}
  \tag{6.3}
\end{equation}\]</span>
<span class="math display" id="eq:influencemean2">\[\begin{equation}
  \overline{X} =\overline{X}_{\left(j\right)}+\left(X_j-\overline{X}_{\left(j\right)}\right)\cdot\frac{1}{n}
  \tag{6.4}
\end{equation}\]</span>
<p>dimana <span class="math inline">\(\overline{X}_{\left(j\right)}\)</span> adalah nilai mean seluruh observasi kecuali <span class="math inline">\(X_j\)</span>. Setiap observasi yang mempengaruhi nilai mean keseluruhan (<span class="math inline">\(\overline{X}\)</span>) didefinisikan oleh <span class="math inline">\(\left(X_j-\overline{X}_{\left(j\right)}\right)\)</span> sebagai jarak antara observasi tersebut dengan nilai rata-rata yang tidak termasuk observasi tersebut di dalamnya. Sehingga seluruh nilai observasi tidak memiliki pengaruh yang sama terhadap nilai rata-rata seluruh observasi.</p>
<p><em>Outlier</em> merupakan observasi yang memiliki nilai yang ekstrim tinggi atau rendah dibanding seluruh observasi yang ada sehingga memiliki pengaruh yang besar terhadap nilai mean keseluruhan (<span class="math inline">\(\overline{X}\)</span>). Pengaruhnya yang sangat besar terhadap nilai rata-rata keseluruhan akan menyebabkan nilai rata-rata akan bergeser ke arah <em>outlier</em> tersebut. Selain itu penampilan dari distribusi frekuensi yang terbentuk akan terlihat memiliki ekor yang panjang.</p>
<p>Untuk lebih memahami pengaruh observasi terhadap nilai rata-rata, disajikan dua buah gambar yaitu: Gambar <a href="ringkasan-numerik.html#fig:mean1">6.1</a> dan Gambar <a href="ringkasan-numerik.html#fig:mean2">6.2</a></p>
<div class="figure" style="text-align: center"><span id="fig:mean1"></span>
<img src="mean1.PNG" alt="Nilai mean (segitiga) sebagai titik kesetimbangan pada data." width="70%" />
<p class="caption">
Gambar 6.1: Nilai mean (segitiga) sebagai titik kesetimbangan pada data.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:mean2"></span>
<img src="mean2.PNG" alt="Pergeseran nilai mean (segitiga) ke kiri setelah penghilangan outlier." width="70%" />
<p class="caption">
Gambar 6.2: Pergeseran nilai mean (segitiga) ke kiri setelah penghilangan outlier.
</p>
</div>
<p>Pada Gambar <a href="ringkasan-numerik.html#fig:mean1">6.1</a> disajikan 7 buah data konsentrasi TSS di suatu sungai. Nilai rata-rata TSS pada sungai tersebut adalah 11 mg/l. Jika kita amati sebagian besar data (6 observasi) berada pada interval nilai konsentrasi TSS 2 sampai 12 mg/l. Observasi yang lain terletak jauh dari mayoritas observasi lainnya yaitu sebesar 37 mg/l. Observasi yang berbeda secara ekstrim dari nilai secara umum pada suatu data disebut sebagai <em>outlier</em>. Nilai <em>outlier</em> tersebut menyebabkan nilai rata-rata yang terbentuk tidak representatif terhadap keseluruhan data yang ada dan cenderung menggeser nilai rata-rata mendekati nilai <em>outlier</em> tersebut. Nilai observasi yang ekstrim biasanya muncul dari adanya kesalahan perlakuan terhadap sampel seperti botol sampel yang digunakan tidak bersih atau prosedur analisa yang dilakukan tidak standar sehingga memungkinkan adanya partikulat udara yang terukur pada proses penimbangan.</p>
<p>Salah satu cara untuk menangani adanya <em>outlier</em> tersebut adalah dengan menghapus observasi yang merupakan <em>outlier</em>. Pada Gambar <a href="ringkasan-numerik.html#fig:mean2">6.2</a> terlihat bahwa penghapusan <em>outlier</em> telah menggeser nilai rata-rata ke kiri. Nilai rata-rata yang baru tersebut jika diperhatikan dari Gambar <a href="ringkasan-numerik.html#fig:mean2">6.2</a> lebih menggambarkan keseluruhan data yang ada. Tidak terlihat adanya nilai yang berada jauh jaraknya dari nilai rata-rata yang baru.</p>
<p>Pada contoh tersebut dapat kita simpulkan bahwa nilai mean sangat sensitif terhadap adanya <em>outlier</em>. Pada prakteknya nilai mean tidaklah berdiri sendiri selama proses analisa. Nilai mean memerlukan nilai lain seperti median untuk menganalisa apakah data yang diperoleh tidak simetris yang dapat mengindikasikan adanya outlier.</p>
<p>Pada <code>R</code> untuk menghitung nilai rata-rata, kita dapat menggunakan fungsi <code>mean()</code>. Format fungsi yang digunakan dituliskan pada persamaan berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(x, <span class="dt">trim =</span> <span class="dv">0</span>, <span class="dt">na.rm =</span> <span class="ot">FALSE</span>)</code></pre></div>
<blockquote>
<p><strong>Note:</strong></p>
<ul>
<li><strong>x</strong>: objek atau vektor numerik.</li>
<li><strong>trim</strong>: menyatakan fraksi data (berkisar antara 0 sampai 0,5) yang perlu dilakukan pemotongan (<em>trim</em>) pada observasi awal dan akhir <strong>x</strong> (yang telah diurutkan) sebelum nilai mean dihitung. <strong>na.rm</strong>: nilai logis yang menyatakan apakah <em>missing value</em> perlu disertakan dalam perhitungan atau tidak. Jika disertakan maka output yang akan dihasilkan adalah NA.</li>
</ul>
</blockquote>
<p><strong>Analisa Nilai Mean Grup Data Tunggal (Single Group)</strong></p>
<p>Untuk lebih memahami penerapannya pada <code>R</code>, pada Tabel <a href="ringkasan-numerik.html#tab:debitsungai">6.1</a> berikut disajikan data terkait debit air suatu sungai.</p>
<table>
<caption><span id="tab:debitsungai">Tabel 6.1: </span>Data Debit Sampel (m3/detik)</caption>
<thead>
<tr class="header">
<th align="right">observasi</th>
<th align="right">debit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">457</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">185</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">133</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">160</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">119</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">115</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">101</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">58</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">68</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">50</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">65</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="right">128</td>
</tr>
</tbody>
</table>
<p>Data pada Tabel <a href="ringkasan-numerik.html#tab:debitsungai">6.1</a> dapat divisualisasikan seperti pada Gambar <a href="ringkasan-numerik.html#fig:debitvis">6.3</a>:</p>
<div class="figure" style="text-align: center"><span id="fig:debitvis"></span>
<img src="EnvStat_files/figure-html/debitvis-1.png" alt="Visualisasi debit sungai pada sampel" width="70%" />
<p class="caption">
Gambar 6.3: Visualisasi debit sungai pada sampel
</p>
</div>
<p>Berdasarkan Gambar <a href="ringkasan-numerik.html#fig:debitvis">6.3</a>, terdapat <em>outlier</em> yang ditunjukkan pada debit sungai yang lebih besar dari 400 m3/detik. Hasil tersebut dapat terjadi salah satunya karena adanya kondisi ekstrim seperti banjir yang menyebabkan sungai meluap atau terjadi kesalahan pengukuran dari alat ukur yang ada di lapangan.</p>
<p>Untuk menghitung nilai rata-rata debit pada data tersebut, masukkan variabel <code>debit</code> yang telah penulis simpan sebagai objek <code>sungai</code> kedalam fungsi <code>mean()</code> seperti berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(sungai<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 136.6</code></pre>
<p>Berdasarkan hasil yang diperoleh, dapat dilihat bahwa nilai rata-rata debit pada sungai tersebut adalah 136.5833 <span class="math inline">\(m^3/detik\)</span>.</p>
<p>Kita dapat menghitung nilai mean dengan terlebih dahulu menghilangkan <em>outlier</em> pada data. Untuk melakukannya kita perlu melakukan subset terhadap data tanpa <em>outlier</em> di dalamnya sebelum data tersebut dimasukkan kedalam fungsi mean(). Berikut sintaks yang digunakan untuk melakukan hal tersebut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># memuat paket</span>
<span class="kw">library</span>(dplyr)

<span class="co"># melakukan filter terhadap data</span>
sungai_subset&lt;-sungai<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(debit<span class="op">&lt;=</span><span class="dv">400</span>)

<span class="co"># menghitung mean</span>
<span class="kw">mean</span>(sungai_subset<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 107.5</code></pre>
<p>Berdasarkan hasil yang diperoleh terlihat bahwa nilai rata-rata yang baru lebih kecil dari yang sebelumnya (bergeser ke kiri) dengan nilai mean debit sungai yang baru sebesar 107.4545 <span class="math inline">\(m^3/detik\)</span>. Hal ini terjadi karena pengaruh dari data <em>outlier</em> yang telah dihilangkan.</p>
<p><strong>Analisa Nilai Rata-Rata Berdarsarkan Grup Data</strong></p>
<p>Pada contoh sebelumnya kita telah melakukan perhitungan nilai mean untuk studi kasus grup tunggal. Pada contoh ini akan disajikan contoh kasus perhitungan nilai mean untuk data berkelompok.</p>
<p>Dataset pada contoh kasus ini diambil dari buku <strong>Statistical Methods in Water Resources</strong>. Data yang digunakan adalah data konsentrasi TDS dan Uranium di airtanah dengan perbedaan konsentrasi bikarbonate dalam air tanah yaitu <span class="math inline">\(\leq 50\)</span>% (0) dan <span class="math inline">\(&gt;50\)</span>% (1). Dataset yang digunakan disajikan pada Tabel <a href="ringkasan-numerik.html#tab:gwtdsur">6.2</a>.</p>
<blockquote>
<p><strong>Note: </strong> data yang digunakan dapat diunduh pada link berikut <a href="https://drive.google.com/open?id=1-k_1Fkl2hWmI9ZohG9hWGrqKe4o8GArW">google.drive</a>. Simpan dataset tersebut pada <em>working directory</em> pembaca agar mudah dalam proses membaca data.</p>
</blockquote>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># memuat library</span>
<span class="kw">library</span>(readxl)</code></pre></div>
<pre><code>## Warning: package &#39;readxl&#39; was built under R version
## 3.5.3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># memuat data excel</span>
data_gw &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;hhappc.xls&quot;</span>, <span class="dt">sheet=</span><span class="st">&quot;appc16&quot;</span>)

<span class="co"># membuang kolom ke-4</span>
data_gw&lt;-data_gw <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(TDS, Uranium, Bicarbonate) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Bicarbonate=</span><span class="kw">as.factor</span>(Bicarbonate))</code></pre></div>
<table>
<caption><span id="tab:gwtdsur">Tabel 6.2: </span>Kosentrasi TDS dan Uranium dalam berbagai kondisi kesadahan</caption>
<thead>
<tr class="header">
<th align="right">TDS</th>
<th align="right">Uranium</th>
<th align="left">Bicarbonate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">682.6</td>
<td align="right">0.9315</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">819.1</td>
<td align="right">1.9380</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">303.8</td>
<td align="right">0.2919</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">1151.4</td>
<td align="right">11.9042</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">582.4</td>
<td align="right">1.5674</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">1043.4</td>
<td align="right">2.0623</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">634.8</td>
<td align="right">3.8858</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">1087.2</td>
<td align="right">0.9772</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">1123.5</td>
<td align="right">1.9354</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">688.1</td>
<td align="right">0.4367</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">1174.5</td>
<td align="right">10.1142</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">599.5</td>
<td align="right">0.7551</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">1240.8</td>
<td align="right">6.8559</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">538.4</td>
<td align="right">0.4806</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">607.8</td>
<td align="right">1.1452</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">705.9</td>
<td align="right">6.0876</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">1290.6</td>
<td align="right">10.8823</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">526.1</td>
<td align="right">0.1473</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">784.7</td>
<td align="right">2.6741</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">953.1</td>
<td align="right">3.0918</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">1149.3</td>
<td align="right">0.7592</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">1074.2</td>
<td align="right">3.7101</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="right">1116.6</td>
<td align="right">7.2446</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="right">301.2</td>
<td align="right">5.7129</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">265.4</td>
<td align="right">4.7366</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">295.9</td>
<td align="right">2.8057</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">442.4</td>
<td align="right">5.6290</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">342.7</td>
<td align="right">3.0950</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">361.3</td>
<td align="right">3.5774</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">262.1</td>
<td align="right">1.7711</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">546.2</td>
<td align="right">11.2724</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">273.9</td>
<td align="right">4.9807</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">281.4</td>
<td align="right">4.0833</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">588.9</td>
<td align="right">14.6342</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">574.1</td>
<td align="right">12.3835</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">307.1</td>
<td align="right">1.5291</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">409.4</td>
<td align="right">4.4647</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">327.1</td>
<td align="right">2.4574</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">425.7</td>
<td align="right">6.3042</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">310.1</td>
<td align="right">4.5441</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">289.8</td>
<td align="right">0.9672</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">408.2</td>
<td align="right">2.1568</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="right">383.0</td>
<td align="right">8.3810</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="right">255.2</td>
<td align="right">2.7957</td>
<td align="left">1</td>
</tr>
</tbody>
</table>
<p>Visualisasi data Tabel <a href="ringkasan-numerik.html#tab:gwtdsur">6.2</a>, disajikan pada Gambar <a href="ringkasan-numerik.html#fig:gwvis1">6.4</a> dan Gambar <a href="ringkasan-numerik.html#fig:gwvis2">6.5</a>:</p>
<div class="figure" style="text-align: center"><span id="fig:gwvis1"></span>
<img src="EnvStat_files/figure-html/gwvis1-1.png" alt="Visualisasi konsentrasi TDS pada air tanah" width="70%" />
<p class="caption">
Gambar 6.4: Visualisasi konsentrasi TDS pada air tanah
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:gwvis2"></span>
<img src="EnvStat_files/figure-html/gwvis2-1.png" alt="Visualisasi konsentrasi Uranium pada air tanah" width="70%" />
<p class="caption">
Gambar 6.5: Visualisasi konsentrasi Uranium pada air tanah
</p>
</div>
<p>Pada dataset tersebut kita ingin melihat apakah terdapat perbedaan antara konsentrasi TDS dan uranium pada kondisi kesadahan bikarbonat <span class="math inline">\(\leq 50\)</span>% dan <span class="math inline">\(&gt; 50\)</span>%. Untuk melakukannya pada <code>R</code> kita perlu mengelompokkan data tersebut terlebih dahulu berdasarkan variabel bikarbonat. Setelah itu nilai rata-rata dapat dihitung. Berikut sintaks yang digunakan:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data_gw <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Bicarbonate) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">TDS =</span> <span class="kw">mean</span>(TDS), <span class="dt">Uranium =</span> <span class="kw">mean</span>(Uranium))</code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   Bicarbonate   TDS Uranium
##   &lt;fct&gt;       &lt;dbl&gt;   &lt;dbl&gt;
## 1 0            864.    3.47
## 2 1            364.    5.16</code></pre>
<p>Berdasarkan hasil yang diperoleh konsentrasi TDS dan Uranium dipengaruhi oleh kesadahan airtanah. Pada konsentrasi Bikarbonate &gt; 50% konsentrasi TDS akan lebih rendah sedangkan konsentrasi Uranium sebaliknya. Untuk menguji apakah nilai tersebut berbeda signifikan, kita perlu melakukan uji hipotesis yang akan dibahas pada Chapter selanjutnya.</p>
</div>
<div id="median-sebagai-ukuran-pemusatan-data-yang-resistan" class="section level3">
<h3><span class="header-section-number">6.1.2</span> Median Sebagai Ukuran Pemusatan Data yang Resistan</h3>
<p>Median atau persentil 50 (<span class="math inline">\(P_{50}\)</span>) merupakan nilai pusat dari distribusi suatu data yang telah dirangkin berdasarkan besar nilai orbservasinya. Untuk data dengan jumlah observasi ganjil median adalah titik tengah yang memiliki jumlah observasi yang sama baik di atas nilai media maupun di bawahnya. Untuk data dengan jumlah observasi genap, media merupakan rata-rata dari dua titik observasi pusat. Untuk memperoleh median dari suatu distribusi data, langkah pertama yang perlu dilakukan adalah mengurutkan data dari observasi dengan nilai terkecil sampai dengan yang besar sehingga <span class="math inline">\(x_1\)</span> merupakan observasi terkecil hingga <span class="math inline">\(x_n\)</span> merupakan observasi terbesar. Persamaan <a href="ringkasan-numerik.html#eq:med1">(6.5)</a> (untuk data ganjil) dan Persamaan <a href="ringkasan-numerik.html#eq:med2">(6.6)</a> (untuk data genap) merupakan persamaan untuk menghitung median berdasarkan jumlah observasi yang ada.</p>
<span class="math display" id="eq:med1">\[\begin{equation}
  Median (P_{0.5}) =\frac{X_{\left(n+1\right)}}{2}
  \tag{6.5}
\end{equation}\]</span>
<span class="math display" id="eq:med2">\[\begin{equation}
  Median (P_{0.5}) =\frac{1}{2}\cdot\left(X_{\left(\frac{n}{2}\right)}+X_{\left(\frac{n}{2}\right)+1}\right)
  \tag{6.6}
\end{equation}\]</span>
<p>Median hanya dipengaruhi minimal oleh besarnya nilai observasi tunggal, yang ditentukan semata-mata oleh urutan relatif observasi. Resitensi terhadap efek dari perubahan nilai atau kehadiran pengamatan terpencil (<em>outlier</em>) sering merupakan sifat yang diinginkan. Meski demikian median memiliki kelemahan utama yaitu kurang representatif dalam mendeskripsikan rata-rata dari data dibandingkan mean. Hal ini disebabkan karena median tidak menggunakan seluruh nilai yang ada pada data.</p>
<p><strong>Analisa Nilai Median Grup Data Tunggal (Single Group)</strong></p>
<p>Kita akan menggunakan kembali data pada Tabel <a href="ringkasan-numerik.html#tab:debitsungai">6.1</a> untuk menghitung median data tersebut. Pada <code>R</code> median dihitung menggunakan fungsi <code>median()</code>. Fotmat yang digunakan adalah sebagai berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">median</span>(x, <span class="dt">na.rm =</span> <span class="ot">FALSE</span>)</code></pre></div>
<blockquote>
<p><strong>Note:</strong></p>
<ul>
<li><strong>x</strong>: objek atau vektor numerik.</li>
<li><strong>na.rm</strong>: nilai logis yang menyatakan apakah <em>missing value</em> perlu disertakan dalam komputasi atau tidak.</li>
</ul>
</blockquote>
<p>Untuk data pada Tabel <a href="ringkasan-numerik.html#tab:debitsungai">6.1</a>, median dapat dihitung menggunakan sintaks berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">median</span>(sungai<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 117</code></pre>
<p>Berdasarkan hasil komputasi diperoleh median debit sungai sebesar 117 <span class="math inline">\(m^3/detik\)</span>. Nilai tersebut tidak berbeda juah dengan nilai mean tanpa <em>outlier</em> data sungai sebesar 107.4545 <span class="math inline">\(m^3/detik\)</span>.</p>
<p>Jika kita melakukan perhitungan menggunakan menggunakan data <code>sungai_subset</code> (tanpa <em>outlier</em>), maka diperoleh 115 <span class="math inline">\(m^3/detik\)</span> yang nilainya juga tidak bergeser jauh dengan median sebelumnya yang membuktikan bahwa median resisten terhadap <em>outlier</em>.</p>
<p><strong>Analisa Nilai Median Berdarsarkan Grup Data</strong></p>
<p>Paca contoh ini kita akan menggunakan kembali data pada Tabel <a href="ringkasan-numerik.html#tab:gwtdsur">6.2</a>. Sintaks berikut adalah cara menghitung median untuk data berkelompok:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data_gw <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Bicarbonate) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">TDS=</span><span class="kw">median</span>(TDS), <span class="dt">Uranium=</span><span class="kw">median</span>(Uranium))</code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   Bicarbonate   TDS Uranium
##   &lt;fct&gt;       &lt;dbl&gt;   &lt;dbl&gt;
## 1 0            819.    1.94
## 2 1            327.    4.46</code></pre>
<p>Pada median TDS kita tidak menemui perbedaan dengan nilai rata-ratanya. Hal ini disebabkan karena bentuk distribusinya yang relatif simetris. Sedangkan pada Uranium distribusi yang terbentuk memiliki kemencengan (<em>skewness</em>) positif. Hal ini menyebabkan nilai mean yang terbentuk akan sangat dipengaruhi oleh observasi dengan nilai ekstrim yang dimiliki.</p>
</div>
<div id="ukuran-pemusatan-data-lainnya" class="section level3">
<h3><span class="header-section-number">6.1.3</span> Ukuran Pemusatan Data Lainnya</h3>
<p>Ukuran pemusatan data lainnya yang kurang sering digunakan adalah modus, rata-rata geometrik (<em>geometric mean</em>), dan <em>trimmed mean</em>. Modus merupakan nilai observasi yang sering muncul. Jika kita visualisasikan menggunakan histogram maka modus merupakan bar tertinggi pada histogram. Modus lebih dapat diaplikasikan pada data berkelompok yang nilai observasinya merupakan integer (<em>finite number</em>) dibanding data dengan nilai kontinyu. Modus sangat mudah diperoleh, namun sangat buruk sebagai ukuran pemusatan data untuk jenis data kontinyu karena sering bergantung pengelompokan data yang sewenang-wenang atu semaunya.</p>
<p><em>Geometric mean</em> sering digunakan untuk distribusi data memiliki bentuk kemencengan positif. <em>Geometric mean</em> merupakan rata-rata logaritmik yang diubah kembali ke unit asalnya. Untuk menghitungnya digunakan Persamaan <a href="ringkasan-numerik.html#eq:geomean">(6.7)</a>.</p>
<span class="math display" id="eq:geomean">\[\begin{equation}
  GM = \exp\left(\overline{Y}\right)
  \tag{6.7}
\end{equation}\]</span>
<p>dimana</p>
<span class="math display" id="eq:geomean2">\[\begin{equation}
  Y_i = \ln\left(X_i\right)
  \tag{6.8}
\end{equation}\]</span>
<p>Untuk data yang memiliki kemencengan positif, <em>geometric mean</em> biasanya cukup dekat dengan median. Bahkan, ketika logaritma data simetris, <em>geometric mean</em> adalah estimasi median. Ini karena median dan <em>geometric mean</em> sama. Ketika ditransformasikan kembali ke satuan asli, rerata geometris terus menjadi estimasi untuk median, tetapi bukan merupakan estimasi untuk rerata.</p>
<p>Pada <code>R</code> <em>geometric mean</em> dapat kita hitung menggunakan sintaks fungsi yang kita buat sendiri:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">geomean &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  y =<span class="st"> </span><span class="kw">log</span>(x)
  GM =<span class="st"> </span><span class="kw">exp</span>(<span class="kw">mean</span>(y))
  <span class="kw">return</span>(GM)
}</code></pre></div>
<p>Data pada Tabel <a href="ringkasan-numerik.html#tab:debitsungai">6.1</a> merupakan data dengan kemencengan positif. Nilai <em>geometric mean</em> data tersebut dihitung menggunakan sintaks berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">geomean</span>(sungai<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 112.4</code></pre>
<p>Berdasarkan hasil komputasi diperoleh nilai <em>geometric mean</em> debit sungai sebesar 112.4315 <span class="math inline">\(m^3/detik\)</span>. Nilai yang diperoleh tidak berbeda dengan nilai median sebesar 117 <span class="math inline">\(m^3/detik\)</span>.</p>
<p>Kompromi antara median dan mean tersedia dengan memotong beberapa observasi terendah dan tertinggi, dan menghitung mean dari apa yang tersisa. Perkiraan pemusatan data seperti itu tidak dipengaruhi oleh observasi yang paling ekstrem (dan mungkin anomali), seperti mean. Namun mereka memungkinkan besarnya sebagian besar nilai untuk mempengaruhi estimasi, tidak seperti median. Estimator ini disebut “<em>trimmed mean</em>”, dan persentase data yang diinginkan dapat dipangkas. Pemangkasan yang paling umum adalah menghapus 25 persen dari data di setiap ujung - rata-rata yang dihasilkan dari 50 persen pusat data biasanya disebut “<em>trimmed mean</em>”, tetapi lebih tepatnya 25 persen <em>trimmed mean</em>. “<em>trimmed mean</em> 0%” adalah mean sampel itu sendiri, sementara memangkas semua kecuali 1 atau 2 nilai pusat menghasilkan median. Persentase pemangkasan harus secara eksplisit dinyatakan saat digunakan. <em>Trimmed mean</em> adalah estimator yang resistan, karena tidak sangat dipengaruhi oleh <em>outlier</em>, dan bekerja dengan baik untuk berbagai macam bentuk distribusi (normal, lognormal, dll). Ini dapat dianggap sebagai rata-rata tertimbang (<em>weighted mean</em>), di mana data di luar ‘jendela’ cutoff diberi bobot 0, dan mereka yang berada di dalam jendela bobot 1,0 (lihat Gambar <a href="ringkasan-numerik.html#fig:tm">6.6</a>).</p>
<div class="figure" style="text-align: center"><span id="fig:tm"></span>
<img src="tm.PNG" alt="Jendela diagram trimmed mean." width="70%" />
<p class="caption">
Gambar 6.6: Jendela diagram trimmed mean.
</p>
</div>
<p>Pada <code>R</code> <em>trimmed mean</em> dapat dihitung dengan spesifikasi argumen <code>trim</code> pada fungsi <code>mean()</code>. Pada data debit sungai (Tabel <a href="ringkasan-numerik.html#tab:debitsungai">6.1</a>) dihitung <em>trimmed mean</em> dengan data yang dipangkas adalah 5% di kedua ujung observasi atau <code>trim=0.1</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(sungai<span class="op">$</span>debit, <span class="dt">trim=</span><span class="fl">0.1</span>)</code></pre></div>
<pre><code>## [1] 113.2</code></pre>
<p>Nilai yang diperoleh sekarang mendekati nilai median dan <em>geometric mean</em> yaitu sebesar 113.2 <span class="math inline">\(m^3/detik\)</span>.</p>
</div>
</div>
<div id="ukuran-sebaran-data" class="section level2">
<h2><span class="header-section-number">6.2</span> Ukuran Sebaran Data</h2>
<p>Saat kita mengetahui kedalaman rata-rata sungai, kita pasti ingin mengetahui berapa interval atau variasi dari kedalamannya. Kita tidak cukup hanya dengan mengetahui nilai pemusatan datanya saja, kita juga perlu mengetahui seberapa besar variasi atau variabilitas datanya.</p>
<p>Variabilitas suatu data diukur dengan melihat sebaran data dari nilai rata-ratanya (mean). Semakin besar sebaran suatu data, semakin tidak berarti nilai rata-ratanya karena nilai rata-ratanya bisa sangat berbeda dari sejumlah nilai pada datanya.</p>
<div id="pengukuran-klasik-varian-dan-simpangan-baku" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Pengukuran Klasik (Varian dan Simpangan Baku)</h3>
<p>Varian sampel dan nilai akar dari varian sampel (Simpangan Baku) merupakan ukuran penyebaran data klasik. Sama dengan mean varian dan simpangan baku dipengaruhi oleh <em>outlier</em>. Semakin besar nilai keduanya, semakin besar variabilitas datanya. Kedua ukuran tersebut dinyatakan pada Persamaan <a href="ringkasan-numerik.html#eq:var">(6.9)</a> dan Persamaan <a href="ringkasan-numerik.html#eq:sd">(6.10)</a>.</p>
<p><strong>Varian Sampel</strong></p>
<span class="math display" id="eq:var">\[\begin{equation}
  s^2=\sum_{i=1}^n\frac{\left(X_i-\overline{X}\right)^2}{\left(n-1\right)}
  \tag{6.9}
\end{equation}\]</span>
<p><strong>simpangan baku</strong></p>
<span class="math display" id="eq:sd">\[\begin{equation}
  s=\sqrt{s^2}
  \tag{6.10}
\end{equation}\]</span>
<p>Kedua nilai tersebut di hitung berdasarkan kuadrat deviasi nilai observasi dari rata-ratanya, sehingga jika pada data terdapat <em>outlier</em> maka nilai outlier akan memperbesar deviasi data dari nilai mean. Ketika <em>outlier</em> hadir, pengukuran menjadi tidak stabil. Hal ini akan memberi kesan sebaran data menjadi jauh lebih besar daripada yang ditunjukkan oleh mayoritas nilai pada data.</p>
<p>Varian dan simpangan baku pada <code>R</code> dihitung menggunakan fungsi <code>var()</code> (varian) dan <code>sd()</code>. Format yang digunakan adalah sebagai berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var</span>(x, <span class="dt">na.rm =</span> <span class="ot">FALSE</span>)
<span class="kw">sd</span>(x, <span class="dt">na.rm =</span> <span class="ot">FALSE</span>)</code></pre></div>
<blockquote>
<p><strong>Note:</strong></p>
<ul>
<li><strong>x</strong>: objek atau vektor numerik.</li>
<li><strong>na.rm</strong>: nilai logis yang menyatakan apakah <em>missing value</em> perlu disertakan dalam komputasi atau tidak.</li>
</ul>
</blockquote>
<p><strong>Analisa Varian dan simpangan baku Grup Tunggal</strong></p>
<p>Kita akan menggunakan kembali data pada Tabel <a href="ringkasan-numerik.html#tab:debitsungai">6.1</a> untuk menghitung varian dan simpangan baku data tersebut. Berikut adalah sintaks untuk melakukannya:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># varian data sungai</span>
<span class="kw">var</span>(sungai<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 11926</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># simpangan baku data sungai</span>
<span class="kw">sd</span>(sungai<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 109.2</code></pre>
<p>Sekarang mari kita bandingkan dengan data yang tidak menyertakan outlier.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># varian data sungai</span>
<span class="kw">var</span>(sungai_subset<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 1919</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># simpangan baku data sungai</span>
<span class="kw">sd</span>(sungai_subset<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 43.8</code></pre>
<p>Berdasarkan hasil yang diperoleh terlihat bahwa nilai varian dan simpangan baku data dengan <em>outlier</em> jauh lebih besar dibanding data tanpa <em>outlier</em>.</p>
<p><strong>Analisa Varian dan simpangan baku Multi Grup</strong></p>
<p>Paca contoh ini kita akan menggunakan kembali data pada Tabel <a href="ringkasan-numerik.html#tab:gwtdsur">6.2</a>. Sintaks berikut adalah cara menghitung varian dan simpangan baku untuk data berkelompok:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data_gw <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Bicarbonate) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">var_TDS=</span><span class="kw">var</span>(TDS), <span class="dt">var_Uranium=</span><span class="kw">var</span>(Uranium),
            <span class="dt">sd_TDS=</span><span class="kw">sd</span>(TDS), <span class="dt">sd_Uranium=</span><span class="kw">sd</span>(Uranium))</code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   Bicarbonate var_TDS var_Uranium sd_TDS sd_Uranium
##   &lt;fct&gt;         &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
## 1 0            79471.        13.0   282.       3.61
## 2 1            10559.        13.5   103.       3.68</code></pre>
<p>Jika kita perhatikan nilai varian dan simpangan baku Uranium pada dua kondisi kesadahan memiliki nilai yang nyaris sama. Hal sebaliknya terjadi pada variabel TDS yang menunjukkan perbedaan pada dua ukuran sebaran datanya. TDS pada kesadahan &gt;50% memiliki varian dan simpangan baku yang lebih kecil dibanding kondisi kesadahan satunya, yang menunjukkan data pada kondisi kesadahan &gt;50% lebih tidak tersebar dibanding kesadahan satunya.</p>
</div>
<div id="ukuran-sebaran-data-yang-resisten-terhadap-outlier" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Ukuran Sebaran Data yang Resisten Terhadap Outlier</h3>
<p>Simpangan kuartil atau <em>interquartile range</em> (IQR) merupakan ukuran sebaran data yang resisten dan paling sering digunakan. IQR mengukur kisaran 50% pusat data sehingga pengukuran tidak dipengaruhi oleh adanya outlier pada 25% pada data pada setiap ujungnya. Untuk visualisasinya kita dapat melihat kembali pada ambar <a href="ringkasan-numerik.html#fig:tm">6.6</a>.</p>
<p>IQR didefinisikan sebagai persentil ke-75 dikurangi dengan persentil ke-25. Persentil ke-75, ke-50 (median) dan ke-25 membagi data menjadi empat tempat berukuran sama. Persentil ke-75 (<span class="math inline">\(P_{.75}\)</span>), juga disebut kuartil atas, adalah nilai yang melebihi tidak lebih dari 75% data dan dilampaui oleh tidak lebih dari 25 persen data. Persentil ke-25 (<span class="math inline">\(P_{.25}\)</span>) atau kuartil lebih rendah adalah nilai yang melebihi tidak lebih dari 25% dari data dan dilampaui oleh tidak lebih dari 75%. Dengan mempertimbangkan data yang telah diurutkan dari yang terkecil ke yang terbesar: <span class="math inline">\(X_{i}\)</span>, <span class="math inline">\(i=1,...n\)</span>. Persentil (<span class="math inline">\(P_j\)</span>) dihitung berdasarkan Persamaan <a href="ringkasan-numerik.html#eq:iqr">(6.11)</a>.</p>
<span class="math display" id="eq:iqr">\[\begin{equation}
  P_j=X_{\left(n+1\right)\cdot j}
  \tag{6.11}
\end{equation}\]</span>
<p>dimana <span class="math inline">\(n\)</span> merupakan ukuran sampel <span class="math inline">\(X_j\)</span>, dan <span class="math inline">\(j\)</span> merupakan fraksi data yang kurang dari atau sama dengan nilai persentil (untuk persentil ke-25, 50, dan 75, <span class="math inline">\(j=.25, .50., dan .75\)</span>).</p>
<p>Pada <code>R</code>, IQR dapat dihitung secara langsung menggunakan fungsi <code>IQR()</code> atau secara tidak langsung menggunakan fungsi <code>quantile()</code>. Penggunaan fungsi <code>quantile()</code> digunakan untuk mencari persentil dari data. Telah dijelaskan sebelumnya bahwa IQR merupakan selisih dari persentil 75 dan persentil 25. Format yang digunakan untuk menghitung IQR adalah sebagai berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># secara langsung</span>
<span class="kw">IQR</span>(x, <span class="dt">na.rm=</span><span class="ot">FALSE</span>)

<span class="co"># secara tidak langsung</span>
<span class="kw">quantile</span>(x, <span class="dv">3</span><span class="op">/</span><span class="dv">4</span>)<span class="op">-</span><span class="kw">quantile</span>(x, <span class="dv">1</span><span class="op">/</span><span class="dv">4</span>)

<span class="co"># atau</span>
<span class="kw">quantile</span>(x, .<span class="dv">75</span>)<span class="op">-</span><span class="kw">quantile</span>(x, .<span class="dv">25</span>)</code></pre></div>
<blockquote>
<p><strong>Note:</strong></p>
<ul>
<li><strong>x</strong>: objek atau vektor numerik.</li>
<li><strong>na.rm</strong>: nilai logis yang menyatakan apakah <em>missing value</em> perlu disertakan dalam komputasi atau tidak.</li>
</ul>
</blockquote>
<p>Pada Tabel <a href="ringkasan-numerik.html#tab:debitsungai">6.1</a>, kita dapat menghitung IQR dari data. Berikut adalah contoh sintaks yang digunakan:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">IQR</span>(sungai<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 72.5</code></pre>
<p>Salah satu penaksir penyebaran yang resisten selain IQR adalah <em>Median Absolute Deviation</em>, atau MAD. MAD dihitung dengan pertama-tama mendaftar nilai absolut dari semua selisih <span class="math inline">\(|d|\)</span> antara masing-masing pengamatan dan median. Median dari nilai absolut ini adalah MAD yang ditulis berdasarkan Persamaan <a href="ringkasan-numerik.html#eq:mad">(6.12)</a>.</p>
<span class="math display" id="eq:mad">\[\begin{equation}
  MAD\ \left(X_i\right)=median\left|d\right|
  \tag{6.12}
\end{equation}\]</span>
<p>dimana</p>
<span class="math display" id="eq:mad2">\[\begin{equation}
  d_i=X_i-median\left(X_i\right)
  \tag{6.13}
\end{equation}\]</span>
<p>Pada <code>R</code>, MAD tidak dapat dihitung secara langsung. Kita perlu membuat <em>user defined function</em> untuk dapat digunakan sewaktu-waktu. Berikut adalah fungsi yang dibuat:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">MAD &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  <span class="co"># median data</span>
  m =<span class="st"> </span><span class="kw">median</span>(x)
  <span class="co"># MAD</span>
  d =<span class="st"> </span><span class="kw">abs</span>(x<span class="op">-</span>m)
  mad =<span class="st"> </span><span class="kw">mean</span>(d)
  <span class="co"># print</span>
  <span class="kw">return</span> (mad)
}</code></pre></div>
<p>Pada Tabel <a href="ringkasan-numerik.html#tab:debitsungai">6.1</a>, kita dapat menghitung MAD dari data menggunakan fungsi yang telah dibuat. Berikut adalah contoh sintaks yang digunakan:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">MAD</span>(sungai<span class="op">$</span>debit)</code></pre></div>
<pre><code>## [1] 60.42</code></pre>
</div>
</div>
<div id="ringkasan-data-menggunakan-fungsi-summary-dan-stat.desc" class="section level2">
<h2><span class="header-section-number">6.3</span> Ringkasan Data Menggunakan Fungsi summary() dan stat.desc()</h2>
<p>Ringkasan data menggunakan fungsi <code>summary()</code> akan memberikan ringkasan data seperti nilai mean, kuartil, nilai minimum dan maksimum, serta <em>missing value</em>. Jika data berupa variabel tunggal maka output yang dihasilkan berupa nilai-nilai yang telah penulis sebutkan sebelumnya. Berikut adalah contoh sintaks yang digunakan:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(sungai<span class="op">$</span>debit)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    50.0    67.2   117.0   136.6   139.8   457.0</code></pre>
<p>Jika objek yang diinputkan kedalam fungsi tersebut adalah data frame, maka ringkasan data akan diberikan pada setiap kolom dengan ketentuan berikut:</p>
<ul>
<li>jika kolom berupa variabel numerik maka output yang diperoleh berupa mean, median, min, max dan kuartil.</li>
<li>jika kolom berupa factor maka output yang dihasilkan berupa rekapan jumlah observasi pada masing-masing grup.</li>
</ul>
<p>Berikut adalah contoh sintaks penerapannya:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(data_gw)</code></pre></div>
<pre><code>##       TDS          Uranium       Bicarbonate
##  Min.   : 255   Min.   : 0.147   0:23       
##  1st Qu.: 323   1st Qu.: 1.558   1:21       
##  Median : 560   Median : 3.093              
##  Mean   : 626   Mean   : 4.276              
##  3rd Qu.: 853   3rd Qu.: 5.807              
##  Max.   :1291   Max.   :14.634</code></pre>
<p>Ringkasan data lain dapat dilakukan dengan menggunakan fungsi <code>stat.desc()</code> dari library <code>pastecs</code>. Kelebihan dari ringkasan data menggunakan fungsi ini adalah kita tidak hanya memperoleh ringkasan data dengan ouput seperti diatas, namun kita juga memperoleh output berupa nilai <em>standadr error</em> (SE), <em>confidence interval</em> (CI), dan koefisien variasi (coef.var) yang merupakan hasil bagi dari simpangan baku dibagi dengan nilai rata-rata.</p>
<p>Berikut adalah sintak yang digunakan untuk menghasilkan ringkasan data menggunakan fungsi <code>stat.desc()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># memasang paket</span>
<span class="kw">install.packages</span>(<span class="st">&quot;pastecs&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># memuat paket</span>
<span class="kw">library</span>(pastecs)</code></pre></div>
<pre><code>## Warning: package &#39;pastecs&#39; was built under R version
## 3.5.3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># ringkasan data</span>
<span class="kw">stat.desc</span>(data_gw)</code></pre></div>
<pre><code>##                    TDS  Uranium Bicarbonate
## nbr.val      4.400e+01  44.0000          NA
## nbr.null     0.000e+00   0.0000          NA
## nbr.na       0.000e+00   0.0000          NA
## min          2.552e+02   0.1473          NA
## max          1.291e+03  14.6342          NA
## range        1.035e+03  14.4869          NA
## sum          2.753e+04 188.1604          NA
## median       5.602e+02   3.0934          NA
## mean         6.257e+02   4.2764          NA
## SE.mean      4.986e+01   0.5572          NA
## CI.mean.0.95 1.005e+02   1.1238          NA
## var          1.094e+05  13.6623          NA
## std.dev      3.307e+02   3.6963          NA
## coef.var     5.286e-01   0.8643          NA</code></pre>
</div>
<div id="ukuran-kemencengan-data" class="section level2">
<h2><span class="header-section-number">6.4</span> Ukuran Kemencengan Data</h2>
<p>Ketika data memiliki kemencengan, nilai mean tidak sama dengan median, tetapi bergeser ke arah ekor distribusi. Jadi untuk kemencengan positif, nilai mean melebihi lebih dari 50% dari data, seperti pada Gambar <a href="ringkasan-numerik.html#fig:skew">6.7</a> dan Gambar <a href="ringkasan-numerik.html#fig:skew2">6.8</a>. Simpangan baku juga meningkat dengan data di bagian ekor. Data yang menceng juga mempertanyakan penerapan tes hipotesis yang didasarkan pada asumsi bahwa data memiliki distribusi normal. Tes-tes ini, yang disebut tes parametrik, mungkin bernilai dipertanyakan ketika diterapkan pada data seperti data sumber daya air, karena data seringkali tidak normal atau bahkan simetris.</p>
<div class="figure" style="text-align: center"><span id="fig:skew"></span>
<img src="skewness.PNG" alt="a) Kemencengan negatif, b) Kemencengan positif." width="70%" />
<p class="caption">
Gambar 6.7: a) Kemencengan negatif, b) Kemencengan positif.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:skew2"></span>
<img src="skewnessbox.png" alt="Box plot untuk data dengan a) Kemencengan negatif, b) Kemencengan positif." width="70%" />
<p class="caption">
Gambar 6.8: Box plot untuk data dengan a) Kemencengan negatif, b) Kemencengan positif.
</p>
</div>
<div id="ukuran-kemencengan-klasik" class="section level3">
<h3><span class="header-section-number">6.4.1</span> Ukuran Kemencengan Klasik</h3>
<p>Koefisien kemencengan (<span class="math inline">\(g\)</span>) merupakan ukuran kemencengan yang sering digunakan. Koefisien kemencengan dituliskan pada Persamaan <a href="ringkasan-numerik.html#eq:g">(6.14)</a>.</p>
<span class="math display" id="eq:g">\[\begin{equation}
  g=\frac{n}{\left(n-1\right)\left(n-2\right)}\sum_{i=1}^n\frac{\left(x_i-\overline{X}\right)^3}{s^3}
  \tag{6.14}
\end{equation}\]</span>
<p>Kemencengan positif (ekor panjang kekanan) memiliki nilai <span class="math inline">\(g\)</span> positif sedangkan kemencengan negatif (ekor panjang kekiri) memiliki nilai <span class="math inline">\(g\)</span> negatif. Sekali lagi, Pengaruh beberapa <em>outlier</em> adalah penting - suatu distribusi simetris yang memiliki satu <em>outlier</em> akan menghasilkan ukuran kemencengan (<span class="math inline">\(g\)</span>) yang besar (dan mungkin menyesatkan).</p>
<p>Pada <code>R</code> Kita dapat menghitung sendiri koefisien kemencengan (<span class="math inline">\(g\)</span>) menggunakan <em>user define function</em>. Berikut adalah contoh sintaks fungsi yang dibuat:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">skew &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  ave =<span class="st"> </span><span class="kw">mean</span>(x)
  n =<span class="st"> </span><span class="kw">length</span>(x)
  sd =<span class="st"> </span><span class="kw">sd</span>(x)
  g=(n<span class="op">/</span>((n<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>(n<span class="op">-</span><span class="dv">2</span>)))<span class="op">*</span><span class="kw">sum</span>(((x<span class="op">-</span>ave)<span class="op">^</span><span class="dv">3</span>)<span class="op">/</span>(sd<span class="op">^</span><span class="dv">3</span>))
  <span class="kw">return</span>(g)
}</code></pre></div>
<p>Pada contoh sebelumnya dengan menggunakan fungsi yang telah dibuat diperoleh koefisien kemencengan sebagai berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">skew</span>(data_gw<span class="op">$</span>Uranium)</code></pre></div>
<pre><code>## [1] 1.184</code></pre>
</div>
<div id="ukuran-kemencengan-yang-resisten" class="section level3">
<h3><span class="header-section-number">6.4.2</span> Ukuran Kemencengan yang Resisten</h3>
<p>Ukuran kemencengan yang lebih resisten adalah <em>quartile skew coefficient</em> (<span class="math inline">\(qs\)</span>). Merupakan ukuran kemencengan didasarkan pada ketiga nilai kuartil data seperti yang ditunjukkan pada Persamaan <a href="ringkasan-numerik.html#eq:qs">(6.15)</a> yang menyatakan perbedaan pada jarak kuartil atas dan bawah terhadap median dibagi dengan IQR.</p>
<span class="math display" id="eq:qs">\[\begin{equation}
  qs=\frac{\left(P_{.75}-P_{.50}\right)-\left(P_{.75}-P_{.25}\right)}{P_{.75}-P_{.25}}
  \tag{6.15}
\end{equation}\]</span>
<p>Kemencengan positif akan memiliki nilai <span class="math inline">\(qs\)</span> positif dan begitupun sebaliknya. Pada <code>R</code> kita dapat menghitung nilai <span class="math inline">\(qs\)</span> menggunakan <em>user define function</em>. Berikut adalah contoh sintaks fungsi yang dibuat:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">qs &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  p75 =<span class="st"> </span><span class="kw">quantile</span>(x, <span class="dv">3</span><span class="op">/</span><span class="dv">4</span>)
  p50 =<span class="st"> </span><span class="kw">median</span>(x)
  p25 =<span class="st"> </span><span class="kw">quantile</span>(x, <span class="dv">1</span><span class="op">/</span><span class="dv">4</span>)
  skew =<span class="st"> </span>((p75<span class="op">-</span>p50)<span class="op">-</span>(p50<span class="op">-</span>p25))<span class="op">/</span>(p75<span class="op">-</span>p25)
  <span class="kw">return</span>(skew)
}</code></pre></div>
<p>Pada contoh sebelumnya dengan menggunakan fungsi yang telah dibuat diperoleh koefisien kemencengan sebagai berikut:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qs</span>(data_gw<span class="op">$</span>Uranium)</code></pre></div>
<pre><code>##    75% 
## 0.2772</code></pre>
</div>
</div>
<div id="outlier" class="section level2">
<h2><span class="header-section-number">6.5</span> Outlier</h2>
<p><em>Outlier</em> merupakan pengamatan yang nilainya sangat berbeda dari yang lain dalam kumpulan data, sering menimbulkan kekhawatiran atau alarm. Meskipun sebenarnya kita tidak perlu khawatir dengan adanya <em>outlier</em> . <em>Outlier</em> sering ditangani dengan membuangnya sebelum mendeskripsikan data, atau sebelum beberapa prosedur uji hipotesis chapter-chapter selanjutnya. Sekali lagi, mereka seharusnya tidak perlu dikhawatirkan. <em>Outlier</em> mungkin merupakan poin paling penting dalam kumpulan data dan harus diselidiki lebih lanjut.</p>
<p>Untuk lebih memahami kenapa <em>outlier</em> begitu penting pada data kita berikut merupakan contoh kasus dari asal kata <em>outlier</em>. Misalkan bahwa data pada “lubang” ozon Antartika, suatu daerah dengan konsentrasi ozon yang sangat rendah, telah dikumpulkan selama kurang lebih 10 tahun sebelum penemuan aktualnya. Namun, rutinitas pengecekan data otomatis selama pemrosesan data menyertakan instruksi untuk menghapus “<em>outlier</em>”. Definisi <em>outlier</em> didasarkan pada konsentrasi ozon yang ditemukan pada pertengahan garis lintang. Dengan demikian semua data yang tidak biasa ini tidak pernah dilihat atau dipelajari selama beberapa waktu. Jika <em>outlier</em> dihapus, risiko diambil hanya dengan melihat apa yang diharapkan dilihat. Jika hal tersebut dilakukan maka anomali yang terjadi pada atmosfer dapat luput kita pelajari.</p>
<p>Berdasarkan kasus tersebut kita perlu dengan baik mempertimbangkan apakah <em>outlier</em> pada data perlu dihapus atau tidak. Jika berkaitan dengan pembuatan model, penghapusan <em>outlier</em> merupakan sesuatu yang dapat memperbaiki akurasi dari model. Namun, pada sebuah penelitian terkadang diperlukan informasi lebih lanjut mengapa terdapat <em>outlier</em> pada data sehingga kita dapat memperoleh pengetahuan baru dari proses pencarian tersebut.</p>
<p><em>Outlier</em> dapat terjadi karena tiga hal, yaitu:</p>
<ol style="list-style-type: decimal">
<li>Kesalahan pengukuran atau perekaman data.</li>
<li>Observasi dari populasi tidak sama dengan sebagian besar data seperti misalnya data debit banji akibat jebolnya sebuah bendungan akan berbeda dengan debit banjir akibat presipitasi.</li>
<li>Kejadian langka pada sebuah populasi yang sedikit memiliki kemencengan pada distribusinya.</li>
</ol>
<p>Metode grafis seperti box plot sangat membantu dalam mengidentifikasi <em>outlier</em>. Setiap kali <em>outlier</em> terjadi, pertama-tama verifikasi bahwa tidak ada penyalinan, titik desimal, atau kesalahan nyata lainnya yang telah dibuat. Jika tidak, tidak mungkin untuk menentukan apakah titik itu valid. Upaya yang dilakukan untuk verifikasi, seperti menjalankan kembali sampel di laboratorium, akan tergantung pada manfaat yang diperoleh versus biaya verifikasi. Kejadian masa lalu mungkin tidak dapat diduplikasi. Jika tidak ada kesalahan yang dapat dideteksi dan diperbaiki, ** <em>outlier</em> tidak boleh dibuang hanya berdasarkan fakta bahwa mereka tampak tidak biasa**. <em>Outlier</em> sering dibuang untuk membuat data cocok dengan distribusi teoretis yang sudah terbentuk sebelumnya seperti distribusi normal. Tidak ada alasan untuk menganggap bahwa mereka seharusnya dibuang! Seluruh rangkaian data dapat muncul dari distribusi yang memiliki kemencengan, dan mengambil logaritma atau transformasi lain dapat menghasilkan data yang cukup simetris. Bahkan jika tidak ada transformasi yang mencapai simetri, outlier tidak perlu dibuang. Daripada menghilangkan data aktual (dan mungkin sangat penting) untuk menggunakan prosedur analisis yang membutuhkan simetri atau normalitas, prosedur yang tahan terhadap <em>outlier</em> harus digunakan. Jika menghitung rata-rata tampak bernilai kecil karena <em>outlier</em>, median telah terbukti menjadi ukuran lokasi yang lebih tepat untuk data yang memiliki kemencengan. Jika melakukan uji-t (dijelaskan pada chapter selanjutnya) tampaknya tidak valid karena set data yang tidak normal, gunakan <em>rank-sum test</em> sebagai gantinya.</p>
<p>Singkatnya, biarkan panduan data prosedur analisis yang digunakan, daripada mengubah data untuk menggunakan beberapa prosedur yang memiliki persyaratan terlalu ketat untuk situasi yang dihadapi.</p>
</div>
<div id="transformasi-data-1" class="section level2">
<h2><span class="header-section-number">6.6</span> Transformasi Data</h2>
<p>Transformasi data dilakukan untuk memenuhi tiga tujuan, antara lain:</p>
<ol style="list-style-type: decimal">
<li>membuat data lebih simetris,</li>
<li>membuat data lebih linier, dan</li>
<li>membuat data memiliki varian yang konsisten.</li>
</ol>
<p>Beberapa ilmuwan lingkungan takut bahwa dengan mentransformasikan data, hasilnya diperoleh yang sesuai dengan gagasan yang telah terbentuk sebelumnya. Oleh karena itu, transformasi adalah metode untuk <strong>melihat apa yang ingin kita lihat</strong> dari data. Namun dalam kenyataannya, masalah serius dapat terjadi ketika prosedur dengan asumsi simetri, linieritas, atau homoseksualitas (varians konstan) digunakan pada data yang tidak memiliki karakteristik yang diperlukan ini. Transformasi dapat menghasilkan karakteristik ini, dan dengan demikian penggunaan variabel yang diubah memenuhi tujuan.</p>
<p>Satu unit pengukuran tidak lebih valid secara apriori daripada yang lainnya. Sebagai contoh, logaritma negatif konsentrasi ion hidrogen (pH), sama validnya dengan sistem pengukuran dengan konsentrasi ion hidrogen itu sendiri. Transformasi seperti akar kuadrat kedalaman air pada sumur sumur, atau akar kubik volume curah hujan, seharusnya tidak mengandung stigma lebih daripada pH. Skala pengukuran ini mungkin lebih sesuai untuk analisis data daripada unit aslinya. Hoaglin (1988) telah menulis artikel yang bagus tentang transformasi tersembunyi, secara konsisten diterima begitu saja, yang umum digunakan oleh semua orang. Oktaf dalam musik adalah transformasi frekuensi logaritmik. Setiap kali piano dimainkan, transformasi logaritmik digunakan! Begitu pula dengan skala Richter untukgempa bumi, mil per galon untuk konsumsi bensin, f-stop untuk eksposur kamera, dll. semua menggunakan transformasi. Dalam ilmu analisis data, keputusan yang menggunakan skala pengukuran harus ditentukan oleh data, bukan dengan kriteria yang ditentukan sebelumnya. Tujuan penggunaan transformasi adalah untuk kesimetrian, linieritas, dan homoskedastisitas. Selain itu, penggunaan banyak teknik tahan seperti persentil dan prosedur uji nonparametrik (akan dibahas kemudian) tidak berbeda dengan skala pengukuran. Hasil <em>rank-sum test</em>, setara nonparametrik dari uji-t, akan persis sama apakah unit asli atau logaritma dari unit tersebut digunakan.</p>
<p>Untuk membuat distribusi asimetris menjadi lebih simetris, data dapat diubah atau diekspresikan kembali menjadi unit baru. Unit-unit baru ini mengubah jarak antara pengamatan pada plot garis. Efeknya adalah memperluas atau mengecilkan jarak ke pengamatan ekstrem di satu sisi median, membuatnya lebih pada setiap sisinya. Transformasi yang paling umum digunakan dalam bidang lingkungan adalah logaritma, seperti Log debit air, konduktivitas hidrolik, atau konsentrasi sering diambil sebelum analisis statistik dilakukan.</p>
<p>Transformasi data biasanya melibatkan fungsi power seperti pada fungsi <span class="math inline">\(y=x^\theta\)</span>, dimana x merupakan data yang belum ditransformasi, y adalah data yang telah ditransformasi, dan <span class="math inline">\(\theta\)</span> merupakan power eksponensial. Pada Gambar <a href="ringkasan-numerik.html#fig:power">6.9</a> nilai <span class="math inline">\(\theta\)</span> di-list kedalam “<em>ladder of powers</em>” (Velleman dan Hoaglin, 1981 dalam helsel dan Hirsch, 2002), sebuah struktur yang berguna untuk menentukan nilai <span class="math inline">\(\theta\)</span> yang tepat.</p>
<div class="figure" style="text-align: center"><span id="fig:power"></span>
<img src="ladder.PNG" alt="Ladder of power" width="70%" />
<p class="caption">
Gambar 6.9: Ladder of power
</p>
</div>
<p>Seperti yang dapat dilihat dari <em>ladder of powers</em>, setiap transformasi dengan <span class="math inline">\(\theta\)</span> kurang dari 1 dapat digunakan untuk membuat data dengan kemencengan positif lebih simetris. Dengan membuat box plot atau plot Q-Q dari data yang diubah kita dapat mengetahui apakah transformasi yang telah dilakukan sesuai. Jika transformasi logaritmik memberikan kompensasi yang berlebihan untuk kemiringan yang tepat dan menghasilkan distribusi yang sedikit kiri (kemencengan negatif), transformasi ‘lebih ringan’ dengan <span class="math inline">\(\theta\)</span> lebih dekat ke 1, seperti transformasi kuadrat atau akar kubik, harus digunakan. Transformasi dengan <span class="math inline">\(\theta\)</span>&gt; 1 akan membantu membuat data yang condong ke kiri lebih simetris.</p>
<p>Namun, kecenderungan untuk mencari transformasi ‘terbaik’ harus dihindari. Misalnya, ketika berhadapan dengan beberapa set data yang serupa, mungkin lebih baik untuk menemukan satu transformasi yang bekerja cukup baik untuk semua, daripada menggunakan yang sedikit berbeda untuk masing-masingnya. Harus diingat bahwa setiap set data adalah sampel dari populasi yang lebih besar, dan sampel lain dari populasi yang sama kemungkinan akan menunjukkan transformasi ‘terbaik’ yang sedikit berbeda. Penentuan ‘terbaik’ dalam ketelitian tinggi adalah pendekatan yang jarang sepadan dengan usaha.</p>
<p>Pada Gambar <a href="ringkasan-numerik.html#fig:gwvis2">6.5</a> kosentrasi distribusi <code>Uranium</code> pada tiap grup memiliki kemencengan positif. Untuk membuatnya simetris kita perlu melakukan transformasi yang sesuai jenis transformasi yang dilakukan dapat dimulai dari akar kuadrat sampai invers akar kuadrat (berdasarkan Gambar <a href="ringkasan-numerik.html#fig:power">6.9</a>). Pada contoh ini kita akan mencoba melakukan trasnformasi logaritmik. Berikut adalah contoh visualisasi hasil transformasinya (lihat Gambar <a href="ringkasan-numerik.html#fig:urantrans">6.10</a>:</p>
<div class="figure" style="text-align: center"><span id="fig:urantrans"></span>
<img src="EnvStat_files/figure-html/urantrans-1.png" alt="Visualisasi konsentrasi Uranium  hasil tansformasi pada air tanah" width="70%" />
<p class="caption">
Gambar 6.10: Visualisasi konsentrasi Uranium hasil tansformasi pada air tanah
</p>
</div>
<p>Berdasarkan hasil transformasi, kita telah memperoleh ditribusi yang cukup simetris untuk kedua grup data tersebut. Pembaca dapat mencobanya menggunakan transformasi lainnya sendiri.</p>
</div>
<div id="referensi-5" class="section level2">
<h2><span class="header-section-number">6.7</span> Referensi</h2>
<ol style="list-style-type: decimal">
<li>Damanhuri, E. 2011. <strong>Statitika Lingkunga</strong>. Penerbit ITB.</li>
<li>Helsel, D.R., Hirsch, R.M. 2002. <strong>statistical Methods in Water Resources</strong>. USGS.</li>
<li>Ofungwu, J. 2014. <strong>Statistical Applications For Environmental Analysis and Risk Assessment</strong>. John Wiley &amp; Sons, Inc.</li>
<li>Rosadi, D. 2015. <strong>Analisis Statistika dengan R</strong>. Gadjah Mada University Press.</li>
<li>STHDA. <strong>Descriptive Statistics and Graphics</strong>. <a href="http://www.sthda.com/english/wiki/descriptive-statistics-and-graphics" class="uri">http://www.sthda.com/english/wiki/descriptive-statistics-and-graphics</a>.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="visualisasi-data-menggunakan-ggplot.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ekplorasi-data-menggunakan-grafik.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["EnvStat.pdf", "EnvStat.epub"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
